// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthTokenResponseTokenType.
const (
	Bearer AuthTokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthTokenResponseTokenType enum.
func (e AuthTokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for AuthenticatedUserSystemRole.
const (
	SYSTEMADMIN AuthenticatedUserSystemRole = "SYSTEM_ADMIN"
	USER        AuthenticatedUserSystemRole = "USER"
)

// Valid indicates whether the value is a known member of the AuthenticatedUserSystemRole enum.
func (e AuthenticatedUserSystemRole) Valid() bool {
	switch e {
	case SYSTEMADMIN:
		return true
	case USER:
		return true
	default:
		return false
	}
}

// Defines values for ComponentStatus.
const (
	ComponentStatusDisabled    ComponentStatus = "disabled"
	ComponentStatusOk          ComponentStatus = "ok"
	ComponentStatusUnavailable ComponentStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ComponentStatus enum.
func (e ComponentStatus) Valid() bool {
	switch e {
	case ComponentStatusDisabled:
		return true
	case ComponentStatusOk:
		return true
	case ComponentStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded    HealthStatus = "degraded"
	HealthStatusOk          HealthStatus = "ok"
	HealthStatusUnavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	case HealthStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for SessionSummaryStatus.
const (
	ACTIVE  SessionSummaryStatus = "ACTIVE"
	EXPIRED SessionSummaryStatus = "EXPIRED"
	REVOKED SessionSummaryStatus = "REVOKED"
)

// Valid indicates whether the value is a known member of the SessionSummaryStatus enum.
func (e SessionSummaryStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case EXPIRED:
		return true
	case REVOKED:
		return true
	default:
		return false
	}
}

// AuthTokenResponse defines model for AuthTokenResponse.
type AuthTokenResponse struct {
	AccessToken string `json:"accessToken"`

	// ExpiresIn 访问令牌剩余有效秒数。
	ExpiresIn int64                      `json:"expiresIn"`
	RequestId string                     `json:"requestId"`
	Session   SessionSummary             `json:"session"`
	TokenType AuthTokenResponseTokenType `json:"tokenType"`
	User      AuthenticatedUser          `json:"user"`
}

// AuthTokenResponseTokenType defines model for AuthTokenResponse.TokenType.
type AuthTokenResponseTokenType string

// AuthenticatedUser defines model for AuthenticatedUser.
type AuthenticatedUser struct {
	DisplayName string                      `json:"displayName"`
	Locale      string                      `json:"locale"`
	SystemRole  AuthenticatedUserSystemRole `json:"systemRole"`
	Timezone    string                      `json:"timezone"`
	UserId      openapi_types.UUID          `json:"userId"`
	Username    string                      `json:"username"`
}

// AuthenticatedUserSystemRole defines model for AuthenticatedUser.SystemRole.
type AuthenticatedUserSystemRole string

// ComponentHealth defines model for ComponentHealth.
type ComponentHealth struct {
	LatencyMs int64           `json:"latencyMs"`
	Message   *string         `json:"message,omitempty"`
	Status    ComponentStatus `json:"status"`
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus string

// CurrentSessionResponse defines model for CurrentSessionResponse.
type CurrentSessionResponse struct {
	RequestId string            `json:"requestId"`
	Session   SessionSummary    `json:"session"`
	User      AuthenticatedUser `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"requestId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks    map[string]ComponentHealth `json:"checks"`
	RequestId string                     `json:"requestId"`
	Service   string                     `json:"service"`
	Status    HealthStatus               `json:"status"`
	Timestamp time.Time                  `json:"timestamp"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	DeviceId *string `json:"deviceId,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page     Page     `json:"page"`
	PageSize PageSize `json:"pageSize"`
	Total    *int64   `json:"total,omitempty"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	CreatedAt  time.Time            `json:"createdAt"`
	DeviceId   *string              `json:"deviceId,omitempty"`
	ExpiresAt  time.Time            `json:"expiresAt"`
	LastSeenAt *time.Time           `json:"lastSeenAt,omitempty"`
	SessionId  openapi_types.UUID   `json:"sessionId"`
	Status     SessionSummaryStatus `json:"status"`
}

// SessionSummaryStatus defines model for SessionSummary.Status.
type SessionSummaryStatus string

// IdempotencyKeyHeader defines model for IdempotencyKeyHeader.
type IdempotencyKeyHeader = string

// PageQuery defines model for PageQuery.
type PageQuery = int

// PageSizeQuery defines model for PageSizeQuery.
type PageSizeQuery = int

// AccountLocked defines model for AccountLocked.
type AccountLocked = ErrorResponse

// AuthRequired defines model for AuthRequired.
type AuthRequired = ErrorResponse

// InvalidCredentials defines model for InvalidCredentials.
type InvalidCredentials = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// SecurityRejected defines model for SecurityRejected.
type SecurityRejected = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 使用用户名和密码登录
	// (POST /api/v1/auth/login)
	Login(c *gin.Context)
	// Logout 注销当前会话
	// (POST /api/v1/auth/logout)
	Logout(c *gin.Context)
	// RefreshSession 轮换 Refresh Token 并签发新访问令牌
	// (POST /api/v1/auth/refresh)
	RefreshSession(c *gin.Context)
	// GetCurrentSession 获取当前认证会话
	// (GET /api/v1/auth/session)
	GetCurrentSession(c *gin.Context)
	// GetLiveness 检查进程是否存活
	// (GET /health/live)
	GetLiveness(c *gin.Context)
	// GetReadiness 检查节点是否可以接收流量
	// (GET /health/ready)
	GetReadiness(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshSession(c)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentSession(c)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLiveness(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health/live", wrapper.GetLiveness)
	router.GET(options.BaseURL+"/health/ready", wrapper.GetReadiness)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshSession)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/v1/auth/session", wrapper.GetCurrentSession)
}

type AccountLockedResponseHeaders struct {
	XRequestID *string
}
type AccountLockedJSONResponse struct {
	Body ErrorResponse

	Headers AccountLockedResponseHeaders
}

type AuthRequiredResponseHeaders struct {
	XRequestID *string
}
type AuthRequiredJSONResponse struct {
	Body ErrorResponse

	Headers AuthRequiredResponseHeaders
}

type InvalidCredentialsResponseHeaders struct {
	XRequestID *string
}
type InvalidCredentialsJSONResponse struct {
	Body ErrorResponse

	Headers InvalidCredentialsResponseHeaders
}

type InvalidRequestResponseHeaders struct {
	XRequestID *string
}
type InvalidRequestJSONResponse struct {
	Body ErrorResponse

	Headers InvalidRequestResponseHeaders
}

type SecurityRejectedResponseHeaders struct {
	XRequestID *string
}
type SecurityRejectedJSONResponse struct {
	Body ErrorResponse

	Headers SecurityRejectedResponseHeaders
}

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
	XRequestID *string
}
type TooManyRequestsJSONResponse struct {
	Body ErrorResponse

	Headers TooManyRequestsResponseHeaders
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	CacheControl *string
	SetCookie    *string
	XRequestID   *string
}

type Login200JSONResponse struct {
	Body    AuthTokenResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ InvalidRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ InvalidCredentialsJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login403JSONResponse struct{ SecurityRejectedJSONResponse }

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Login423JSONResponse struct{ AccountLockedJSONResponse }

func (response Login423JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(423)
	_, err := buf.WriteTo(w)
	return err
}

type Login429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie  *string
	XRequestID *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(204)
	return nil
}

type Logout403JSONResponse struct{ SecurityRejectedJSONResponse }

func (response Logout403JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSessionRequestObject struct {
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

type RefreshSession200ResponseHeaders struct {
	CacheControl *string
	SetCookie    *string
	XRequestID   *string
}

type RefreshSession200JSONResponse struct {
	Body    AuthTokenResponse
	Headers RefreshSession200ResponseHeaders
}

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession401JSONResponse struct{ AuthRequiredJSONResponse }

func (response RefreshSession401JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession403JSONResponse struct{ SecurityRejectedJSONResponse }

func (response RefreshSession403JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSessionRequestObject struct {
}

type GetCurrentSessionResponseObject interface {
	VisitGetCurrentSessionResponse(w http.ResponseWriter) error
}

type GetCurrentSession200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *string
}

type GetCurrentSession200JSONResponse struct {
	Body    CurrentSessionResponse
	Headers GetCurrentSession200ResponseHeaders
}

func (response GetCurrentSession200JSONResponse) VisitGetCurrentSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSession401JSONResponse struct{ AuthRequiredJSONResponse }

func (response GetCurrentSession401JSONResponse) VisitGetCurrentSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200ResponseHeaders struct {
	XRequestID *string
}

type GetLiveness200JSONResponse struct {
	Body    HealthResponse
	Headers GetLiveness200ResponseHeaders
}

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200ResponseHeaders struct {
	XRequestID *string
}

type GetReadiness200JSONResponse struct {
	Body    HealthResponse
	Headers GetReadiness200ResponseHeaders
}

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ResponseHeaders struct {
	XRequestID *string
}

type GetReadiness503JSONResponse struct {
	Body    HealthResponse
	Headers GetReadiness503ResponseHeaders
}

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login 使用用户名和密码登录
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout 注销当前会话
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RefreshSession 轮换 Refresh Token 并签发新访问令牌
	// (POST /api/v1/auth/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// GetCurrentSession 获取当前认证会话
	// (GET /api/v1/auth/session)
	GetCurrentSession(ctx context.Context, request GetCurrentSessionRequestObject) (GetCurrentSessionResponseObject, error)
	// GetLiveness 检查进程是否存活
	// (GET /health/live)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// GetReadiness 检查节点是否可以接收流量
	// (GET /health/ready)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(ctx *gin.Context) {
	var request RefreshSessionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx, request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentSession operation middleware
func (sh *strictHandler) GetCurrentSession(ctx *gin.Context) {
	var request GetCurrentSessionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentSession(ctx, request.(GetCurrentSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetCurrentSessionResponseObject); ok {
		if err := validResponse.VisitGetCurrentSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(ctx *gin.Context) {
	var request GetLivenessRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx *gin.Context) {
	var request GetReadinessRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
