// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditChainHeads = `-- name: CountAuditChainHeads :one
SELECT count(*)::bigint
FROM audit_chain_heads
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
  AND ($3::text IS NULL OR status = $3::text)
`

type CountAuditChainHeadsParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
	Status   pgtype.Text
}

func (q *Queries) CountAuditChainHeads(ctx context.Context, arg *CountAuditChainHeadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditChainHeads, arg.DateFrom, arg.DateTo, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAuditChainHeadsByStatus = `-- name: CountAuditChainHeadsByStatus :many
SELECT status, count(*)::bigint AS chain_count
FROM audit_chain_heads
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
GROUP BY status
ORDER BY status ASC
`

type CountAuditChainHeadsByStatusParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
}

type CountAuditChainHeadsByStatusRow struct {
	Status     string
	ChainCount int64
}

func (q *Queries) CountAuditChainHeadsByStatus(ctx context.Context, arg *CountAuditChainHeadsByStatusParams) ([]*CountAuditChainHeadsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAuditChainHeadsByStatus, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountAuditChainHeadsByStatusRow{}
	for rows.Next() {
		var i CountAuditChainHeadsByStatusRow
		if err := rows.Scan(&i.Status, &i.ChainCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*)::bigint
FROM audit_events
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
  AND ($3::text IS NULL OR event_type = $3::text)
  AND ($4::text IS NULL OR risk_level = $4::text)
  AND ($5::text IS NULL OR actor_type = $5::text)
  AND ($6::uuid IS NULL OR actor_id = $6::uuid)
  AND ($7::text IS NULL OR resource_type = $7::text)
  AND ($8::uuid IS NULL OR resource_id = $8::uuid)
  AND ($9::text IS NULL OR result = $9::text)
  AND ($10::uuid IS NULL OR request_id = $10::uuid)
`

type CountAuditEventsParams struct {
	DateFrom     pgtype.Date
	DateTo       pgtype.Date
	EventType    pgtype.Text
	RiskLevel    pgtype.Text
	ActorType    pgtype.Text
	ActorID      pgtype.UUID
	ResourceType pgtype.Text
	ResourceID   pgtype.UUID
	Result       pgtype.Text
	RequestID    pgtype.UUID
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg *CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.DateFrom,
		arg.DateTo,
		arg.EventType,
		arg.RiskLevel,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.RequestID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAuditEventsByActorType = `-- name: CountAuditEventsByActorType :many
SELECT actor_type, count(*)::bigint AS event_count
FROM audit_events
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
GROUP BY actor_type
ORDER BY actor_type ASC
`

type CountAuditEventsByActorTypeParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
}

type CountAuditEventsByActorTypeRow struct {
	ActorType  string
	EventCount int64
}

func (q *Queries) CountAuditEventsByActorType(ctx context.Context, arg *CountAuditEventsByActorTypeParams) ([]*CountAuditEventsByActorTypeRow, error) {
	rows, err := q.db.Query(ctx, countAuditEventsByActorType, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountAuditEventsByActorTypeRow{}
	for rows.Next() {
		var i CountAuditEventsByActorTypeRow
		if err := rows.Scan(&i.ActorType, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEventsByResult = `-- name: CountAuditEventsByResult :many
SELECT result, count(*)::bigint AS event_count
FROM audit_events
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
GROUP BY result
ORDER BY result ASC
`

type CountAuditEventsByResultParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
}

type CountAuditEventsByResultRow struct {
	Result     string
	EventCount int64
}

func (q *Queries) CountAuditEventsByResult(ctx context.Context, arg *CountAuditEventsByResultParams) ([]*CountAuditEventsByResultRow, error) {
	rows, err := q.db.Query(ctx, countAuditEventsByResult, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountAuditEventsByResultRow{}
	for rows.Next() {
		var i CountAuditEventsByResultRow
		if err := rows.Scan(&i.Result, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEventsByRiskLevel = `-- name: CountAuditEventsByRiskLevel :many
SELECT risk_level, count(*)::bigint AS event_count
FROM audit_events
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
GROUP BY risk_level
ORDER BY risk_level ASC
`

type CountAuditEventsByRiskLevelParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
}

type CountAuditEventsByRiskLevelRow struct {
	RiskLevel  string
	EventCount int64
}

func (q *Queries) CountAuditEventsByRiskLevel(ctx context.Context, arg *CountAuditEventsByRiskLevelParams) ([]*CountAuditEventsByRiskLevelRow, error) {
	rows, err := q.db.Query(ctx, countAuditEventsByRiskLevel, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountAuditEventsByRiskLevelRow{}
	for rows.Next() {
		var i CountAuditEventsByRiskLevelRow
		if err := rows.Scan(&i.RiskLevel, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditChainHeadForUpdate = `-- name: GetAuditChainHeadForUpdate :one
SELECT chain_id, partition_date, last_sequence_number, last_event_id, last_hash,
  batch_root, anchor_location, status, verified_at, created_at, updated_at, row_version
FROM audit_chain_heads
WHERE chain_id = $1
  AND partition_date = $2::date
FOR UPDATE
`

type GetAuditChainHeadForUpdateParams struct {
	ChainID string
	Column2 pgtype.Date
}

func (q *Queries) GetAuditChainHeadForUpdate(ctx context.Context, arg *GetAuditChainHeadForUpdateParams) (*AuditChainHead, error) {
	row := q.db.QueryRow(ctx, getAuditChainHeadForUpdate, arg.ChainID, arg.Column2)
	var i AuditChainHead
	err := row.Scan(
		&i.ChainID,
		&i.PartitionDate,
		&i.LastSequenceNumber,
		&i.LastEventID,
		&i.LastHash,
		&i.BatchRoot,
		&i.AnchorLocation,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT
  audit_event_id, event_type, risk_level, actor_type, actor_id, actor_display_name,
  actor_employee_no, effective_role, admin_delegation_id, share_id, resource_type,
  resource_id, resource_name, space_id, organization_id, document_id, document_version_id,
  action, result, failure_code, source_channel, COALESCE(host(ip_address)::text, '') AS ip_address,
  user_agent, request_id, trace_id, correlation_id, reason, metadata_schema_version,
  metadata_json, hash_schema_version, chain_id, sequence_number, previous_hash,
  event_hash, partition_date, created_at
FROM audit_events
WHERE partition_date = $1::date
  AND audit_event_id = $2::uuid
`

type GetAuditEventParams struct {
	Column1 pgtype.Date
	Column2 pgtype.UUID
}

type GetAuditEventRow struct {
	AuditEventID          pgtype.UUID
	EventType             string
	RiskLevel             string
	ActorType             string
	ActorID               pgtype.UUID
	ActorDisplayName      pgtype.Text
	ActorEmployeeNo       pgtype.Text
	EffectiveRole         pgtype.Text
	AdminDelegationID     pgtype.UUID
	ShareID               pgtype.UUID
	ResourceType          pgtype.Text
	ResourceID            pgtype.UUID
	ResourceName          pgtype.Text
	SpaceID               pgtype.UUID
	OrganizationID        pgtype.UUID
	DocumentID            pgtype.UUID
	DocumentVersionID     pgtype.UUID
	Action                string
	Result                string
	FailureCode           pgtype.Text
	SourceChannel         string
	IpAddress             interface{}
	UserAgent             pgtype.Text
	RequestID             pgtype.UUID
	TraceID               pgtype.Text
	CorrelationID         pgtype.UUID
	Reason                pgtype.Text
	MetadataSchemaVersion int32
	MetadataJson          []byte
	HashSchemaVersion     pgtype.Int4
	ChainID               pgtype.Text
	SequenceNumber        pgtype.Int8
	PreviousHash          []byte
	EventHash             []byte
	PartitionDate         pgtype.Date
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetAuditEvent(ctx context.Context, arg *GetAuditEventParams) (*GetAuditEventRow, error) {
	row := q.db.QueryRow(ctx, getAuditEvent, arg.Column1, arg.Column2)
	var i GetAuditEventRow
	err := row.Scan(
		&i.AuditEventID,
		&i.EventType,
		&i.RiskLevel,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplayName,
		&i.ActorEmployeeNo,
		&i.EffectiveRole,
		&i.AdminDelegationID,
		&i.ShareID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.SpaceID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.DocumentVersionID,
		&i.Action,
		&i.Result,
		&i.FailureCode,
		&i.SourceChannel,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.TraceID,
		&i.CorrelationID,
		&i.Reason,
		&i.MetadataSchemaVersion,
		&i.MetadataJson,
		&i.HashSchemaVersion,
		&i.ChainID,
		&i.SequenceNumber,
		&i.PreviousHash,
		&i.EventHash,
		&i.PartitionDate,
		&i.CreatedAt,
	)
	return &i, err
}

const insertAuditChainHead = `-- name: InsertAuditChainHead :exec
INSERT INTO audit_chain_heads (
  chain_id, partition_date, last_sequence_number, last_event_id, last_hash,
  status, created_at, updated_at
) VALUES (
  $1, $2::date, $3, $4::uuid, $5, 'ACTIVE', $6, $6
)
`

type InsertAuditChainHeadParams struct {
	ChainID            string
	Column2            pgtype.Date
	LastSequenceNumber int64
	Column4            pgtype.UUID
	LastHash           []byte
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertAuditChainHead(ctx context.Context, arg *InsertAuditChainHeadParams) error {
	_, err := q.db.Exec(ctx, insertAuditChainHead,
		arg.ChainID,
		arg.Column2,
		arg.LastSequenceNumber,
		arg.Column4,
		arg.LastHash,
		arg.CreatedAt,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
  audit_event_id, event_type, risk_level, actor_type, actor_id, actor_display_name,
  actor_employee_no, effective_role, admin_delegation_id, share_id, resource_type,
  resource_id, resource_name, space_id, organization_id, document_id, document_version_id,
  action, result, failure_code, source_channel, request_id, trace_id, correlation_id,
  reason, metadata_schema_version, metadata_json, hash_schema_version, chain_id,
  sequence_number, previous_hash, event_hash, partition_date, created_at
) VALUES (
  $1::uuid, $2, $3, $4, $5::uuid, $6, $7, $8, $9::uuid, $10::uuid, $11,
  $12::uuid, $13, $14::uuid, $15::uuid, $16::uuid, $17::uuid, $18, $19, $20,
  $21, $22::uuid, $23, $24::uuid, $25, $26, $27::jsonb, $28, $29, $30,
  $31, $32, $33, $34
)
`

type InsertAuditEventParams struct {
	Column1               pgtype.UUID
	EventType             string
	RiskLevel             string
	ActorType             string
	Column5               pgtype.UUID
	ActorDisplayName      pgtype.Text
	ActorEmployeeNo       pgtype.Text
	EffectiveRole         pgtype.Text
	Column9               pgtype.UUID
	Column10              pgtype.UUID
	ResourceType          pgtype.Text
	Column12              pgtype.UUID
	ResourceName          pgtype.Text
	Column14              pgtype.UUID
	Column15              pgtype.UUID
	Column16              pgtype.UUID
	Column17              pgtype.UUID
	Action                string
	Result                string
	FailureCode           pgtype.Text
	SourceChannel         string
	Column22              pgtype.UUID
	TraceID               pgtype.Text
	Column24              pgtype.UUID
	Reason                pgtype.Text
	MetadataSchemaVersion int32
	Column27              []byte
	HashSchemaVersion     pgtype.Int4
	ChainID               pgtype.Text
	SequenceNumber        pgtype.Int8
	PreviousHash          []byte
	EventHash             []byte
	PartitionDate         pgtype.Date
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg *InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.Column1,
		arg.EventType,
		arg.RiskLevel,
		arg.ActorType,
		arg.Column5,
		arg.ActorDisplayName,
		arg.ActorEmployeeNo,
		arg.EffectiveRole,
		arg.Column9,
		arg.Column10,
		arg.ResourceType,
		arg.Column12,
		arg.ResourceName,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.Column17,
		arg.Action,
		arg.Result,
		arg.FailureCode,
		arg.SourceChannel,
		arg.Column22,
		arg.TraceID,
		arg.Column24,
		arg.Reason,
		arg.MetadataSchemaVersion,
		arg.Column27,
		arg.HashSchemaVersion,
		arg.ChainID,
		arg.SequenceNumber,
		arg.PreviousHash,
		arg.EventHash,
		arg.PartitionDate,
		arg.CreatedAt,
	)
	return err
}

const listAuditChainEventsForVerify = `-- name: ListAuditChainEventsForVerify :many
SELECT audit_event_id, event_type, risk_level, actor_type, actor_id, actor_display_name,
  actor_employee_no, effective_role, admin_delegation_id, share_id, resource_type,
  resource_id, resource_name, space_id, organization_id, document_id, document_version_id,
  action, result, failure_code, source_channel, request_id, trace_id, correlation_id,
  reason, metadata_schema_version, metadata_json, hash_schema_version, chain_id,
  sequence_number, previous_hash, event_hash, partition_date, created_at
FROM audit_events
WHERE partition_date = $1::date
  AND chain_id = $2
ORDER BY sequence_number ASC
`

type ListAuditChainEventsForVerifyParams struct {
	Column1 pgtype.Date
	ChainID pgtype.Text
}

type ListAuditChainEventsForVerifyRow struct {
	AuditEventID          pgtype.UUID
	EventType             string
	RiskLevel             string
	ActorType             string
	ActorID               pgtype.UUID
	ActorDisplayName      pgtype.Text
	ActorEmployeeNo       pgtype.Text
	EffectiveRole         pgtype.Text
	AdminDelegationID     pgtype.UUID
	ShareID               pgtype.UUID
	ResourceType          pgtype.Text
	ResourceID            pgtype.UUID
	ResourceName          pgtype.Text
	SpaceID               pgtype.UUID
	OrganizationID        pgtype.UUID
	DocumentID            pgtype.UUID
	DocumentVersionID     pgtype.UUID
	Action                string
	Result                string
	FailureCode           pgtype.Text
	SourceChannel         string
	RequestID             pgtype.UUID
	TraceID               pgtype.Text
	CorrelationID         pgtype.UUID
	Reason                pgtype.Text
	MetadataSchemaVersion int32
	MetadataJson          []byte
	HashSchemaVersion     pgtype.Int4
	ChainID               pgtype.Text
	SequenceNumber        pgtype.Int8
	PreviousHash          []byte
	EventHash             []byte
	PartitionDate         pgtype.Date
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListAuditChainEventsForVerify(ctx context.Context, arg *ListAuditChainEventsForVerifyParams) ([]*ListAuditChainEventsForVerifyRow, error) {
	rows, err := q.db.Query(ctx, listAuditChainEventsForVerify, arg.Column1, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAuditChainEventsForVerifyRow{}
	for rows.Next() {
		var i ListAuditChainEventsForVerifyRow
		if err := rows.Scan(
			&i.AuditEventID,
			&i.EventType,
			&i.RiskLevel,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorEmployeeNo,
			&i.EffectiveRole,
			&i.AdminDelegationID,
			&i.ShareID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.SpaceID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentVersionID,
			&i.Action,
			&i.Result,
			&i.FailureCode,
			&i.SourceChannel,
			&i.RequestID,
			&i.TraceID,
			&i.CorrelationID,
			&i.Reason,
			&i.MetadataSchemaVersion,
			&i.MetadataJson,
			&i.HashSchemaVersion,
			&i.ChainID,
			&i.SequenceNumber,
			&i.PreviousHash,
			&i.EventHash,
			&i.PartitionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditChainHeads = `-- name: ListAuditChainHeads :many
SELECT chain_id, partition_date, last_sequence_number, last_event_id, last_hash,
  batch_root, anchor_location, status, verified_at, created_at, updated_at, row_version
FROM audit_chain_heads
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY partition_date DESC, chain_id ASC
OFFSET $4::bigint
LIMIT $5::integer
`

type ListAuditChainHeadsParams struct {
	DateFrom   pgtype.Date
	DateTo     pgtype.Date
	Status     pgtype.Text
	PageOffset int64
	PageSize   int32
}

func (q *Queries) ListAuditChainHeads(ctx context.Context, arg *ListAuditChainHeadsParams) ([]*AuditChainHead, error) {
	rows, err := q.db.Query(ctx, listAuditChainHeads,
		arg.DateFrom,
		arg.DateTo,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditChainHead{}
	for rows.Next() {
		var i AuditChainHead
		if err := rows.Scan(
			&i.ChainID,
			&i.PartitionDate,
			&i.LastSequenceNumber,
			&i.LastEventID,
			&i.LastHash,
			&i.BatchRoot,
			&i.AnchorLocation,
			&i.Status,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
  audit_event_id, event_type, risk_level, actor_type, actor_id, actor_display_name,
  actor_employee_no, effective_role, admin_delegation_id, share_id, resource_type,
  resource_id, resource_name, space_id, organization_id, document_id, document_version_id,
  action, result, failure_code, source_channel, COALESCE(host(ip_address)::text, '') AS ip_address,
  user_agent, request_id, trace_id, correlation_id, reason, metadata_schema_version,
  metadata_json, hash_schema_version, chain_id, sequence_number, previous_hash,
  event_hash, partition_date, created_at
FROM audit_events
WHERE partition_date >= $1::date
  AND partition_date <= $2::date
  AND ($3::text IS NULL OR event_type = $3::text)
  AND ($4::text IS NULL OR risk_level = $4::text)
  AND ($5::text IS NULL OR actor_type = $5::text)
  AND ($6::uuid IS NULL OR actor_id = $6::uuid)
  AND ($7::text IS NULL OR resource_type = $7::text)
  AND ($8::uuid IS NULL OR resource_id = $8::uuid)
  AND ($9::text IS NULL OR result = $9::text)
  AND ($10::uuid IS NULL OR request_id = $10::uuid)
ORDER BY created_at DESC, audit_event_id DESC
OFFSET $11::bigint
LIMIT $12::integer
`

type ListAuditEventsParams struct {
	DateFrom     pgtype.Date
	DateTo       pgtype.Date
	EventType    pgtype.Text
	RiskLevel    pgtype.Text
	ActorType    pgtype.Text
	ActorID      pgtype.UUID
	ResourceType pgtype.Text
	ResourceID   pgtype.UUID
	Result       pgtype.Text
	RequestID    pgtype.UUID
	PageOffset   int64
	PageSize     int32
}

type ListAuditEventsRow struct {
	AuditEventID          pgtype.UUID
	EventType             string
	RiskLevel             string
	ActorType             string
	ActorID               pgtype.UUID
	ActorDisplayName      pgtype.Text
	ActorEmployeeNo       pgtype.Text
	EffectiveRole         pgtype.Text
	AdminDelegationID     pgtype.UUID
	ShareID               pgtype.UUID
	ResourceType          pgtype.Text
	ResourceID            pgtype.UUID
	ResourceName          pgtype.Text
	SpaceID               pgtype.UUID
	OrganizationID        pgtype.UUID
	DocumentID            pgtype.UUID
	DocumentVersionID     pgtype.UUID
	Action                string
	Result                string
	FailureCode           pgtype.Text
	SourceChannel         string
	IpAddress             interface{}
	UserAgent             pgtype.Text
	RequestID             pgtype.UUID
	TraceID               pgtype.Text
	CorrelationID         pgtype.UUID
	Reason                pgtype.Text
	MetadataSchemaVersion int32
	MetadataJson          []byte
	HashSchemaVersion     pgtype.Int4
	ChainID               pgtype.Text
	SequenceNumber        pgtype.Int8
	PreviousHash          []byte
	EventHash             []byte
	PartitionDate         pgtype.Date
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg *ListAuditEventsParams) ([]*ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.DateFrom,
		arg.DateTo,
		arg.EventType,
		arg.RiskLevel,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.RequestID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.AuditEventID,
			&i.EventType,
			&i.RiskLevel,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorEmployeeNo,
			&i.EffectiveRole,
			&i.AdminDelegationID,
			&i.ShareID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.SpaceID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentVersionID,
			&i.Action,
			&i.Result,
			&i.FailureCode,
			&i.SourceChannel,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.TraceID,
			&i.CorrelationID,
			&i.Reason,
			&i.MetadataSchemaVersion,
			&i.MetadataJson,
			&i.HashSchemaVersion,
			&i.ChainID,
			&i.SequenceNumber,
			&i.PreviousHash,
			&i.EventHash,
			&i.PartitionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuditChainInvalid = `-- name: MarkAuditChainInvalid :execrows
UPDATE audit_chain_heads
SET status = 'INVALID',
    verified_at = $3,
    updated_at = $3,
    row_version = row_version + 1
WHERE chain_id = $1
  AND partition_date = $2::date
`

type MarkAuditChainInvalidParams struct {
	ChainID    string
	Column2    pgtype.Date
	VerifiedAt pgtype.Timestamptz
}

func (q *Queries) MarkAuditChainInvalid(ctx context.Context, arg *MarkAuditChainInvalidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAuditChainInvalid, arg.ChainID, arg.Column2, arg.VerifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAuditChainVerified = `-- name: MarkAuditChainVerified :execrows
UPDATE audit_chain_heads
SET status = 'ACTIVE',
    verified_at = $3,
    updated_at = $3,
    row_version = row_version + 1
WHERE chain_id = $1
  AND partition_date = $2::date
`

type MarkAuditChainVerifiedParams struct {
	ChainID    string
	Column2    pgtype.Date
	VerifiedAt pgtype.Timestamptz
}

func (q *Queries) MarkAuditChainVerified(ctx context.Context, arg *MarkAuditChainVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAuditChainVerified, arg.ChainID, arg.Column2, arg.VerifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAuditChainHead = `-- name: UpdateAuditChainHead :execrows
UPDATE audit_chain_heads
SET last_sequence_number = $3,
    last_event_id = $4::uuid,
    last_hash = $5,
    updated_at = $6,
    row_version = row_version + 1
WHERE chain_id = $1
  AND partition_date = $2::date
  AND status = 'ACTIVE'
`

type UpdateAuditChainHeadParams struct {
	ChainID            string
	Column2            pgtype.Date
	LastSequenceNumber int64
	Column4            pgtype.UUID
	LastHash           []byte
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateAuditChainHead(ctx context.Context, arg *UpdateAuditChainHeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAuditChainHead,
		arg.ChainID,
		arg.Column2,
		arg.LastSequenceNumber,
		arg.Column4,
		arg.LastHash,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
