// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: background.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEventsByType = `-- name: ClaimOutboxEventsByType :many
WITH candidates AS (
  SELECT outbox_event_id
  FROM outbox_events
  WHERE event_type = $4::varchar
    AND attempt_count < max_attempts
    AND (
      (status = 'PENDING' AND available_at <= $2::timestamptz)
      OR (status = 'FAILED' AND COALESCE(next_retry_at, available_at) <= $2::timestamptz)
      OR (status = 'PROCESSING' AND lease_until <= $2::timestamptz)
    )
  ORDER BY priority DESC, available_at, outbox_event_id
  LIMIT $5::integer
  FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events e
SET status = 'PROCESSING',
    attempt_count = e.attempt_count + 1,
    locked_by = $1::varchar,
    locked_at = $2::timestamptz,
    lease_until = $3::timestamptz,
    next_retry_at = NULL,
    updated_at = $2::timestamptz,
    row_version = e.row_version + 1
FROM candidates c
WHERE e.outbox_event_id = c.outbox_event_id
RETURNING e.outbox_event_id, e.aggregate_type, e.aggregate_id, e.aggregate_version, e.event_type, e.event_schema_version, e.payload_json, e.deduplication_key, e.correlation_id, e.causation_id, e.priority, e.status, e.attempt_count, e.max_attempts, e.available_at, e.locked_by, e.locked_at, e.lease_until, e.next_retry_at, e.created_at, e.updated_at, e.published_at, e.last_error_code, e.last_error_summary, e.row_version
`

type ClaimOutboxEventsByTypeParams struct {
	LockedBy   string
	Now        pgtype.Timestamptz
	LeaseUntil pgtype.Timestamptz
	EventType  string
	BatchSize  int32
}

func (q *Queries) ClaimOutboxEventsByType(ctx context.Context, arg *ClaimOutboxEventsByTypeParams) ([]*OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEventsByType,
		arg.LockedBy,
		arg.Now,
		arg.LeaseUntil,
		arg.EventType,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.OutboxEventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.EventType,
			&i.EventSchemaVersion,
			&i.PayloadJson,
			&i.DeduplicationKey,
			&i.CorrelationID,
			&i.CausationID,
			&i.Priority,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.LeaseUntil,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.LastErrorCode,
			&i.LastErrorSummary,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboxEventsByStatus = `-- name: CountOutboxEventsByStatus :many
SELECT status, count(*)::bigint AS count
FROM outbox_events
GROUP BY status
ORDER BY status
`

type CountOutboxEventsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountOutboxEventsByStatus(ctx context.Context) ([]*CountOutboxEventsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOutboxEventsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountOutboxEventsByStatusRow{}
	for rows.Next() {
		var i CountOutboxEventsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDead = `-- name: MarkOutboxEventDead :execrows
UPDATE outbox_events
SET status = 'DEAD',
    locked_by = NULL,
    locked_at = NULL,
    lease_until = NULL,
    next_retry_at = NULL,
    last_error_code = $1::varchar,
    last_error_summary = $2::text,
    updated_at = $3::timestamptz,
    row_version = row_version + 1
WHERE outbox_event_id = $4::uuid
  AND status = 'PROCESSING'
  AND locked_by = $5::varchar
  AND row_version = $6::bigint
`

type MarkOutboxEventDeadParams struct {
	LastErrorCode    string
	LastErrorSummary string
	Now              pgtype.Timestamptz
	OutboxEventID    pgtype.UUID
	LockedBy         string
	RowVersion       int64
}

func (q *Queries) MarkOutboxEventDead(ctx context.Context, arg *MarkOutboxEventDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventDead,
		arg.LastErrorCode,
		arg.LastErrorSummary,
		arg.Now,
		arg.OutboxEventID,
		arg.LockedBy,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :execrows
UPDATE outbox_events
SET status = 'FAILED',
    locked_by = NULL,
    locked_at = NULL,
    lease_until = NULL,
    next_retry_at = $1::timestamptz,
    last_error_code = $2::varchar,
    last_error_summary = $3::text,
    updated_at = $4::timestamptz,
    row_version = row_version + 1
WHERE outbox_event_id = $5::uuid
  AND status = 'PROCESSING'
  AND locked_by = $6::varchar
  AND row_version = $7::bigint
  AND attempt_count < max_attempts
`

type MarkOutboxEventFailedParams struct {
	NextRetryAt      pgtype.Timestamptz
	LastErrorCode    string
	LastErrorSummary string
	Now              pgtype.Timestamptz
	OutboxEventID    pgtype.UUID
	LockedBy         string
	RowVersion       int64
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg *MarkOutboxEventFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventFailed,
		arg.NextRetryAt,
		arg.LastErrorCode,
		arg.LastErrorSummary,
		arg.Now,
		arg.OutboxEventID,
		arg.LockedBy,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :execrows
UPDATE outbox_events
SET status = 'PUBLISHED',
    locked_by = NULL,
    locked_at = NULL,
    lease_until = NULL,
    next_retry_at = NULL,
    last_error_code = NULL,
    last_error_summary = NULL,
    published_at = $1::timestamptz,
    updated_at = $1::timestamptz,
    row_version = row_version + 1
WHERE outbox_event_id = $2::uuid
  AND status = 'PROCESSING'
  AND locked_by = $3::varchar
  AND row_version = $4::bigint
`

type MarkOutboxEventPublishedParams struct {
	PublishedAt   pgtype.Timestamptz
	OutboxEventID pgtype.UUID
	LockedBy      string
	RowVersion    int64
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg *MarkOutboxEventPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventPublished,
		arg.PublishedAt,
		arg.OutboxEventID,
		arg.LockedBy,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewOutboxEventLease = `-- name: RenewOutboxEventLease :execrows
UPDATE outbox_events
SET lease_until = $1::timestamptz,
    updated_at = $2::timestamptz,
    row_version = row_version + 1
WHERE outbox_event_id = $3::uuid
  AND status = 'PROCESSING'
  AND locked_by = $4::varchar
  AND row_version = $5::bigint
`

type RenewOutboxEventLeaseParams struct {
	LeaseUntil    pgtype.Timestamptz
	Now           pgtype.Timestamptz
	OutboxEventID pgtype.UUID
	LockedBy      string
	RowVersion    int64
}

func (q *Queries) RenewOutboxEventLease(ctx context.Context, arg *RenewOutboxEventLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewOutboxEventLease,
		arg.LeaseUntil,
		arg.Now,
		arg.OutboxEventID,
		arg.LockedBy,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
