// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeFileIdempotencyRecord = `-- name: CompleteFileIdempotencyRecord :exec
UPDATE idempotency_records
SET status = 'COMPLETED',
    response_status_code = 201,
    response_schema_version = 1,
    response_json = jsonb_build_object('resourceId', $4::uuid, 'resourceType', $5::text),
    result_resource_id = $4,
    result_resource_type = $5,
    completed_at = $6,
    updated_at = $6,
    row_version = row_version + 1
WHERE principal_kind = 'USER'
  AND user_id = $1
  AND operation = $2
  AND idempotency_key = $3
  AND status = 'IN_PROGRESS'
`

type CompleteFileIdempotencyRecordParams struct {
	UserID             pgtype.UUID
	Operation          string
	IdempotencyKey     string
	ResultResourceID   pgtype.UUID
	ResultResourceType pgtype.Text
	CompletedAt        pgtype.Timestamptz
}

func (q *Queries) CompleteFileIdempotencyRecord(ctx context.Context, arg *CompleteFileIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, completeFileIdempotencyRecord,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.ResultResourceID,
		arg.ResultResourceType,
		arg.CompletedAt,
	)
	return err
}

const countFileChildEntries = `-- name: CountFileChildEntries :one
SELECT count(*)::bigint
FROM namespace_entries e
WHERE e.space_id = $1::uuid
  AND e.parent_folder_id = $2::uuid
  AND ($3::text IS NULL OR e.entry_type = $3)
  AND ($4::text IS NULL OR e.lifecycle_status = $4)
`

type CountFileChildEntriesParams struct {
	SpaceID         pgtype.UUID
	ParentFolderID  pgtype.UUID
	EntryType       pgtype.Text
	LifecycleStatus pgtype.Text
}

func (q *Queries) CountFileChildEntries(ctx context.Context, arg *CountFileChildEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFileChildEntries,
		arg.SpaceID,
		arg.ParentFolderID,
		arg.EntryType,
		arg.LifecycleStatus,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const fileFolderIsDescendantOf = `-- name: FileFolderIsDescendantOf :one
WITH RECURSIVE parents AS (
  SELECT e.parent_folder_id
  FROM namespace_entries e
  WHERE e.namespace_entry_id = $2::uuid
  UNION ALL
  SELECT e.parent_folder_id
  FROM namespace_entries e
  JOIN parents p ON e.namespace_entry_id = p.parent_folder_id
  WHERE p.parent_folder_id IS NOT NULL
)
SELECT EXISTS (
  SELECT 1 FROM parents WHERE parent_folder_id = $1::uuid
)::boolean
`

type FileFolderIsDescendantOfParams struct {
	AncestorFolderID pgtype.UUID
	FolderID         pgtype.UUID
}

func (q *Queries) FileFolderIsDescendantOf(ctx context.Context, arg *FileFolderIsDescendantOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, fileFolderIsDescendantOf, arg.AncestorFolderID, arg.FolderID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getFileIdempotencyRecord = `-- name: GetFileIdempotencyRecord :one
SELECT request_hash, status, result_resource_id
FROM idempotency_records
WHERE principal_kind = 'USER'
  AND user_id = $1
  AND operation = $2
  AND idempotency_key = $3
`

type GetFileIdempotencyRecordParams struct {
	UserID         pgtype.UUID
	Operation      string
	IdempotencyKey string
}

type GetFileIdempotencyRecordRow struct {
	RequestHash      []byte
	Status           string
	ResultResourceID pgtype.UUID
}

func (q *Queries) GetFileIdempotencyRecord(ctx context.Context, arg *GetFileIdempotencyRecordParams) (*GetFileIdempotencyRecordRow, error) {
	row := q.db.QueryRow(ctx, getFileIdempotencyRecord, arg.UserID, arg.Operation, arg.IdempotencyKey)
	var i GetFileIdempotencyRecordRow
	err := row.Scan(&i.RequestHash, &i.Status, &i.ResultResourceID)
	return &i, err
}

const getFileNamespaceEntry = `-- name: GetFileNamespaceEntry :one
SELECT
  e.namespace_entry_id, e.space_id, e.parent_folder_id, e.entry_type, e.name, e.normalized_name, e.path_cache, e.depth, e.lifecycle_status, e.created_by_user_id, e.created_at, e.updated_at, e.deleted_at, e.row_version,
  (s.root_folder_id = e.namespace_entry_id) AS is_root,
  f.inheritance_mode AS folder_inheritance_mode,
  f.acl_version AS folder_acl_version,
  d.owner_user_id,
  d.current_version_id,
  d.availability_status,
  d.extension_normalized,
  d.inheritance_mode AS document_inheritance_mode,
  d.acl_version AS document_acl_version,
  d.classification,
  d.metadata_schema_version,
  d.metadata_json
FROM namespace_entries e
JOIN spaces s ON s.space_id = e.space_id
LEFT JOIN folders f ON f.folder_id = e.namespace_entry_id
LEFT JOIN documents d ON d.document_id = e.namespace_entry_id
WHERE e.namespace_entry_id = $1 AND e.lifecycle_status <> 'PURGED' AND s.status <> 'DELETED'
`

type GetFileNamespaceEntryRow struct {
	NamespaceEntryID        pgtype.UUID
	SpaceID                 pgtype.UUID
	ParentFolderID          pgtype.UUID
	EntryType               string
	Name                    string
	NormalizedName          string
	PathCache               pgtype.Text
	Depth                   int32
	LifecycleStatus         string
	CreatedByUserID         pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	RowVersion              int64
	IsRoot                  bool
	FolderInheritanceMode   pgtype.Text
	FolderAclVersion        pgtype.Int8
	OwnerUserID             pgtype.UUID
	CurrentVersionID        pgtype.UUID
	AvailabilityStatus      pgtype.Text
	ExtensionNormalized     pgtype.Text
	DocumentInheritanceMode pgtype.Text
	DocumentAclVersion      pgtype.Int8
	Classification          pgtype.Text
	MetadataSchemaVersion   pgtype.Int4
	MetadataJson            []byte
}

func (q *Queries) GetFileNamespaceEntry(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetFileNamespaceEntryRow, error) {
	row := q.db.QueryRow(ctx, getFileNamespaceEntry, namespaceEntryID)
	var i GetFileNamespaceEntryRow
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
		&i.IsRoot,
		&i.FolderInheritanceMode,
		&i.FolderAclVersion,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.AvailabilityStatus,
		&i.ExtensionNormalized,
		&i.DocumentInheritanceMode,
		&i.DocumentAclVersion,
		&i.Classification,
		&i.MetadataSchemaVersion,
		&i.MetadataJson,
	)
	return &i, err
}

const getFileNamespaceEntryForUpdate = `-- name: GetFileNamespaceEntryForUpdate :one
SELECT
  e.namespace_entry_id, e.space_id, e.parent_folder_id, e.entry_type, e.name, e.normalized_name, e.path_cache, e.depth, e.lifecycle_status, e.created_by_user_id, e.created_at, e.updated_at, e.deleted_at, e.row_version,
  (s.root_folder_id = e.namespace_entry_id) AS is_root,
  f.inheritance_mode AS folder_inheritance_mode,
  f.acl_version AS folder_acl_version,
  d.owner_user_id,
  d.current_version_id,
  d.availability_status,
  d.extension_normalized,
  d.inheritance_mode AS document_inheritance_mode,
  d.acl_version AS document_acl_version,
  d.classification,
  d.metadata_schema_version,
  d.metadata_json
FROM namespace_entries e
JOIN spaces s ON s.space_id = e.space_id
LEFT JOIN folders f ON f.folder_id = e.namespace_entry_id
LEFT JOIN documents d ON d.document_id = e.namespace_entry_id
WHERE e.namespace_entry_id = $1 AND e.lifecycle_status <> 'PURGED' AND s.status <> 'DELETED'
FOR UPDATE OF e
`

type GetFileNamespaceEntryForUpdateRow struct {
	NamespaceEntryID        pgtype.UUID
	SpaceID                 pgtype.UUID
	ParentFolderID          pgtype.UUID
	EntryType               string
	Name                    string
	NormalizedName          string
	PathCache               pgtype.Text
	Depth                   int32
	LifecycleStatus         string
	CreatedByUserID         pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	RowVersion              int64
	IsRoot                  bool
	FolderInheritanceMode   pgtype.Text
	FolderAclVersion        pgtype.Int8
	OwnerUserID             pgtype.UUID
	CurrentVersionID        pgtype.UUID
	AvailabilityStatus      pgtype.Text
	ExtensionNormalized     pgtype.Text
	DocumentInheritanceMode pgtype.Text
	DocumentAclVersion      pgtype.Int8
	Classification          pgtype.Text
	MetadataSchemaVersion   pgtype.Int4
	MetadataJson            []byte
}

func (q *Queries) GetFileNamespaceEntryForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetFileNamespaceEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFileNamespaceEntryForUpdate, namespaceEntryID)
	var i GetFileNamespaceEntryForUpdateRow
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
		&i.IsRoot,
		&i.FolderInheritanceMode,
		&i.FolderAclVersion,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.AvailabilityStatus,
		&i.ExtensionNormalized,
		&i.DocumentInheritanceMode,
		&i.DocumentAclVersion,
		&i.Classification,
		&i.MetadataSchemaVersion,
		&i.MetadataJson,
	)
	return &i, err
}

const getFileSpaceDirectoryInfo = `-- name: GetFileSpaceDirectoryInfo :one
SELECT space_id, space_type, owner_user_id, organization_id, root_folder_id, status, row_version
FROM spaces
WHERE space_id = $1 AND status <> 'DELETED'
`

type GetFileSpaceDirectoryInfoRow struct {
	SpaceID        pgtype.UUID
	SpaceType      string
	OwnerUserID    pgtype.UUID
	OrganizationID pgtype.UUID
	RootFolderID   pgtype.UUID
	Status         string
	RowVersion     int64
}

func (q *Queries) GetFileSpaceDirectoryInfo(ctx context.Context, spaceID pgtype.UUID) (*GetFileSpaceDirectoryInfoRow, error) {
	row := q.db.QueryRow(ctx, getFileSpaceDirectoryInfo, spaceID)
	var i GetFileSpaceDirectoryInfoRow
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.Status,
		&i.RowVersion,
	)
	return &i, err
}

const getFileSpaceDirectoryInfoForUpdate = `-- name: GetFileSpaceDirectoryInfoForUpdate :one
SELECT space_id, space_type, owner_user_id, organization_id, root_folder_id, status, row_version
FROM spaces
WHERE space_id = $1 AND status <> 'DELETED'
FOR UPDATE
`

type GetFileSpaceDirectoryInfoForUpdateRow struct {
	SpaceID        pgtype.UUID
	SpaceType      string
	OwnerUserID    pgtype.UUID
	OrganizationID pgtype.UUID
	RootFolderID   pgtype.UUID
	Status         string
	RowVersion     int64
}

func (q *Queries) GetFileSpaceDirectoryInfoForUpdate(ctx context.Context, spaceID pgtype.UUID) (*GetFileSpaceDirectoryInfoForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFileSpaceDirectoryInfoForUpdate, spaceID)
	var i GetFileSpaceDirectoryInfoForUpdateRow
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.Status,
		&i.RowVersion,
	)
	return &i, err
}

const insertFileDocument = `-- name: InsertFileDocument :one
INSERT INTO documents (
  document_id, owner_user_id, current_version_id, availability_status,
  extension_normalized, inheritance_mode, classification,
  metadata_schema_version, metadata_json, created_at, updated_at
) VALUES (
  $1, $2, NULL, $3,
  $4, 'INHERIT', $5,
  1, $6, $7, $7
)
RETURNING document_id, owner_user_id, current_version_id, availability_status, extension_normalized, inheritance_mode, acl_version, classification, metadata_schema_version, metadata_json, created_at, updated_at, row_version
`

type InsertFileDocumentParams struct {
	DocumentID          pgtype.UUID
	OwnerUserID         pgtype.UUID
	AvailabilityStatus  string
	ExtensionNormalized pgtype.Text
	Classification      pgtype.Text
	MetadataJson        []byte
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) InsertFileDocument(ctx context.Context, arg *InsertFileDocumentParams) (*Document, error) {
	row := q.db.QueryRow(ctx, insertFileDocument,
		arg.DocumentID,
		arg.OwnerUserID,
		arg.AvailabilityStatus,
		arg.ExtensionNormalized,
		arg.Classification,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.AvailabilityStatus,
		&i.ExtensionNormalized,
		&i.InheritanceMode,
		&i.AclVersion,
		&i.Classification,
		&i.MetadataSchemaVersion,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertFileFolder = `-- name: InsertFileFolder :exec
INSERT INTO folders (folder_id, inheritance_mode, created_at, updated_at)
VALUES ($1, 'INHERIT', $2, $2)
`

type InsertFileFolderParams struct {
	FolderID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertFileFolder(ctx context.Context, arg *InsertFileFolderParams) error {
	_, err := q.db.Exec(ctx, insertFileFolder, arg.FolderID, arg.CreatedAt)
	return err
}

const insertFileNamespaceEntry = `-- name: InsertFileNamespaceEntry :one
INSERT INTO namespace_entries (
  namespace_entry_id, space_id, parent_folder_id, entry_type,
  name, normalized_name, path_cache, depth, lifecycle_status,
  created_by_user_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8, 'ACTIVE',
  $9, $10, $10
)
RETURNING namespace_entry_id, space_id, parent_folder_id, entry_type, name, normalized_name, path_cache, depth, lifecycle_status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type InsertFileNamespaceEntryParams struct {
	NamespaceEntryID pgtype.UUID
	SpaceID          pgtype.UUID
	ParentFolderID   pgtype.UUID
	EntryType        string
	Name             string
	NormalizedName   string
	PathCache        pgtype.Text
	Depth            int32
	CreatedByUserID  pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertFileNamespaceEntry(ctx context.Context, arg *InsertFileNamespaceEntryParams) (*NamespaceEntry, error) {
	row := q.db.QueryRow(ctx, insertFileNamespaceEntry,
		arg.NamespaceEntryID,
		arg.SpaceID,
		arg.ParentFolderID,
		arg.EntryType,
		arg.Name,
		arg.NormalizedName,
		arg.PathCache,
		arg.Depth,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i NamespaceEntry
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertFileOutboxEvent = `-- name: InsertFileOutboxEvent :exec
INSERT INTO outbox_events (
  outbox_event_id, aggregate_type, aggregate_id, aggregate_version,
  event_type, event_schema_version, payload_json, deduplication_key, correlation_id,
  max_attempts, available_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4,
  $5, 1, $6, $7, $8,
  10, $9, $9, $9
)
ON CONFLICT (deduplication_key) DO NOTHING
`

type InsertFileOutboxEventParams struct {
	OutboxEventID    pgtype.UUID
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
	PayloadJson      []byte
	DeduplicationKey string
	CorrelationID    pgtype.UUID
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertFileOutboxEvent(ctx context.Context, arg *InsertFileOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertFileOutboxEvent,
		arg.OutboxEventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.PayloadJson,
		arg.DeduplicationKey,
		arg.CorrelationID,
		arg.AvailableAt,
	)
	return err
}

const listFileChildEntries = `-- name: ListFileChildEntries :many
SELECT
  e.namespace_entry_id, e.space_id, e.parent_folder_id, e.entry_type, e.name, e.normalized_name, e.path_cache, e.depth, e.lifecycle_status, e.created_by_user_id, e.created_at, e.updated_at, e.deleted_at, e.row_version,
  false::boolean AS is_root,
  f.inheritance_mode AS folder_inheritance_mode,
  f.acl_version AS folder_acl_version,
  d.owner_user_id,
  d.current_version_id,
  d.availability_status,
  d.extension_normalized,
  d.inheritance_mode AS document_inheritance_mode,
  d.acl_version AS document_acl_version,
  d.classification,
  d.metadata_schema_version,
  d.metadata_json
FROM namespace_entries e
LEFT JOIN folders f ON f.folder_id = e.namespace_entry_id
LEFT JOIN documents d ON d.document_id = e.namespace_entry_id
WHERE e.space_id = $1::uuid
  AND e.parent_folder_id = $2::uuid
  AND ($3::text IS NULL OR e.entry_type = $3)
  AND ($4::text IS NULL OR e.lifecycle_status = $4)
ORDER BY e.entry_type, e.normalized_name, e.namespace_entry_id
LIMIT $6::integer OFFSET $5::bigint
`

type ListFileChildEntriesParams struct {
	SpaceID         pgtype.UUID
	ParentFolderID  pgtype.UUID
	EntryType       pgtype.Text
	LifecycleStatus pgtype.Text
	PageOffset      int64
	PageSize        int32
}

type ListFileChildEntriesRow struct {
	NamespaceEntryID        pgtype.UUID
	SpaceID                 pgtype.UUID
	ParentFolderID          pgtype.UUID
	EntryType               string
	Name                    string
	NormalizedName          string
	PathCache               pgtype.Text
	Depth                   int32
	LifecycleStatus         string
	CreatedByUserID         pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	RowVersion              int64
	IsRoot                  bool
	FolderInheritanceMode   pgtype.Text
	FolderAclVersion        pgtype.Int8
	OwnerUserID             pgtype.UUID
	CurrentVersionID        pgtype.UUID
	AvailabilityStatus      pgtype.Text
	ExtensionNormalized     pgtype.Text
	DocumentInheritanceMode pgtype.Text
	DocumentAclVersion      pgtype.Int8
	Classification          pgtype.Text
	MetadataSchemaVersion   pgtype.Int4
	MetadataJson            []byte
}

func (q *Queries) ListFileChildEntries(ctx context.Context, arg *ListFileChildEntriesParams) ([]*ListFileChildEntriesRow, error) {
	rows, err := q.db.Query(ctx, listFileChildEntries,
		arg.SpaceID,
		arg.ParentFolderID,
		arg.EntryType,
		arg.LifecycleStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFileChildEntriesRow{}
	for rows.Next() {
		var i ListFileChildEntriesRow
		if err := rows.Scan(
			&i.NamespaceEntryID,
			&i.SpaceID,
			&i.ParentFolderID,
			&i.EntryType,
			&i.Name,
			&i.NormalizedName,
			&i.PathCache,
			&i.Depth,
			&i.LifecycleStatus,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RowVersion,
			&i.IsRoot,
			&i.FolderInheritanceMode,
			&i.FolderAclVersion,
			&i.OwnerUserID,
			&i.CurrentVersionID,
			&i.AvailabilityStatus,
			&i.ExtensionNormalized,
			&i.DocumentInheritanceMode,
			&i.DocumentAclVersion,
			&i.Classification,
			&i.MetadataSchemaVersion,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFileNamespaceEntry = `-- name: MoveFileNamespaceEntry :one
UPDATE namespace_entries
SET parent_folder_id = $2,
    path_cache = $3,
    depth = $4,
    updated_at = $5,
    row_version = row_version + 1
WHERE namespace_entry_id = $1
  AND row_version = $6
  AND parent_folder_id IS NOT NULL
  AND lifecycle_status IN ('ACTIVE', 'ARCHIVED')
RETURNING namespace_entry_id, space_id, parent_folder_id, entry_type, name, normalized_name, path_cache, depth, lifecycle_status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type MoveFileNamespaceEntryParams struct {
	NamespaceEntryID pgtype.UUID
	ParentFolderID   pgtype.UUID
	PathCache        pgtype.Text
	Depth            int32
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int64
}

func (q *Queries) MoveFileNamespaceEntry(ctx context.Context, arg *MoveFileNamespaceEntryParams) (*NamespaceEntry, error) {
	row := q.db.QueryRow(ctx, moveFileNamespaceEntry,
		arg.NamespaceEntryID,
		arg.ParentFolderID,
		arg.PathCache,
		arg.Depth,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i NamespaceEntry
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const renameFileNamespaceEntry = `-- name: RenameFileNamespaceEntry :one
UPDATE namespace_entries
SET name = $1::varchar,
    normalized_name = $2::varchar,
    path_cache = CASE
      WHEN parent_folder_id IS NULL THEN path_cache
      ELSE regexp_replace(COALESCE(path_cache, ''), '[^/]+$', $1::varchar::text)
    END,
    updated_at = $3::timestamptz,
    row_version = row_version + 1
WHERE namespace_entry_id = $4::uuid
  AND row_version = $5::bigint
  AND lifecycle_status IN ('ACTIVE', 'ARCHIVED')
RETURNING namespace_entry_id, space_id, parent_folder_id, entry_type, name, normalized_name, path_cache, depth, lifecycle_status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type RenameFileNamespaceEntryParams struct {
	Name             string
	NormalizedName   string
	UpdatedAt        pgtype.Timestamptz
	NamespaceEntryID pgtype.UUID
	RowVersion       int64
}

func (q *Queries) RenameFileNamespaceEntry(ctx context.Context, arg *RenameFileNamespaceEntryParams) (*NamespaceEntry, error) {
	row := q.db.QueryRow(ctx, renameFileNamespaceEntry,
		arg.Name,
		arg.NormalizedName,
		arg.UpdatedAt,
		arg.NamespaceEntryID,
		arg.RowVersion,
	)
	var i NamespaceEntry
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const touchFileSpaceSecurityEpoch = `-- name: TouchFileSpaceSecurityEpoch :exec
UPDATE spaces
SET security_epoch = security_epoch + 1,
    updated_at = $2,
    row_version = row_version + 1
WHERE space_id = $1 AND status <> 'DELETED'
`

type TouchFileSpaceSecurityEpochParams struct {
	SpaceID   pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) TouchFileSpaceSecurityEpoch(ctx context.Context, arg *TouchFileSpaceSecurityEpochParams) error {
	_, err := q.db.Exec(ctx, touchFileSpaceSecurityEpoch, arg.SpaceID, arg.UpdatedAt)
	return err
}

const tryCreateFileIdempotencyRecord = `-- name: TryCreateFileIdempotencyRecord :execrows
INSERT INTO idempotency_records (
  idempotency_record_id, principal_kind, user_id, operation, idempotency_key, request_hash,
  status, expires_at, created_at, updated_at
) VALUES (
  $1, 'USER', $2, $3, $4, $5, 'IN_PROGRESS', $6, $7, $7
)
ON CONFLICT DO NOTHING
`

type TryCreateFileIdempotencyRecordParams struct {
	IdempotencyRecordID pgtype.UUID
	UserID              pgtype.UUID
	Operation           string
	IdempotencyKey      string
	RequestHash         []byte
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) TryCreateFileIdempotencyRecord(ctx context.Context, arg *TryCreateFileIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryCreateFileIdempotencyRecord,
		arg.IdempotencyRecordID,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFileDescendantPaths = `-- name: UpdateFileDescendantPaths :exec
WITH RECURSIVE tree AS (
  SELECT child.namespace_entry_id,
         $2::text || '/' || child.name AS new_path,
         $3::integer + 1 AS new_depth
  FROM namespace_entries child
  WHERE child.parent_folder_id = $4::uuid
  UNION ALL
  SELECT child.namespace_entry_id,
         tree.new_path || '/' || child.name AS new_path,
         tree.new_depth + 1 AS new_depth
  FROM namespace_entries child
  JOIN tree ON child.parent_folder_id = tree.namespace_entry_id
)
UPDATE namespace_entries e
SET path_cache = tree.new_path,
    depth = tree.new_depth,
    updated_at = $1::timestamptz,
    row_version = e.row_version + 1
FROM tree
WHERE e.namespace_entry_id = tree.namespace_entry_id
`

type UpdateFileDescendantPathsParams struct {
	UpdatedAt pgtype.Timestamptz
	RootPath  string
	RootDepth int32
	RootID    pgtype.UUID
}

func (q *Queries) UpdateFileDescendantPaths(ctx context.Context, arg *UpdateFileDescendantPathsParams) error {
	_, err := q.db.Exec(ctx, updateFileDescendantPaths,
		arg.UpdatedAt,
		arg.RootPath,
		arg.RootDepth,
		arg.RootID,
	)
	return err
}

const updateFileDocumentExtension = `-- name: UpdateFileDocumentExtension :exec
UPDATE documents
SET extension_normalized = $2,
    updated_at = $3,
    row_version = row_version + 1
WHERE document_id = $1
`

type UpdateFileDocumentExtensionParams struct {
	DocumentID          pgtype.UUID
	ExtensionNormalized pgtype.Text
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateFileDocumentExtension(ctx context.Context, arg *UpdateFileDocumentExtensionParams) error {
	_, err := q.db.Exec(ctx, updateFileDocumentExtension, arg.DocumentID, arg.ExtensionNormalized, arg.UpdatedAt)
	return err
}

const updateFileSpaceRootFolder = `-- name: UpdateFileSpaceRootFolder :exec
UPDATE spaces
SET root_folder_id = $2,
    updated_at = $3,
    row_version = row_version + 1
WHERE space_id = $1 AND root_folder_id IS NULL AND status <> 'DELETED'
`

type UpdateFileSpaceRootFolderParams struct {
	SpaceID      pgtype.UUID
	RootFolderID pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateFileSpaceRootFolder(ctx context.Context, arg *UpdateFileSpaceRootFolderParams) error {
	_, err := q.db.Exec(ctx, updateFileSpaceRootFolder, arg.SpaceID, arg.RootFolderID, arg.UpdatedAt)
	return err
}
