// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
)

const getDatabaseHealth = `-- name: GetDatabaseHealth :one
SELECT current_database()::text AS database_name,
       current_user::text AS database_user,
       current_schema()::text AS current_schema,
       current_setting('server_version')::text AS server_version,
       current_setting('TimeZone')::text AS timezone
`

type GetDatabaseHealthRow struct {
	DatabaseName  string
	DatabaseUser  string
	CurrentSchema string
	ServerVersion string
	Timezone      string
}

func (q *Queries) GetDatabaseHealth(ctx context.Context) (*GetDatabaseHealthRow, error) {
	row := q.db.QueryRow(ctx, getDatabaseHealth)
	var i GetDatabaseHealthRow
	err := row.Scan(
		&i.DatabaseName,
		&i.DatabaseUser,
		&i.CurrentSchema,
		&i.ServerVersion,
		&i.Timezone,
	)
	return &i, err
}
