// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionRefreshToken = `-- name: CreateSessionRefreshToken :one
INSERT INTO session_refresh_tokens (
    refresh_token_id,
    user_session_id,
    token_family_id,
    parent_refresh_token_id,
    rotation_number,
    token_hash,
    status,
    issued_at,
    expires_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 'ACTIVE', $7, $8, $7
)
RETURNING refresh_token_id, user_session_id, token_family_id, parent_refresh_token_id,
          rotation_number, status, issued_at, expires_at
`

type CreateSessionRefreshTokenParams struct {
	RefreshTokenID       pgtype.UUID
	UserSessionID        pgtype.UUID
	TokenFamilyID        pgtype.UUID
	ParentRefreshTokenID pgtype.UUID
	RotationNumber       int32
	TokenHash            []byte
	IssuedAt             pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}

type CreateSessionRefreshTokenRow struct {
	RefreshTokenID       pgtype.UUID
	UserSessionID        pgtype.UUID
	TokenFamilyID        pgtype.UUID
	ParentRefreshTokenID pgtype.UUID
	RotationNumber       int32
	Status               string
	IssuedAt             pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}

func (q *Queries) CreateSessionRefreshToken(ctx context.Context, arg *CreateSessionRefreshTokenParams) (*CreateSessionRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createSessionRefreshToken,
		arg.RefreshTokenID,
		arg.UserSessionID,
		arg.TokenFamilyID,
		arg.ParentRefreshTokenID,
		arg.RotationNumber,
		arg.TokenHash,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i CreateSessionRefreshTokenRow
	err := row.Scan(
		&i.RefreshTokenID,
		&i.UserSessionID,
		&i.TokenFamilyID,
		&i.ParentRefreshTokenID,
		&i.RotationNumber,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
    user_session_id,
    user_id,
    device_id,
    ip_address,
    user_agent,
    status,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, 'ACTIVE', $6, $7, $7
)
RETURNING user_session_id, user_id, device_id, status, expires_at, last_seen_at, created_at
`

type CreateUserSessionParams struct {
	UserSessionID pgtype.UUID
	UserID        pgtype.UUID
	DeviceID      pgtype.Text
	IpAddress     *netip.Addr
	UserAgent     pgtype.Text
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type CreateUserSessionRow struct {
	UserSessionID pgtype.UUID
	UserID        pgtype.UUID
	DeviceID      pgtype.Text
	Status        string
	ExpiresAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateUserSession(ctx context.Context, arg *CreateUserSessionParams) (*CreateUserSessionRow, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserSessionID,
		arg.UserID,
		arg.DeviceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i CreateUserSessionRow
	err := row.Scan(
		&i.UserSessionID,
		&i.UserID,
		&i.DeviceID,
		&i.Status,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getCurrentSessionIdentity = `-- name: GetCurrentSessionIdentity :one
SELECT
    s.user_session_id,
    s.device_id,
    s.status AS session_status,
    s.expires_at AS session_expires_at,
    s.last_seen_at,
    s.created_at AS session_created_at,
    u.user_id,
    u.username,
    u.display_name,
    u.system_role,
    u.status AS user_status,
    u.locale,
    u.timezone
FROM user_sessions AS s
JOIN users AS u ON u.user_id = s.user_id
WHERE s.user_session_id = $1
`

type GetCurrentSessionIdentityRow struct {
	UserSessionID    pgtype.UUID
	DeviceID         pgtype.Text
	SessionStatus    string
	SessionExpiresAt pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	SessionCreatedAt pgtype.Timestamptz
	UserID           pgtype.UUID
	Username         string
	DisplayName      string
	SystemRole       string
	UserStatus       string
	Locale           string
	Timezone         string
}

func (q *Queries) GetCurrentSessionIdentity(ctx context.Context, userSessionID pgtype.UUID) (*GetCurrentSessionIdentityRow, error) {
	row := q.db.QueryRow(ctx, getCurrentSessionIdentity, userSessionID)
	var i GetCurrentSessionIdentityRow
	err := row.Scan(
		&i.UserSessionID,
		&i.DeviceID,
		&i.SessionStatus,
		&i.SessionExpiresAt,
		&i.LastSeenAt,
		&i.SessionCreatedAt,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.SystemRole,
		&i.UserStatus,
		&i.Locale,
		&i.Timezone,
	)
	return &i, err
}

const getPasswordLoginIdentity = `-- name: GetPasswordLoginIdentity :one
SELECT
    u.user_id,
    u.username,
    u.display_name,
    u.system_role,
    u.status AS user_status,
    u.locale,
    u.timezone,
    uc.user_credential_id,
    uc.secret_hash
FROM users AS u
JOIN user_credentials AS uc ON uc.user_id = u.user_id
WHERE u.username_normalized = $1
  AND uc.credential_type = 'PASSWORD'
  AND uc.status = 'ACTIVE'
  AND (uc.expires_at IS NULL OR uc.expires_at > $2)
LIMIT 1
`

type GetPasswordLoginIdentityParams struct {
	UsernameNormalized string
	ExpiresAt          pgtype.Timestamptz
}

type GetPasswordLoginIdentityRow struct {
	UserID           pgtype.UUID
	Username         string
	DisplayName      string
	SystemRole       string
	UserStatus       string
	Locale           string
	Timezone         string
	UserCredentialID pgtype.UUID
	SecretHash       pgtype.Text
}

func (q *Queries) GetPasswordLoginIdentity(ctx context.Context, arg *GetPasswordLoginIdentityParams) (*GetPasswordLoginIdentityRow, error) {
	row := q.db.QueryRow(ctx, getPasswordLoginIdentity, arg.UsernameNormalized, arg.ExpiresAt)
	var i GetPasswordLoginIdentityRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.SystemRole,
		&i.UserStatus,
		&i.Locale,
		&i.Timezone,
		&i.UserCredentialID,
		&i.SecretHash,
	)
	return &i, err
}

const getRecentLoginFailureState = `-- name: GetRecentLoginFailureState :one
SELECT
    count(*)::bigint AS failure_count,
    max(created_at)::timestamptz AS last_failure_at
FROM login_attempts AS attempt
WHERE attempt.username_normalized = $1
  AND attempt.result = 'FAILURE'
  AND attempt.created_at >= $2
  AND attempt.created_at > COALESCE((
      SELECT max(success.created_at)
      FROM login_attempts AS success
      WHERE success.username_normalized = $1
        AND success.result = 'SUCCESS'
        AND success.created_at >= $2
  ), $2)
`

type GetRecentLoginFailureStateParams struct {
	UsernameNormalized string
	CreatedAt          pgtype.Timestamptz
}

type GetRecentLoginFailureStateRow struct {
	FailureCount  int64
	LastFailureAt pgtype.Timestamptz
}

func (q *Queries) GetRecentLoginFailureState(ctx context.Context, arg *GetRecentLoginFailureStateParams) (*GetRecentLoginFailureStateRow, error) {
	row := q.db.QueryRow(ctx, getRecentLoginFailureState, arg.UsernameNormalized, arg.CreatedAt)
	var i GetRecentLoginFailureStateRow
	err := row.Scan(&i.FailureCount, &i.LastFailureAt)
	return &i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT
    rt.refresh_token_id,
    rt.user_session_id,
    rt.token_family_id,
    rt.rotation_number,
    rt.status AS refresh_token_status,
    rt.expires_at AS refresh_token_expires_at,
    s.device_id,
    s.status AS session_status,
    s.expires_at AS session_expires_at,
    s.last_seen_at,
    s.created_at AS session_created_at,
    u.user_id,
    u.username,
    u.display_name,
    u.system_role,
    u.status AS user_status,
    u.locale,
    u.timezone
FROM session_refresh_tokens AS rt
JOIN user_sessions AS s ON s.user_session_id = rt.user_session_id
JOIN users AS u ON u.user_id = s.user_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt, s
`

type GetRefreshTokenForUpdateRow struct {
	RefreshTokenID        pgtype.UUID
	UserSessionID         pgtype.UUID
	TokenFamilyID         pgtype.UUID
	RotationNumber        int32
	RefreshTokenStatus    string
	RefreshTokenExpiresAt pgtype.Timestamptz
	DeviceID              pgtype.Text
	SessionStatus         string
	SessionExpiresAt      pgtype.Timestamptz
	LastSeenAt            pgtype.Timestamptz
	SessionCreatedAt      pgtype.Timestamptz
	UserID                pgtype.UUID
	Username              string
	DisplayName           string
	SystemRole            string
	UserStatus            string
	Locale                string
	Timezone              string
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (*GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.RefreshTokenID,
		&i.UserSessionID,
		&i.TokenFamilyID,
		&i.RotationNumber,
		&i.RefreshTokenStatus,
		&i.RefreshTokenExpiresAt,
		&i.DeviceID,
		&i.SessionStatus,
		&i.SessionExpiresAt,
		&i.LastSeenAt,
		&i.SessionCreatedAt,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.SystemRole,
		&i.UserStatus,
		&i.Locale,
		&i.Timezone,
	)
	return &i, err
}

const getSessionIDByRefreshTokenHash = `-- name: GetSessionIDByRefreshTokenHash :one
SELECT user_session_id
FROM session_refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetSessionIDByRefreshTokenHash(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionIDByRefreshTokenHash, tokenHash)
	var user_session_id pgtype.UUID
	err := row.Scan(&user_session_id)
	return user_session_id, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO login_attempts (
    login_attempt_id,
    username_normalized,
    user_id,
    result,
    failure_code,
    ip_address,
    user_agent,
    request_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertLoginAttemptParams struct {
	LoginAttemptID     pgtype.UUID
	UsernameNormalized string
	UserID             pgtype.UUID
	Result             string
	FailureCode        pgtype.Text
	IpAddress          *netip.Addr
	UserAgent          pgtype.Text
	RequestID          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg *InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt,
		arg.LoginAttemptID,
		arg.UsernameNormalized,
		arg.UserID,
		arg.Result,
		arg.FailureCode,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.CreatedAt,
	)
	return err
}

const markRefreshTokenReused = `-- name: MarkRefreshTokenReused :exec
UPDATE session_refresh_tokens
SET status = 'REUSED',
    revoked_at = $2,
    updated_at = $2,
    row_version = row_version + 1
WHERE refresh_token_id = $1
  AND status = 'USED'
`

type MarkRefreshTokenReusedParams struct {
	RefreshTokenID pgtype.UUID
	RevokedAt      pgtype.Timestamptz
}

func (q *Queries) MarkRefreshTokenReused(ctx context.Context, arg *MarkRefreshTokenReusedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenReused, arg.RefreshTokenID, arg.RevokedAt)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE session_refresh_tokens
SET status = 'USED',
    used_at = $2,
    updated_at = $2,
    row_version = row_version + 1
WHERE refresh_token_id = $1
  AND status = 'ACTIVE'
`

type MarkRefreshTokenUsedParams struct {
	RefreshTokenID pgtype.UUID
	UsedAt         pgtype.Timestamptz
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg *MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.RefreshTokenID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeActiveRefreshTokensForSession = `-- name: RevokeActiveRefreshTokensForSession :exec
UPDATE session_refresh_tokens
SET status = 'REVOKED',
    revoked_at = $2,
    updated_at = $2,
    row_version = row_version + 1
WHERE user_session_id = $1
  AND status = 'ACTIVE'
`

type RevokeActiveRefreshTokensForSessionParams struct {
	UserSessionID pgtype.UUID
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) RevokeActiveRefreshTokensForSession(ctx context.Context, arg *RevokeActiveRefreshTokensForSessionParams) error {
	_, err := q.db.Exec(ctx, revokeActiveRefreshTokensForSession, arg.UserSessionID, arg.RevokedAt)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE user_sessions
SET status = 'REVOKED',
    revoked_at = COALESCE(revoked_at, $2),
    revoke_reason = COALESCE(revoke_reason, $3),
    updated_at = $2,
    row_version = row_version + 1
WHERE user_session_id = $1
  AND status = 'ACTIVE'
`

type RevokeUserSessionParams struct {
	UserSessionID pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	RevokeReason  pgtype.Text
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg *RevokeUserSessionParams) error {
	_, err := q.db.Exec(ctx, revokeUserSession, arg.UserSessionID, arg.UpdatedAt, arg.RevokeReason)
	return err
}

const touchCredentialAfterLogin = `-- name: TouchCredentialAfterLogin :exec
UPDATE user_credentials
SET last_used_at = $2,
    updated_at = $2,
    row_version = row_version + 1
WHERE user_credential_id = $1
`

type TouchCredentialAfterLoginParams struct {
	UserCredentialID pgtype.UUID
	LastUsedAt       pgtype.Timestamptz
}

func (q *Queries) TouchCredentialAfterLogin(ctx context.Context, arg *TouchCredentialAfterLoginParams) error {
	_, err := q.db.Exec(ctx, touchCredentialAfterLogin, arg.UserCredentialID, arg.LastUsedAt)
	return err
}

const touchUserAfterLogin = `-- name: TouchUserAfterLogin :exec
UPDATE users
SET last_login_at = $2,
    updated_at = $2,
    row_version = row_version + 1
WHERE user_id = $1
`

type TouchUserAfterLoginParams struct {
	UserID      pgtype.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) TouchUserAfterLogin(ctx context.Context, arg *TouchUserAfterLoginParams) error {
	_, err := q.db.Exec(ctx, touchUserAfterLogin, arg.UserID, arg.LastLoginAt)
	return err
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions
SET last_seen_at = $2::timestamptz,
    updated_at = $2::timestamptz,
    row_version = row_version + 1
WHERE user_session_id = $1
  AND status = 'ACTIVE'
  AND (last_seen_at IS NULL OR last_seen_at < $2::timestamptz - interval '5 minutes')
`

type TouchUserSessionParams struct {
	UserSessionID pgtype.UUID
	LastSeenAt    pgtype.Timestamptz
}

func (q *Queries) TouchUserSession(ctx context.Context, arg *TouchUserSessionParams) error {
	_, err := q.db.Exec(ctx, touchUserSession, arg.UserSessionID, arg.LastSeenAt)
	return err
}
