// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeLegalHoldExistsForEntrySubtree = `-- name: ActiveLegalHoldExistsForEntrySubtree :one
WITH RECURSIVE tree AS (
  SELECT e.namespace_entry_id, e.entry_type
  FROM namespace_entries e
  WHERE e.namespace_entry_id = $1
  UNION ALL
  SELECT child.namespace_entry_id, child.entry_type
  FROM namespace_entries child
  JOIN tree parent ON child.parent_folder_id = parent.namespace_entry_id
)
SELECT EXISTS (
  SELECT 1
  FROM legal_holds hold
  JOIN tree ON tree.namespace_entry_id = hold.document_id
  WHERE hold.status = 'ACTIVE'
)::boolean
`

func (q *Queries) ActiveLegalHoldExistsForEntrySubtree(ctx context.Context, namespaceEntryID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, activeLegalHoldExistsForEntrySubtree, namespaceEntryID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const completeLifecycleIdempotency = `-- name: CompleteLifecycleIdempotency :exec
UPDATE idempotency_records
SET status = 'COMPLETED', result_resource_id = $4, result_resource_type = $5, completed_at = $6, updated_at = $6
WHERE principal_kind = 'USER' AND user_id = $1 AND operation = $2 AND idempotency_key = $3 AND status = 'IN_PROGRESS'
`

type CompleteLifecycleIdempotencyParams struct {
	UserID             pgtype.UUID
	Operation          string
	IdempotencyKey     string
	ResultResourceID   pgtype.UUID
	ResultResourceType pgtype.Text
	CompletedAt        pgtype.Timestamptz
}

func (q *Queries) CompleteLifecycleIdempotency(ctx context.Context, arg *CompleteLifecycleIdempotencyParams) error {
	_, err := q.db.Exec(ctx, completeLifecycleIdempotency,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.ResultResourceID,
		arg.ResultResourceType,
		arg.CompletedAt,
	)
	return err
}

const countPreservationHolds = `-- name: CountPreservationHolds :one
SELECT count(*)::bigint
FROM legal_holds
WHERE ($1::uuid IS NULL OR document_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR case_reference ILIKE '%' || $3::text || '%')
`

type CountPreservationHoldsParams struct {
	DocumentID    pgtype.UUID
	Status        pgtype.Text
	CaseReference pgtype.Text
}

func (q *Queries) CountPreservationHolds(ctx context.Context, arg *CountPreservationHoldsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPreservationHolds, arg.DocumentID, arg.Status, arg.CaseReference)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecycleItems = `-- name: CountRecycleItems :one
SELECT count(*)::bigint
FROM recycle_items r
JOIN namespace_entries e ON e.namespace_entry_id = r.namespace_entry_id
WHERE r.status = 'ACTIVE'
  AND ($1::uuid IS NULL OR r.original_space_id = $1::uuid)
`

func (q *Queries) CountRecycleItems(ctx context.Context, spaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecycleItems, spaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLifecycleDocumentRef = `-- name: GetLifecycleDocumentRef :one
SELECT
  e.namespace_entry_id AS document_id,
  e.space_id,
  e.name,
  e.lifecycle_status,
  d.current_version_id
FROM documents d
JOIN namespace_entries e ON e.namespace_entry_id = d.document_id
WHERE d.document_id = $1
  AND e.entry_type = 'DOCUMENT'
  AND e.lifecycle_status <> 'PURGED'
`

type GetLifecycleDocumentRefRow struct {
	DocumentID       pgtype.UUID
	SpaceID          pgtype.UUID
	Name             string
	LifecycleStatus  string
	CurrentVersionID pgtype.UUID
}

func (q *Queries) GetLifecycleDocumentRef(ctx context.Context, documentID pgtype.UUID) (*GetLifecycleDocumentRefRow, error) {
	row := q.db.QueryRow(ctx, getLifecycleDocumentRef, documentID)
	var i GetLifecycleDocumentRefRow
	err := row.Scan(
		&i.DocumentID,
		&i.SpaceID,
		&i.Name,
		&i.LifecycleStatus,
		&i.CurrentVersionID,
	)
	return &i, err
}

const getLifecycleEntryForUpdate = `-- name: GetLifecycleEntryForUpdate :one
SELECT
  e.namespace_entry_id, e.space_id, e.parent_folder_id, e.entry_type, e.name,
  e.normalized_name, e.path_cache, e.depth, e.lifecycle_status, e.created_by_user_id,
  e.created_at, e.updated_at, e.deleted_at, e.row_version,
  (s.root_folder_id = e.namespace_entry_id) AS is_root
FROM namespace_entries e
JOIN spaces s ON s.space_id = e.space_id
WHERE e.namespace_entry_id = $1
  AND e.lifecycle_status <> 'PURGED'
  AND s.status <> 'DELETED'
FOR UPDATE OF e
`

type GetLifecycleEntryForUpdateRow struct {
	NamespaceEntryID pgtype.UUID
	SpaceID          pgtype.UUID
	ParentFolderID   pgtype.UUID
	EntryType        string
	Name             string
	NormalizedName   string
	PathCache        pgtype.Text
	Depth            int32
	LifecycleStatus  string
	CreatedByUserID  pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	RowVersion       int64
	IsRoot           bool
}

func (q *Queries) GetLifecycleEntryForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetLifecycleEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLifecycleEntryForUpdate, namespaceEntryID)
	var i GetLifecycleEntryForUpdateRow
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
		&i.IsRoot,
	)
	return &i, err
}

const getLifecycleFolderForUpdate = `-- name: GetLifecycleFolderForUpdate :one
SELECT
  e.namespace_entry_id, e.space_id, e.parent_folder_id, e.entry_type, e.name,
  e.normalized_name, e.path_cache, e.depth, e.lifecycle_status, e.created_by_user_id,
  e.created_at, e.updated_at, e.deleted_at, e.row_version,
  (s.root_folder_id = e.namespace_entry_id) AS is_root
FROM namespace_entries e
JOIN spaces s ON s.space_id = e.space_id
WHERE e.namespace_entry_id = $1
  AND e.entry_type = 'FOLDER'
  AND e.lifecycle_status = 'ACTIVE'
  AND s.status <> 'DELETED'
FOR UPDATE OF e
`

type GetLifecycleFolderForUpdateRow struct {
	NamespaceEntryID pgtype.UUID
	SpaceID          pgtype.UUID
	ParentFolderID   pgtype.UUID
	EntryType        string
	Name             string
	NormalizedName   string
	PathCache        pgtype.Text
	Depth            int32
	LifecycleStatus  string
	CreatedByUserID  pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	RowVersion       int64
	IsRoot           bool
}

func (q *Queries) GetLifecycleFolderForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetLifecycleFolderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLifecycleFolderForUpdate, namespaceEntryID)
	var i GetLifecycleFolderForUpdateRow
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
		&i.IsRoot,
	)
	return &i, err
}

const getLifecycleIdempotency = `-- name: GetLifecycleIdempotency :one
SELECT request_hash, status, result_resource_id FROM idempotency_records
WHERE principal_kind = 'USER' AND user_id = $1 AND operation = $2 AND idempotency_key = $3
`

type GetLifecycleIdempotencyParams struct {
	UserID         pgtype.UUID
	Operation      string
	IdempotencyKey string
}

type GetLifecycleIdempotencyRow struct {
	RequestHash      []byte
	Status           string
	ResultResourceID pgtype.UUID
}

func (q *Queries) GetLifecycleIdempotency(ctx context.Context, arg *GetLifecycleIdempotencyParams) (*GetLifecycleIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getLifecycleIdempotency, arg.UserID, arg.Operation, arg.IdempotencyKey)
	var i GetLifecycleIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.Status, &i.ResultResourceID)
	return &i, err
}

const getPreservationHold = `-- name: GetPreservationHold :one
SELECT legal_hold_id, document_id, document_version_id, case_reference, reason, status, placed_by_user_id, placed_at, released_by_user_id, released_at, release_reason, created_at, updated_at, row_version FROM legal_holds WHERE legal_hold_id = $1
`

func (q *Queries) GetPreservationHold(ctx context.Context, legalHoldID pgtype.UUID) (*LegalHold, error) {
	row := q.db.QueryRow(ctx, getPreservationHold, legalHoldID)
	var i LegalHold
	err := row.Scan(
		&i.LegalHoldID,
		&i.DocumentID,
		&i.DocumentVersionID,
		&i.CaseReference,
		&i.Reason,
		&i.Status,
		&i.PlacedByUserID,
		&i.PlacedAt,
		&i.ReleasedByUserID,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getPreservationHoldForUpdate = `-- name: GetPreservationHoldForUpdate :one
SELECT legal_hold_id, document_id, document_version_id, case_reference, reason, status, placed_by_user_id, placed_at, released_by_user_id, released_at, release_reason, created_at, updated_at, row_version FROM legal_holds WHERE legal_hold_id = $1 FOR UPDATE
`

func (q *Queries) GetPreservationHoldForUpdate(ctx context.Context, legalHoldID pgtype.UUID) (*LegalHold, error) {
	row := q.db.QueryRow(ctx, getPreservationHoldForUpdate, legalHoldID)
	var i LegalHold
	err := row.Scan(
		&i.LegalHoldID,
		&i.DocumentID,
		&i.DocumentVersionID,
		&i.CaseReference,
		&i.Reason,
		&i.Status,
		&i.PlacedByUserID,
		&i.PlacedAt,
		&i.ReleasedByUserID,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getRecycleItemWithEntry = `-- name: GetRecycleItemWithEntry :one
SELECT
  r.recycle_item_id, r.namespace_entry_id, r.original_space_id, r.original_parent_folder_id,
  r.original_name, r.deleted_by_user_id, r.deleted_at, r.expires_at, r.status,
  r.restored_to_folder_id, r.restored_at, r.created_at, r.updated_at, r.row_version,
  e.entry_type, e.name AS current_name, e.lifecycle_status
FROM recycle_items r
JOIN namespace_entries e ON e.namespace_entry_id = r.namespace_entry_id
WHERE r.recycle_item_id = $1
`

type GetRecycleItemWithEntryRow struct {
	RecycleItemID          pgtype.UUID
	NamespaceEntryID       pgtype.UUID
	OriginalSpaceID        pgtype.UUID
	OriginalParentFolderID pgtype.UUID
	OriginalName           string
	DeletedByUserID        pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	Status                 string
	RestoredToFolderID     pgtype.UUID
	RestoredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	RowVersion             int64
	EntryType              string
	CurrentName            string
	LifecycleStatus        string
}

func (q *Queries) GetRecycleItemWithEntry(ctx context.Context, recycleItemID pgtype.UUID) (*GetRecycleItemWithEntryRow, error) {
	row := q.db.QueryRow(ctx, getRecycleItemWithEntry, recycleItemID)
	var i GetRecycleItemWithEntryRow
	err := row.Scan(
		&i.RecycleItemID,
		&i.NamespaceEntryID,
		&i.OriginalSpaceID,
		&i.OriginalParentFolderID,
		&i.OriginalName,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RestoredToFolderID,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
		&i.EntryType,
		&i.CurrentName,
		&i.LifecycleStatus,
	)
	return &i, err
}

const getRecycleItemWithEntryForUpdate = `-- name: GetRecycleItemWithEntryForUpdate :one
SELECT
  r.recycle_item_id, r.namespace_entry_id, r.original_space_id, r.original_parent_folder_id,
  r.original_name, r.deleted_by_user_id, r.deleted_at, r.expires_at, r.status,
  r.restored_to_folder_id, r.restored_at, r.created_at, r.updated_at, r.row_version,
  e.entry_type, e.name AS current_name, e.lifecycle_status
FROM recycle_items r
JOIN namespace_entries e ON e.namespace_entry_id = r.namespace_entry_id
WHERE r.recycle_item_id = $1
FOR UPDATE OF r
`

type GetRecycleItemWithEntryForUpdateRow struct {
	RecycleItemID          pgtype.UUID
	NamespaceEntryID       pgtype.UUID
	OriginalSpaceID        pgtype.UUID
	OriginalParentFolderID pgtype.UUID
	OriginalName           string
	DeletedByUserID        pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	Status                 string
	RestoredToFolderID     pgtype.UUID
	RestoredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	RowVersion             int64
	EntryType              string
	CurrentName            string
	LifecycleStatus        string
}

func (q *Queries) GetRecycleItemWithEntryForUpdate(ctx context.Context, recycleItemID pgtype.UUID) (*GetRecycleItemWithEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRecycleItemWithEntryForUpdate, recycleItemID)
	var i GetRecycleItemWithEntryForUpdateRow
	err := row.Scan(
		&i.RecycleItemID,
		&i.NamespaceEntryID,
		&i.OriginalSpaceID,
		&i.OriginalParentFolderID,
		&i.OriginalName,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RestoredToFolderID,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
		&i.EntryType,
		&i.CurrentName,
		&i.LifecycleStatus,
	)
	return &i, err
}

const insertLifecycleOutboxEvent = `-- name: InsertLifecycleOutboxEvent :exec
INSERT INTO outbox_events (
  outbox_event_id, aggregate_type, aggregate_id, aggregate_version,
  event_type, payload_json, deduplication_key, correlation_id, available_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertLifecycleOutboxEventParams struct {
	OutboxEventID    pgtype.UUID
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
	PayloadJson      []byte
	DeduplicationKey string
	CorrelationID    pgtype.UUID
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertLifecycleOutboxEvent(ctx context.Context, arg *InsertLifecycleOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertLifecycleOutboxEvent,
		arg.OutboxEventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.PayloadJson,
		arg.DeduplicationKey,
		arg.CorrelationID,
		arg.AvailableAt,
	)
	return err
}

const insertPreservationHold = `-- name: InsertPreservationHold :one
INSERT INTO legal_holds (
  legal_hold_id, document_id, document_version_id, case_reference, reason,
  placed_by_user_id, placed_at, created_at, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$7,$7)
RETURNING legal_hold_id, document_id, document_version_id, case_reference, reason, status, placed_by_user_id, placed_at, released_by_user_id, released_at, release_reason, created_at, updated_at, row_version
`

type InsertPreservationHoldParams struct {
	LegalHoldID       pgtype.UUID
	DocumentID        pgtype.UUID
	DocumentVersionID pgtype.UUID
	CaseReference     string
	Reason            string
	PlacedByUserID    pgtype.UUID
	PlacedAt          pgtype.Timestamptz
}

func (q *Queries) InsertPreservationHold(ctx context.Context, arg *InsertPreservationHoldParams) (*LegalHold, error) {
	row := q.db.QueryRow(ctx, insertPreservationHold,
		arg.LegalHoldID,
		arg.DocumentID,
		arg.DocumentVersionID,
		arg.CaseReference,
		arg.Reason,
		arg.PlacedByUserID,
		arg.PlacedAt,
	)
	var i LegalHold
	err := row.Scan(
		&i.LegalHoldID,
		&i.DocumentID,
		&i.DocumentVersionID,
		&i.CaseReference,
		&i.Reason,
		&i.Status,
		&i.PlacedByUserID,
		&i.PlacedAt,
		&i.ReleasedByUserID,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertRecycleItem = `-- name: InsertRecycleItem :one
INSERT INTO recycle_items (
  recycle_item_id, namespace_entry_id, original_space_id, original_parent_folder_id,
  original_name, deleted_by_user_id, deleted_at, expires_at, created_at, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$7,$7)
RETURNING recycle_item_id, namespace_entry_id, original_space_id, original_parent_folder_id, original_name, deleted_by_user_id, deleted_at, expires_at, status, restored_to_folder_id, restored_at, created_at, updated_at, row_version
`

type InsertRecycleItemParams struct {
	RecycleItemID          pgtype.UUID
	NamespaceEntryID       pgtype.UUID
	OriginalSpaceID        pgtype.UUID
	OriginalParentFolderID pgtype.UUID
	OriginalName           string
	DeletedByUserID        pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
}

func (q *Queries) InsertRecycleItem(ctx context.Context, arg *InsertRecycleItemParams) (*RecycleItem, error) {
	row := q.db.QueryRow(ctx, insertRecycleItem,
		arg.RecycleItemID,
		arg.NamespaceEntryID,
		arg.OriginalSpaceID,
		arg.OriginalParentFolderID,
		arg.OriginalName,
		arg.DeletedByUserID,
		arg.DeletedAt,
		arg.ExpiresAt,
	)
	var i RecycleItem
	err := row.Scan(
		&i.RecycleItemID,
		&i.NamespaceEntryID,
		&i.OriginalSpaceID,
		&i.OriginalParentFolderID,
		&i.OriginalName,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RestoredToFolderID,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const lifecycleNameExists = `-- name: LifecycleNameExists :one
SELECT EXISTS (
  SELECT 1
  FROM namespace_entries e
  WHERE e.space_id = $1
    AND (($2::uuid IS NULL AND e.parent_folder_id IS NULL) OR e.parent_folder_id = $2)
    AND e.normalized_name = $3
    AND e.lifecycle_status IN ('ACTIVE', 'ARCHIVED')
    AND e.namespace_entry_id <> $4
)::boolean
`

type LifecycleNameExistsParams struct {
	SpaceID          pgtype.UUID
	Column2          pgtype.UUID
	NormalizedName   string
	NamespaceEntryID pgtype.UUID
}

func (q *Queries) LifecycleNameExists(ctx context.Context, arg *LifecycleNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, lifecycleNameExists,
		arg.SpaceID,
		arg.Column2,
		arg.NormalizedName,
		arg.NamespaceEntryID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listExpiredActiveRecycleItems = `-- name: ListExpiredActiveRecycleItems :many
SELECT
  r.recycle_item_id, r.namespace_entry_id, r.original_space_id, r.original_parent_folder_id,
  r.original_name, r.deleted_by_user_id, r.deleted_at, r.expires_at, r.status,
  r.restored_to_folder_id, r.restored_at, r.created_at, r.updated_at, r.row_version,
  e.entry_type, e.name AS current_name, e.lifecycle_status
FROM recycle_items r
JOIN namespace_entries e ON e.namespace_entry_id = r.namespace_entry_id
WHERE r.status = 'ACTIVE'
  AND r.expires_at <= $1::timestamptz
  AND e.lifecycle_status = 'TRASHED'
ORDER BY r.expires_at ASC, r.recycle_item_id ASC
LIMIT $2::integer
`

type ListExpiredActiveRecycleItemsParams struct {
	Now       pgtype.Timestamptz
	BatchSize int32
}

type ListExpiredActiveRecycleItemsRow struct {
	RecycleItemID          pgtype.UUID
	NamespaceEntryID       pgtype.UUID
	OriginalSpaceID        pgtype.UUID
	OriginalParentFolderID pgtype.UUID
	OriginalName           string
	DeletedByUserID        pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	Status                 string
	RestoredToFolderID     pgtype.UUID
	RestoredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	RowVersion             int64
	EntryType              string
	CurrentName            string
	LifecycleStatus        string
}

func (q *Queries) ListExpiredActiveRecycleItems(ctx context.Context, arg *ListExpiredActiveRecycleItemsParams) ([]*ListExpiredActiveRecycleItemsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveRecycleItems, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListExpiredActiveRecycleItemsRow{}
	for rows.Next() {
		var i ListExpiredActiveRecycleItemsRow
		if err := rows.Scan(
			&i.RecycleItemID,
			&i.NamespaceEntryID,
			&i.OriginalSpaceID,
			&i.OriginalParentFolderID,
			&i.OriginalName,
			&i.DeletedByUserID,
			&i.DeletedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RestoredToFolderID,
			&i.RestoredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
			&i.EntryType,
			&i.CurrentName,
			&i.LifecycleStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreservationHolds = `-- name: ListPreservationHolds :many
SELECT legal_hold_id, document_id, document_version_id, case_reference, reason, status, placed_by_user_id, placed_at, released_by_user_id, released_at, release_reason, created_at, updated_at, row_version
FROM legal_holds
WHERE ($1::uuid IS NULL OR document_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR case_reference ILIKE '%' || $3::text || '%')
ORDER BY placed_at DESC, legal_hold_id DESC
LIMIT $5::integer OFFSET $4::bigint
`

type ListPreservationHoldsParams struct {
	DocumentID    pgtype.UUID
	Status        pgtype.Text
	CaseReference pgtype.Text
	PageOffset    int64
	PageSize      int32
}

func (q *Queries) ListPreservationHolds(ctx context.Context, arg *ListPreservationHoldsParams) ([]*LegalHold, error) {
	rows, err := q.db.Query(ctx, listPreservationHolds,
		arg.DocumentID,
		arg.Status,
		arg.CaseReference,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LegalHold{}
	for rows.Next() {
		var i LegalHold
		if err := rows.Scan(
			&i.LegalHoldID,
			&i.DocumentID,
			&i.DocumentVersionID,
			&i.CaseReference,
			&i.Reason,
			&i.Status,
			&i.PlacedByUserID,
			&i.PlacedAt,
			&i.ReleasedByUserID,
			&i.ReleasedAt,
			&i.ReleaseReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecycleItems = `-- name: ListRecycleItems :many
SELECT
  r.recycle_item_id, r.namespace_entry_id, r.original_space_id, r.original_parent_folder_id,
  r.original_name, r.deleted_by_user_id, r.deleted_at, r.expires_at, r.status,
  r.restored_to_folder_id, r.restored_at, r.created_at, r.updated_at, r.row_version,
  e.entry_type, e.name AS current_name, e.lifecycle_status
FROM recycle_items r
JOIN namespace_entries e ON e.namespace_entry_id = r.namespace_entry_id
WHERE r.status = 'ACTIVE'
  AND ($1::uuid IS NULL OR r.original_space_id = $1::uuid)
ORDER BY r.deleted_at DESC, r.recycle_item_id DESC
LIMIT $3::integer OFFSET $2::bigint
`

type ListRecycleItemsParams struct {
	SpaceID    pgtype.UUID
	PageOffset int64
	PageSize   int32
}

type ListRecycleItemsRow struct {
	RecycleItemID          pgtype.UUID
	NamespaceEntryID       pgtype.UUID
	OriginalSpaceID        pgtype.UUID
	OriginalParentFolderID pgtype.UUID
	OriginalName           string
	DeletedByUserID        pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	Status                 string
	RestoredToFolderID     pgtype.UUID
	RestoredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	RowVersion             int64
	EntryType              string
	CurrentName            string
	LifecycleStatus        string
}

func (q *Queries) ListRecycleItems(ctx context.Context, arg *ListRecycleItemsParams) ([]*ListRecycleItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecycleItems, arg.SpaceID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRecycleItemsRow{}
	for rows.Next() {
		var i ListRecycleItemsRow
		if err := rows.Scan(
			&i.RecycleItemID,
			&i.NamespaceEntryID,
			&i.OriginalSpaceID,
			&i.OriginalParentFolderID,
			&i.OriginalName,
			&i.DeletedByUserID,
			&i.DeletedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RestoredToFolderID,
			&i.RestoredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
			&i.EntryType,
			&i.CurrentName,
			&i.LifecycleStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLifecycleEntrySubtreePurging = `-- name: MarkLifecycleEntrySubtreePurging :execrows
WITH RECURSIVE tree AS (
  SELECT namespace_entry_id
  FROM namespace_entries
  WHERE namespace_entry_id = $2::uuid
  UNION ALL
  SELECT child.namespace_entry_id
  FROM namespace_entries child
  JOIN tree parent ON child.parent_folder_id = parent.namespace_entry_id
  WHERE child.lifecycle_status = 'TRASHED'
)
UPDATE namespace_entries e
SET lifecycle_status = 'PURGING',
    deleted_at = $1::timestamptz,
    updated_at = $1::timestamptz,
    row_version = e.row_version + 1
FROM tree
WHERE e.namespace_entry_id = tree.namespace_entry_id
  AND e.lifecycle_status = 'TRASHED'
`

type MarkLifecycleEntrySubtreePurgingParams struct {
	DeletedAt pgtype.Timestamptz
	RootID    pgtype.UUID
}

func (q *Queries) MarkLifecycleEntrySubtreePurging(ctx context.Context, arg *MarkLifecycleEntrySubtreePurgingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLifecycleEntrySubtreePurging, arg.DeletedAt, arg.RootID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRecycleItemPurging = `-- name: MarkRecycleItemPurging :one
UPDATE recycle_items
SET status = 'PURGING',
    updated_at = $3,
    row_version = row_version + 1
WHERE recycle_item_id = $1
  AND row_version = $2
  AND status = 'ACTIVE'
RETURNING recycle_item_id, namespace_entry_id, original_space_id, original_parent_folder_id, original_name, deleted_by_user_id, deleted_at, expires_at, status, restored_to_folder_id, restored_at, created_at, updated_at, row_version
`

type MarkRecycleItemPurgingParams struct {
	RecycleItemID pgtype.UUID
	RowVersion    int64
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) MarkRecycleItemPurging(ctx context.Context, arg *MarkRecycleItemPurgingParams) (*RecycleItem, error) {
	row := q.db.QueryRow(ctx, markRecycleItemPurging, arg.RecycleItemID, arg.RowVersion, arg.UpdatedAt)
	var i RecycleItem
	err := row.Scan(
		&i.RecycleItemID,
		&i.NamespaceEntryID,
		&i.OriginalSpaceID,
		&i.OriginalParentFolderID,
		&i.OriginalName,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RestoredToFolderID,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const markSharesSourceUnavailableForEntrySubtree = `-- name: MarkSharesSourceUnavailableForEntrySubtree :exec
WITH RECURSIVE tree AS (
  SELECT namespace_entry_id, entry_type
  FROM namespace_entries
  WHERE namespace_entry_id = $2::uuid
  UNION ALL
  SELECT child.namespace_entry_id, child.entry_type
  FROM namespace_entries child
  JOIN tree parent ON child.parent_folder_id = parent.namespace_entry_id
)
UPDATE shares s
SET status = 'SOURCE_UNAVAILABLE',
    updated_at = $1::timestamptz,
    row_version = s.row_version + 1
WHERE s.status = 'ACTIVE'
  AND (
    s.source_document_id IN (SELECT namespace_entry_id FROM tree WHERE entry_type = 'DOCUMENT')
    OR s.source_folder_id IN (SELECT namespace_entry_id FROM tree WHERE entry_type = 'FOLDER')
  )
`

type MarkSharesSourceUnavailableForEntrySubtreeParams struct {
	UpdatedAt pgtype.Timestamptz
	RootID    pgtype.UUID
}

func (q *Queries) MarkSharesSourceUnavailableForEntrySubtree(ctx context.Context, arg *MarkSharesSourceUnavailableForEntrySubtreeParams) error {
	_, err := q.db.Exec(ctx, markSharesSourceUnavailableForEntrySubtree, arg.UpdatedAt, arg.RootID)
	return err
}

const moveRestoreLifecycleRoot = `-- name: MoveRestoreLifecycleRoot :one
UPDATE namespace_entries
SET parent_folder_id = $2,
    name = $3,
    normalized_name = $4,
    path_cache = $5,
    depth = $6,
    updated_at = $7,
    row_version = row_version + 1
WHERE namespace_entry_id = $1
  AND lifecycle_status = 'TRASHED'
RETURNING namespace_entry_id, space_id, parent_folder_id, entry_type, name, normalized_name, path_cache, depth, lifecycle_status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type MoveRestoreLifecycleRootParams struct {
	NamespaceEntryID pgtype.UUID
	ParentFolderID   pgtype.UUID
	Name             string
	NormalizedName   string
	PathCache        pgtype.Text
	Depth            int32
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) MoveRestoreLifecycleRoot(ctx context.Context, arg *MoveRestoreLifecycleRootParams) (*NamespaceEntry, error) {
	row := q.db.QueryRow(ctx, moveRestoreLifecycleRoot,
		arg.NamespaceEntryID,
		arg.ParentFolderID,
		arg.Name,
		arg.NormalizedName,
		arg.PathCache,
		arg.Depth,
		arg.UpdatedAt,
	)
	var i NamespaceEntry
	err := row.Scan(
		&i.NamespaceEntryID,
		&i.SpaceID,
		&i.ParentFolderID,
		&i.EntryType,
		&i.Name,
		&i.NormalizedName,
		&i.PathCache,
		&i.Depth,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const releasePreservationHold = `-- name: ReleasePreservationHold :one
UPDATE legal_holds
SET status = 'RELEASED',
    released_by_user_id = $2,
    released_at = $3,
    release_reason = $4,
    updated_at = $3,
    row_version = row_version + 1
WHERE legal_hold_id = $1
  AND row_version = $5
  AND status = 'ACTIVE'
RETURNING legal_hold_id, document_id, document_version_id, case_reference, reason, status, placed_by_user_id, placed_at, released_by_user_id, released_at, release_reason, created_at, updated_at, row_version
`

type ReleasePreservationHoldParams struct {
	LegalHoldID      pgtype.UUID
	ReleasedByUserID pgtype.UUID
	ReleasedAt       pgtype.Timestamptz
	ReleaseReason    pgtype.Text
	RowVersion       int64
}

func (q *Queries) ReleasePreservationHold(ctx context.Context, arg *ReleasePreservationHoldParams) (*LegalHold, error) {
	row := q.db.QueryRow(ctx, releasePreservationHold,
		arg.LegalHoldID,
		arg.ReleasedByUserID,
		arg.ReleasedAt,
		arg.ReleaseReason,
		arg.RowVersion,
	)
	var i LegalHold
	err := row.Scan(
		&i.LegalHoldID,
		&i.DocumentID,
		&i.DocumentVersionID,
		&i.CaseReference,
		&i.Reason,
		&i.Status,
		&i.PlacedByUserID,
		&i.PlacedAt,
		&i.ReleasedByUserID,
		&i.ReleasedAt,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const restoreLifecycleEntrySubtree = `-- name: RestoreLifecycleEntrySubtree :execrows
WITH RECURSIVE tree AS (
  SELECT namespace_entry_id
  FROM namespace_entries
  WHERE namespace_entry_id = $2::uuid
  UNION ALL
  SELECT child.namespace_entry_id
  FROM namespace_entries child
  JOIN tree parent ON child.parent_folder_id = parent.namespace_entry_id
  WHERE child.lifecycle_status = 'TRASHED'
)
UPDATE namespace_entries e
SET lifecycle_status = 'ACTIVE',
    updated_at = $1::timestamptz,
    row_version = e.row_version + 1
FROM tree
WHERE e.namespace_entry_id = tree.namespace_entry_id
  AND e.lifecycle_status = 'TRASHED'
`

type RestoreLifecycleEntrySubtreeParams struct {
	UpdatedAt pgtype.Timestamptz
	RootID    pgtype.UUID
}

func (q *Queries) RestoreLifecycleEntrySubtree(ctx context.Context, arg *RestoreLifecycleEntrySubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreLifecycleEntrySubtree, arg.UpdatedAt, arg.RootID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreRecycleItem = `-- name: RestoreRecycleItem :one
UPDATE recycle_items
SET status = 'RESTORED',
    restored_to_folder_id = $2,
    restored_at = $3,
    updated_at = $3,
    row_version = row_version + 1
WHERE recycle_item_id = $1
  AND row_version = $4
  AND status = 'ACTIVE'
RETURNING recycle_item_id, namespace_entry_id, original_space_id, original_parent_folder_id, original_name, deleted_by_user_id, deleted_at, expires_at, status, restored_to_folder_id, restored_at, created_at, updated_at, row_version
`

type RestoreRecycleItemParams struct {
	RecycleItemID      pgtype.UUID
	RestoredToFolderID pgtype.UUID
	RestoredAt         pgtype.Timestamptz
	RowVersion         int64
}

func (q *Queries) RestoreRecycleItem(ctx context.Context, arg *RestoreRecycleItemParams) (*RecycleItem, error) {
	row := q.db.QueryRow(ctx, restoreRecycleItem,
		arg.RecycleItemID,
		arg.RestoredToFolderID,
		arg.RestoredAt,
		arg.RowVersion,
	)
	var i RecycleItem
	err := row.Scan(
		&i.RecycleItemID,
		&i.NamespaceEntryID,
		&i.OriginalSpaceID,
		&i.OriginalParentFolderID,
		&i.OriginalName,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RestoredToFolderID,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const touchLifecycleSpaceSecurityEpoch = `-- name: TouchLifecycleSpaceSecurityEpoch :exec
UPDATE spaces
SET security_epoch = security_epoch + 1,
    updated_at = $2,
    row_version = row_version + 1
WHERE space_id = $1 AND status <> 'DELETED'
`

type TouchLifecycleSpaceSecurityEpochParams struct {
	SpaceID   pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) TouchLifecycleSpaceSecurityEpoch(ctx context.Context, arg *TouchLifecycleSpaceSecurityEpochParams) error {
	_, err := q.db.Exec(ctx, touchLifecycleSpaceSecurityEpoch, arg.SpaceID, arg.UpdatedAt)
	return err
}

const trashLifecycleEntrySubtree = `-- name: TrashLifecycleEntrySubtree :execrows
WITH RECURSIVE tree AS (
  SELECT namespace_entry_id
  FROM namespace_entries
  WHERE namespace_entry_id = $2::uuid
  UNION ALL
  SELECT child.namespace_entry_id
  FROM namespace_entries child
  JOIN tree parent ON child.parent_folder_id = parent.namespace_entry_id
  WHERE child.lifecycle_status IN ('ACTIVE', 'ARCHIVED')
)
UPDATE namespace_entries e
SET lifecycle_status = 'TRASHED',
    updated_at = $1::timestamptz,
    row_version = e.row_version + 1
FROM tree
WHERE e.namespace_entry_id = tree.namespace_entry_id
  AND e.lifecycle_status IN ('ACTIVE', 'ARCHIVED')
`

type TrashLifecycleEntrySubtreeParams struct {
	UpdatedAt pgtype.Timestamptz
	RootID    pgtype.UUID
}

func (q *Queries) TrashLifecycleEntrySubtree(ctx context.Context, arg *TrashLifecycleEntrySubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, trashLifecycleEntrySubtree, arg.UpdatedAt, arg.RootID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryCreateLifecycleIdempotency = `-- name: TryCreateLifecycleIdempotency :execrows
INSERT INTO idempotency_records (
  idempotency_record_id, principal_kind, user_id, operation, idempotency_key, request_hash,
  status, expires_at, created_at, updated_at
) VALUES ($1,'USER',$2,$3,$4,$5,'IN_PROGRESS',$6,$7,$7)
ON CONFLICT DO NOTHING
`

type TryCreateLifecycleIdempotencyParams struct {
	IdempotencyRecordID pgtype.UUID
	UserID              pgtype.UUID
	Operation           string
	IdempotencyKey      string
	RequestHash         []byte
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) TryCreateLifecycleIdempotency(ctx context.Context, arg *TryCreateLifecycleIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryCreateLifecycleIdempotency,
		arg.IdempotencyRecordID,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLifecycleDescendantPaths = `-- name: UpdateLifecycleDescendantPaths :exec
WITH RECURSIVE tree AS (
  SELECT child.namespace_entry_id,
         $2::text || '/' || child.name AS new_path,
         $3::integer + 1 AS new_depth
  FROM namespace_entries child
  WHERE child.parent_folder_id = $4::uuid
  UNION ALL
  SELECT child.namespace_entry_id,
         tree.new_path || '/' || child.name AS new_path,
         tree.new_depth + 1
  FROM namespace_entries child
  JOIN tree ON child.parent_folder_id = tree.namespace_entry_id
)
UPDATE namespace_entries e
SET path_cache = tree.new_path,
    depth = tree.new_depth,
    updated_at = $1::timestamptz,
    row_version = e.row_version + 1
FROM tree
WHERE e.namespace_entry_id = tree.namespace_entry_id
`

type UpdateLifecycleDescendantPathsParams struct {
	UpdatedAt pgtype.Timestamptz
	RootPath  string
	RootDepth int32
	RootID    pgtype.UUID
}

func (q *Queries) UpdateLifecycleDescendantPaths(ctx context.Context, arg *UpdateLifecycleDescendantPathsParams) error {
	_, err := q.db.Exec(ctx, updateLifecycleDescendantPaths,
		arg.UpdatedAt,
		arg.RootPath,
		arg.RootDepth,
		arg.RootID,
	)
	return err
}
