// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminDelegation struct {
	AdminDelegationID       pgtype.UUID
	UserID                  pgtype.UUID
	OrganizationID          pgtype.UUID
	Scope                   string
	CanDelegate             bool
	ParentAdminDelegationID pgtype.UUID
	GrantedByUserID         pgtype.UUID
	ValidFrom               pgtype.Timestamptz
	ValidUntil              pgtype.Timestamptz
	Status                  string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	RevokedAt               pgtype.Timestamptz
	RevokeReason            pgtype.Text
	RowVersion              int64
}

type Document struct {
	DocumentID            pgtype.UUID
	OwnerUserID           pgtype.UUID
	CurrentVersionID      pgtype.UUID
	AvailabilityStatus    string
	ExtensionNormalized   pgtype.Text
	InheritanceMode       string
	AclVersion            int64
	Classification        pgtype.Text
	MetadataSchemaVersion int32
	MetadataJson          []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RowVersion            int64
}

type NamespaceEntry struct {
	NamespaceEntryID pgtype.UUID
	SpaceID          pgtype.UUID
	ParentFolderID   pgtype.UUID
	EntryType        string
	Name             string
	NormalizedName   string
	PathCache        pgtype.Text
	Depth            int32
	LifecycleStatus  string
	CreatedByUserID  pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	RowVersion       int64
}

type Organization struct {
	OrganizationID       pgtype.UUID
	ParentOrganizationID pgtype.UUID
	Name                 string
	NormalizedName       string
	Code                 pgtype.Text
	NormalizedCode       pgtype.Text
	TypeLabel            pgtype.Text
	SortOrder            int32
	PathCache            pgtype.Text
	Depth                int32
	TreeVersion          int64
	Status               string
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

type OrganizationChangeOperation struct {
	OrganizationChangeOperationID pgtype.UUID
	OrganizationChangePlanID      pgtype.UUID
	SequenceNumber                int32
	OperationType                 string
	SourceOrganizationID          pgtype.UUID
	TargetOrganizationID          pgtype.UUID
	OperationSchemaVersion        int32
	OperationJson                 []byte
	Status                        string
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	CompletedAt                   pgtype.Timestamptz
	FailureCode                   pgtype.Text
	RowVersion                    int64
}

type OrganizationChangePlan struct {
	OrganizationChangePlanID pgtype.UUID
	PlanType                 string
	Name                     string
	Status                   string
	ExpectedTreeVersion      int64
	CreatedByUserID          pgtype.UUID
	ApprovedByUserID         pgtype.UUID
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	ValidatedAt              pgtype.Timestamptz
	ApprovedAt               pgtype.Timestamptz
	StartedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
	FailureCode              pgtype.Text
	RowVersion               int64
}

type OutboxEvent struct {
	OutboxEventID      pgtype.UUID
	AggregateType      string
	AggregateID        pgtype.UUID
	AggregateVersion   int64
	EventType          string
	EventSchemaVersion int32
	PayloadJson        []byte
	DeduplicationKey   string
	CorrelationID      pgtype.UUID
	CausationID        pgtype.UUID
	Priority           int32
	Status             string
	AttemptCount       int32
	MaxAttempts        int32
	AvailableAt        pgtype.Timestamptz
	LockedBy           pgtype.Text
	LockedAt           pgtype.Timestamptz
	LeaseUntil         pgtype.Timestamptz
	NextRetryAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
	LastErrorCode      pgtype.Text
	LastErrorSummary   pgtype.Text
	RowVersion         int64
}

type PermissionGrant struct {
	PermissionGrantID     pgtype.UUID
	SubjectUserID         pgtype.UUID
	SubjectOrganizationID pgtype.UUID
	SpaceID               pgtype.UUID
	FolderID              pgtype.UUID
	DocumentID            pgtype.UUID
	InheritToDescendants  bool
	GrantSource           string
	ValidFrom             pgtype.Timestamptz
	ValidUntil            pgtype.Timestamptz
	Status                string
	GrantedByUserID       pgtype.UUID
	GrantReason           pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	RevokedByUserID       pgtype.UUID
	RevokeReason          pgtype.Text
	RowVersion            int64
}

type QuotaReservation struct {
	QuotaReservationID pgtype.UUID
	SpaceID            pgtype.UUID
	UserID             pgtype.UUID
	ReservedBytes      int64
	Status             string
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ConsumedAt         pgtype.Timestamptz
	ReleasedAt         pgtype.Timestamptz
	RowVersion         int64
}

type Space struct {
	SpaceID             pgtype.UUID
	SpaceType           string
	Name                string
	NormalizedName      string
	OwnerUserID         pgtype.UUID
	OrganizationID      pgtype.UUID
	RootFolderID        pgtype.UUID
	QuotaBytes          int64
	UsedBytes           int64
	ReservedBytes       int64
	AclVersion          int64
	SecurityEpoch       int64
	ConfigSchemaVersion int32
	ConfigJson          []byte
	Status              string
	CreatedByUserID     pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	RowVersion          int64
}

type UserOrganization struct {
	UserOrganizationID pgtype.UUID
	UserID             pgtype.UUID
	OrganizationID     pgtype.UUID
	MembershipType     string
	JobTitle           pgtype.Text
	Status             string
	EffectiveFrom      pgtype.Timestamptz
	EffectiveUntil     pgtype.Timestamptz
	CreatedByUserID    pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	RowVersion         int64
}

type UserSession struct {
	UserSessionID pgtype.UUID
	UserID        pgtype.UUID
	DeviceID      pgtype.Text
	IpAddress     *netip.Addr
	UserAgent     pgtype.Text
	Status        string
	ExpiresAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokeReason  pgtype.Text
	RowVersion    int64
}
