// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOrganizationIdempotencyRecord = `-- name: CompleteOrganizationIdempotencyRecord :exec
UPDATE idempotency_records
SET status = 'COMPLETED',
    response_status_code = 201,
    response_schema_version = 1,
    response_json = jsonb_build_object('resourceId', $4::uuid),
    result_resource_type = $5,
    result_resource_id = $4,
    completed_at = $6,
    updated_at = $6,
    row_version = row_version + 1
WHERE user_id = $1
  AND operation = $2
  AND idempotency_key = $3
  AND status = 'IN_PROGRESS'
`

type CompleteOrganizationIdempotencyRecordParams struct {
	UserID             pgtype.UUID
	Operation          string
	IdempotencyKey     string
	ResultResourceID   pgtype.UUID
	ResultResourceType pgtype.Text
	CompletedAt        pgtype.Timestamptz
}

func (q *Queries) CompleteOrganizationIdempotencyRecord(ctx context.Context, arg *CompleteOrganizationIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, completeOrganizationIdempotencyRecord,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.ResultResourceID,
		arg.ResultResourceType,
		arg.CompletedAt,
	)
	return err
}

const consumeSpaceQuotaReservation = `-- name: ConsumeSpaceQuotaReservation :execrows
UPDATE spaces
SET reserved_bytes = reserved_bytes - $2,
    used_bytes = used_bytes + $3,
    updated_at = $4,
    row_version = row_version + 1
WHERE space_id = $1
  AND reserved_bytes >= $2
  AND used_bytes + reserved_bytes - $2 + $3 <= quota_bytes
`

type ConsumeSpaceQuotaReservationParams struct {
	SpaceID       pgtype.UUID
	ReservedBytes int64
	UsedBytes     int64
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ConsumeSpaceQuotaReservation(ctx context.Context, arg *ConsumeSpaceQuotaReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeSpaceQuotaReservation,
		arg.SpaceID,
		arg.ReservedBytes,
		arg.UsedBytes,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMemberships = `-- name: CountMemberships :one
SELECT count(*)::bigint
FROM user_organizations
WHERE ($1::uuid IS NULL OR organization_id = $1)
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL OR (
      effective_from <= $4
      AND (effective_until IS NULL OR effective_until > $4)
  ))
`

type CountMembershipsParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Status         pgtype.Text
	EffectiveAt    pgtype.Timestamptz
}

func (q *Queries) CountMemberships(ctx context.Context, arg *CountMembershipsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberships,
		arg.OrganizationID,
		arg.UserID,
		arg.Status,
		arg.EffectiveAt,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrganizationChangePlans = `-- name: CountOrganizationChangePlans :one
SELECT count(*)::bigint
FROM organization_change_plans
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountOrganizationChangePlans(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationChangePlans, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrganizationRowVersion = `-- name: CountOrganizationRowVersion :one
SELECT count(*)::bigint
FROM organizations
WHERE organization_id = $1
  AND row_version = $2
`

type CountOrganizationRowVersionParams struct {
	OrganizationID pgtype.UUID
	RowVersion     int64
}

func (q *Queries) CountOrganizationRowVersion(ctx context.Context, arg *CountOrganizationRowVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationRowVersion, arg.OrganizationID, arg.RowVersion)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*)::bigint
FROM organizations
WHERE ($1::uuid IS NULL OR parent_organization_id = $1)
  AND ($2::text IS NULL OR status = $2)
`

type CountOrganizationsParams struct {
	ParentOrganizationID pgtype.UUID
	Status               pgtype.Text
}

func (q *Queries) CountOrganizations(ctx context.Context, arg *CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.ParentOrganizationID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSpaces = `-- name: CountSpaces :one
SELECT count(*)::bigint
FROM spaces
WHERE ($1::text IS NULL OR space_type = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR organization_id = $3)
  AND ($4::uuid IS NULL OR owner_user_id = $4)
`

type CountSpacesParams struct {
	SpaceType      pgtype.Text
	Status         pgtype.Text
	OrganizationID pgtype.UUID
	OwnerUserID    pgtype.UUID
}

func (q *Queries) CountSpaces(ctx context.Context, arg *CountSpacesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSpaces,
		arg.SpaceType,
		arg.Status,
		arg.OrganizationID,
		arg.OwnerUserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deactivateMembership = `-- name: DeactivateMembership :one
UPDATE user_organizations
SET status = 'INACTIVE',
    effective_until = COALESCE(effective_until, $3),
    updated_at = $3,
    row_version = row_version + 1
WHERE user_organization_id = $1
  AND organization_id = $2
  AND row_version = $4
RETURNING user_organization_id, user_id, organization_id, membership_type, job_title, status, effective_from, effective_until, created_by_user_id, created_at, updated_at, row_version
`

type DeactivateMembershipParams struct {
	UserOrganizationID pgtype.UUID
	OrganizationID     pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	RowVersion         int64
}

func (q *Queries) DeactivateMembership(ctx context.Context, arg *DeactivateMembershipParams) (*UserOrganization, error) {
	row := q.db.QueryRow(ctx, deactivateMembership,
		arg.UserOrganizationID,
		arg.OrganizationID,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i UserOrganization
	err := row.Scan(
		&i.UserOrganizationID,
		&i.UserID,
		&i.OrganizationID,
		&i.MembershipType,
		&i.JobTitle,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const deleteOrganizationExternalClosureLinks = `-- name: DeleteOrganizationExternalClosureLinks :exec
DELETE FROM organization_closure AS link
WHERE link.descendant_organization_id IN (
    SELECT subtree.descendant_organization_id
    FROM organization_closure AS subtree
    WHERE subtree.ancestor_organization_id = $1
)
AND link.ancestor_organization_id IN (
    SELECT ancestors.ancestor_organization_id
    FROM organization_closure AS ancestors
    WHERE ancestors.descendant_organization_id = $1
      AND ancestors.ancestor_organization_id <> $1
)
`

func (q *Queries) DeleteOrganizationExternalClosureLinks(ctx context.Context, ancestorOrganizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationExternalClosureLinks, ancestorOrganizationID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT user_organization_id, user_id, organization_id, membership_type, job_title, status, effective_from, effective_until, created_by_user_id, created_at, updated_at, row_version
FROM user_organizations
WHERE user_organization_id = $1
`

func (q *Queries) GetMembership(ctx context.Context, userOrganizationID pgtype.UUID) (*UserOrganization, error) {
	row := q.db.QueryRow(ctx, getMembership, userOrganizationID)
	var i UserOrganization
	err := row.Scan(
		&i.UserOrganizationID,
		&i.UserID,
		&i.OrganizationID,
		&i.MembershipType,
		&i.JobTitle,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getMembershipForUpdate = `-- name: GetMembershipForUpdate :one
SELECT user_organization_id, user_id, organization_id, membership_type, job_title, status, effective_from, effective_until, created_by_user_id, created_at, updated_at, row_version
FROM user_organizations
WHERE user_organization_id = $1
  AND organization_id = $2
FOR UPDATE
`

type GetMembershipForUpdateParams struct {
	UserOrganizationID pgtype.UUID
	OrganizationID     pgtype.UUID
}

func (q *Queries) GetMembershipForUpdate(ctx context.Context, arg *GetMembershipForUpdateParams) (*UserOrganization, error) {
	row := q.db.QueryRow(ctx, getMembershipForUpdate, arg.UserOrganizationID, arg.OrganizationID)
	var i UserOrganization
	err := row.Scan(
		&i.UserOrganizationID,
		&i.UserID,
		&i.OrganizationID,
		&i.MembershipType,
		&i.JobTitle,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT organization_id, parent_organization_id, name, normalized_name, code, normalized_code, type_label, sort_order, path_cache, depth, tree_version, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM organizations
WHERE organization_id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, organizationID pgtype.UUID) (*Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, organizationID)
	var i Organization
	err := row.Scan(
		&i.OrganizationID,
		&i.ParentOrganizationID,
		&i.Name,
		&i.NormalizedName,
		&i.Code,
		&i.NormalizedCode,
		&i.TypeLabel,
		&i.SortOrder,
		&i.PathCache,
		&i.Depth,
		&i.TreeVersion,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getOrganizationChangePlan = `-- name: GetOrganizationChangePlan :one
SELECT organization_change_plan_id, plan_type, name, status, expected_tree_version, created_by_user_id, approved_by_user_id, created_at, updated_at, validated_at, approved_at, started_at, completed_at, failure_code, row_version
FROM organization_change_plans
WHERE organization_change_plan_id = $1
`

func (q *Queries) GetOrganizationChangePlan(ctx context.Context, organizationChangePlanID pgtype.UUID) (*OrganizationChangePlan, error) {
	row := q.db.QueryRow(ctx, getOrganizationChangePlan, organizationChangePlanID)
	var i OrganizationChangePlan
	err := row.Scan(
		&i.OrganizationChangePlanID,
		&i.PlanType,
		&i.Name,
		&i.Status,
		&i.ExpectedTreeVersion,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ValidatedAt,
		&i.ApprovedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const getOrganizationChangePlanForUpdate = `-- name: GetOrganizationChangePlanForUpdate :one
SELECT organization_change_plan_id, plan_type, name, status, expected_tree_version, created_by_user_id, approved_by_user_id, created_at, updated_at, validated_at, approved_at, started_at, completed_at, failure_code, row_version
FROM organization_change_plans
WHERE organization_change_plan_id = $1
FOR UPDATE
`

func (q *Queries) GetOrganizationChangePlanForUpdate(ctx context.Context, organizationChangePlanID pgtype.UUID) (*OrganizationChangePlan, error) {
	row := q.db.QueryRow(ctx, getOrganizationChangePlanForUpdate, organizationChangePlanID)
	var i OrganizationChangePlan
	err := row.Scan(
		&i.OrganizationChangePlanID,
		&i.PlanType,
		&i.Name,
		&i.Status,
		&i.ExpectedTreeVersion,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ValidatedAt,
		&i.ApprovedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const getOrganizationForUpdate = `-- name: GetOrganizationForUpdate :one
SELECT organization_id, parent_organization_id, name, normalized_name, code, normalized_code, type_label, sort_order, path_cache, depth, tree_version, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM organizations
WHERE organization_id = $1
FOR UPDATE
`

func (q *Queries) GetOrganizationForUpdate(ctx context.Context, organizationID pgtype.UUID) (*Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationForUpdate, organizationID)
	var i Organization
	err := row.Scan(
		&i.OrganizationID,
		&i.ParentOrganizationID,
		&i.Name,
		&i.NormalizedName,
		&i.Code,
		&i.NormalizedCode,
		&i.TypeLabel,
		&i.SortOrder,
		&i.PathCache,
		&i.Depth,
		&i.TreeVersion,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getOrganizationIdempotencyRecordForUpdate = `-- name: GetOrganizationIdempotencyRecordForUpdate :one
SELECT request_hash, status, result_resource_id
FROM idempotency_records
WHERE principal_kind = 'USER'
  AND user_id = $1
  AND operation = $2
  AND idempotency_key = $3
FOR UPDATE
`

type GetOrganizationIdempotencyRecordForUpdateParams struct {
	UserID         pgtype.UUID
	Operation      string
	IdempotencyKey string
}

type GetOrganizationIdempotencyRecordForUpdateRow struct {
	RequestHash      []byte
	Status           string
	ResultResourceID pgtype.UUID
}

func (q *Queries) GetOrganizationIdempotencyRecordForUpdate(ctx context.Context, arg *GetOrganizationIdempotencyRecordForUpdateParams) (*GetOrganizationIdempotencyRecordForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationIdempotencyRecordForUpdate, arg.UserID, arg.Operation, arg.IdempotencyKey)
	var i GetOrganizationIdempotencyRecordForUpdateRow
	err := row.Scan(&i.RequestHash, &i.Status, &i.ResultResourceID)
	return &i, err
}

const getOrganizationSpace = `-- name: GetOrganizationSpace :one
SELECT space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM spaces
WHERE organization_id = $1
  AND space_type = 'ORGANIZATION'
  AND status <> 'DELETED'
`

func (q *Queries) GetOrganizationSpace(ctx context.Context, organizationID pgtype.UUID) (*Space, error) {
	row := q.db.QueryRow(ctx, getOrganizationSpace, organizationID)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getPersonalSpaceByUser = `-- name: GetPersonalSpaceByUser :one
SELECT space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM spaces
WHERE owner_user_id = $1
  AND space_type = 'PERSONAL'
  AND status <> 'DELETED'
`

func (q *Queries) GetPersonalSpaceByUser(ctx context.Context, ownerUserID pgtype.UUID) (*Space, error) {
	row := q.db.QueryRow(ctx, getPersonalSpaceByUser, ownerUserID)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getQuotaReservationForUpdate = `-- name: GetQuotaReservationForUpdate :one
SELECT quota_reservation_id, space_id, user_id, reserved_bytes, status, expires_at, created_at, updated_at, consumed_at, released_at, row_version
FROM quota_reservations
WHERE quota_reservation_id = $1
FOR UPDATE
`

func (q *Queries) GetQuotaReservationForUpdate(ctx context.Context, quotaReservationID pgtype.UUID) (*QuotaReservation, error) {
	row := q.db.QueryRow(ctx, getQuotaReservationForUpdate, quotaReservationID)
	var i QuotaReservation
	err := row.Scan(
		&i.QuotaReservationID,
		&i.SpaceID,
		&i.UserID,
		&i.ReservedBytes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsumedAt,
		&i.ReleasedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getSpace = `-- name: GetSpace :one
SELECT space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM spaces
WHERE space_id = $1
`

func (q *Queries) GetSpace(ctx context.Context, spaceID pgtype.UUID) (*Space, error) {
	row := q.db.QueryRow(ctx, getSpace, spaceID)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getSpaceForUpdate = `-- name: GetSpaceForUpdate :one
SELECT space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM spaces
WHERE space_id = $1
FOR UPDATE
`

func (q *Queries) GetSpaceForUpdate(ctx context.Context, spaceID pgtype.UUID) (*Space, error) {
	row := q.db.QueryRow(ctx, getSpaceForUpdate, spaceID)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const incrementOrganizationMembershipVersion = `-- name: IncrementOrganizationMembershipVersion :exec
UPDATE organization_security_versions
SET membership_version = membership_version + 1,
    subtree_security_epoch = subtree_security_epoch + 1,
    updated_at = $2
WHERE organization_id = $1
`

type IncrementOrganizationMembershipVersionParams struct {
	OrganizationID pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) IncrementOrganizationMembershipVersion(ctx context.Context, arg *IncrementOrganizationMembershipVersionParams) error {
	_, err := q.db.Exec(ctx, incrementOrganizationMembershipVersion, arg.OrganizationID, arg.UpdatedAt)
	return err
}

const incrementOrganizationSubtreeSecurityEpochs = `-- name: IncrementOrganizationSubtreeSecurityEpochs :exec
UPDATE organization_security_versions
SET subtree_security_epoch = subtree_security_epoch + 1,
    updated_at = $2
WHERE organization_id IN (
    SELECT ancestor_organization_id
    FROM organization_closure
    WHERE descendant_organization_id = $1
)
`

type IncrementOrganizationSubtreeSecurityEpochsParams struct {
	DescendantOrganizationID pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
}

func (q *Queries) IncrementOrganizationSubtreeSecurityEpochs(ctx context.Context, arg *IncrementOrganizationSubtreeSecurityEpochsParams) error {
	_, err := q.db.Exec(ctx, incrementOrganizationSubtreeSecurityEpochs, arg.DescendantOrganizationID, arg.UpdatedAt)
	return err
}

const incrementUserOrganizationMembershipVersion = `-- name: IncrementUserOrganizationMembershipVersion :exec
UPDATE principal_security_versions
SET organization_membership_version = organization_membership_version + 1,
    updated_at = $2
WHERE user_id = $1
`

type IncrementUserOrganizationMembershipVersionParams struct {
	UserID    pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) IncrementUserOrganizationMembershipVersion(ctx context.Context, arg *IncrementUserOrganizationMembershipVersionParams) error {
	_, err := q.db.Exec(ctx, incrementUserOrganizationMembershipVersion, arg.UserID, arg.UpdatedAt)
	return err
}

const insertMembership = `-- name: InsertMembership :one
INSERT INTO user_organizations (
    user_organization_id, user_id, organization_id, membership_type, job_title,
    effective_from, effective_until, created_by_user_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING user_organization_id, user_id, organization_id, membership_type, job_title, status, effective_from, effective_until, created_by_user_id, created_at, updated_at, row_version
`

type InsertMembershipParams struct {
	UserOrganizationID pgtype.UUID
	UserID             pgtype.UUID
	OrganizationID     pgtype.UUID
	MembershipType     string
	JobTitle           pgtype.Text
	EffectiveFrom      pgtype.Timestamptz
	EffectiveUntil     pgtype.Timestamptz
	CreatedByUserID    pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertMembership(ctx context.Context, arg *InsertMembershipParams) (*UserOrganization, error) {
	row := q.db.QueryRow(ctx, insertMembership,
		arg.UserOrganizationID,
		arg.UserID,
		arg.OrganizationID,
		arg.MembershipType,
		arg.JobTitle,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i UserOrganization
	err := row.Scan(
		&i.UserOrganizationID,
		&i.UserID,
		&i.OrganizationID,
		&i.MembershipType,
		&i.JobTitle,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertMovedOrganizationClosureLinks = `-- name: InsertMovedOrganizationClosureLinks :exec
INSERT INTO organization_closure (
    ancestor_organization_id, descendant_organization_id, depth, created_at
)
SELECT parent_path.ancestor_organization_id,
       subtree.descendant_organization_id,
       parent_path.depth + subtree.depth + 1,
       $3
FROM organization_closure AS parent_path
CROSS JOIN organization_closure AS subtree
WHERE parent_path.descendant_organization_id = $2
  AND subtree.ancestor_organization_id = $1
`

type InsertMovedOrganizationClosureLinksParams struct {
	AncestorOrganizationID   pgtype.UUID
	DescendantOrganizationID pgtype.UUID
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) InsertMovedOrganizationClosureLinks(ctx context.Context, arg *InsertMovedOrganizationClosureLinksParams) error {
	_, err := q.db.Exec(ctx, insertMovedOrganizationClosureLinks, arg.AncestorOrganizationID, arg.DescendantOrganizationID, arg.CreatedAt)
	return err
}

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organizations (
    organization_id, parent_organization_id, name, normalized_name, code,
    normalized_code, type_label, sort_order, depth, created_by_user_id,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
RETURNING organization_id, parent_organization_id, name, normalized_name, code, normalized_code, type_label, sort_order, path_cache, depth, tree_version, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type InsertOrganizationParams struct {
	OrganizationID       pgtype.UUID
	ParentOrganizationID pgtype.UUID
	Name                 string
	NormalizedName       string
	Code                 pgtype.Text
	NormalizedCode       pgtype.Text
	TypeLabel            pgtype.Text
	SortOrder            int32
	Depth                int32
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertOrganization(ctx context.Context, arg *InsertOrganizationParams) (*Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.OrganizationID,
		arg.ParentOrganizationID,
		arg.Name,
		arg.NormalizedName,
		arg.Code,
		arg.NormalizedCode,
		arg.TypeLabel,
		arg.SortOrder,
		arg.Depth,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.OrganizationID,
		&i.ParentOrganizationID,
		&i.Name,
		&i.NormalizedName,
		&i.Code,
		&i.NormalizedCode,
		&i.TypeLabel,
		&i.SortOrder,
		&i.PathCache,
		&i.Depth,
		&i.TreeVersion,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertOrganizationChangeOperation = `-- name: InsertOrganizationChangeOperation :one
INSERT INTO organization_change_operations (
    organization_change_operation_id, organization_change_plan_id, sequence_number,
    operation_type, source_organization_id, target_organization_id,
    operation_schema_version, operation_json, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING organization_change_operation_id, organization_change_plan_id, sequence_number, operation_type, source_organization_id, target_organization_id, operation_schema_version, operation_json, status, created_at, updated_at, completed_at, failure_code, row_version
`

type InsertOrganizationChangeOperationParams struct {
	OrganizationChangeOperationID pgtype.UUID
	OrganizationChangePlanID      pgtype.UUID
	SequenceNumber                int32
	OperationType                 string
	SourceOrganizationID          pgtype.UUID
	TargetOrganizationID          pgtype.UUID
	OperationSchemaVersion        int32
	OperationJson                 []byte
	CreatedAt                     pgtype.Timestamptz
}

func (q *Queries) InsertOrganizationChangeOperation(ctx context.Context, arg *InsertOrganizationChangeOperationParams) (*OrganizationChangeOperation, error) {
	row := q.db.QueryRow(ctx, insertOrganizationChangeOperation,
		arg.OrganizationChangeOperationID,
		arg.OrganizationChangePlanID,
		arg.SequenceNumber,
		arg.OperationType,
		arg.SourceOrganizationID,
		arg.TargetOrganizationID,
		arg.OperationSchemaVersion,
		arg.OperationJson,
		arg.CreatedAt,
	)
	var i OrganizationChangeOperation
	err := row.Scan(
		&i.OrganizationChangeOperationID,
		&i.OrganizationChangePlanID,
		&i.SequenceNumber,
		&i.OperationType,
		&i.SourceOrganizationID,
		&i.TargetOrganizationID,
		&i.OperationSchemaVersion,
		&i.OperationJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const insertOrganizationChangePlan = `-- name: InsertOrganizationChangePlan :one
INSERT INTO organization_change_plans (
    organization_change_plan_id, plan_type, name, expected_tree_version,
    created_by_user_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING organization_change_plan_id, plan_type, name, status, expected_tree_version, created_by_user_id, approved_by_user_id, created_at, updated_at, validated_at, approved_at, started_at, completed_at, failure_code, row_version
`

type InsertOrganizationChangePlanParams struct {
	OrganizationChangePlanID pgtype.UUID
	PlanType                 string
	Name                     string
	ExpectedTreeVersion      int64
	CreatedByUserID          pgtype.UUID
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) InsertOrganizationChangePlan(ctx context.Context, arg *InsertOrganizationChangePlanParams) (*OrganizationChangePlan, error) {
	row := q.db.QueryRow(ctx, insertOrganizationChangePlan,
		arg.OrganizationChangePlanID,
		arg.PlanType,
		arg.Name,
		arg.ExpectedTreeVersion,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i OrganizationChangePlan
	err := row.Scan(
		&i.OrganizationChangePlanID,
		&i.PlanType,
		&i.Name,
		&i.Status,
		&i.ExpectedTreeVersion,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ValidatedAt,
		&i.ApprovedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const insertOrganizationClosure = `-- name: InsertOrganizationClosure :exec
INSERT INTO organization_closure (
    ancestor_organization_id, descendant_organization_id, depth, created_at
)
SELECT ancestor_organization_id, $1::uuid, depth + 1, $2::timestamptz
FROM organization_closure
WHERE descendant_organization_id = $3::uuid
UNION ALL
SELECT $1::uuid, $1::uuid, 0, $2::timestamptz
`

type InsertOrganizationClosureParams struct {
	OrganizationID       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	ParentOrganizationID pgtype.UUID
}

func (q *Queries) InsertOrganizationClosure(ctx context.Context, arg *InsertOrganizationClosureParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationClosure, arg.OrganizationID, arg.CreatedAt, arg.ParentOrganizationID)
	return err
}

const insertOrganizationOutboxEvent = `-- name: InsertOrganizationOutboxEvent :exec
INSERT INTO outbox_events (
    outbox_event_id, aggregate_type, aggregate_id, aggregate_version, event_type,
    event_schema_version, payload_json, deduplication_key, correlation_id,
    max_attempts, available_at, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, 1, $6, $7, $8, 10, $9, $9, $9)
`

type InsertOrganizationOutboxEventParams struct {
	OutboxEventID    pgtype.UUID
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
	PayloadJson      []byte
	DeduplicationKey string
	CorrelationID    pgtype.UUID
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertOrganizationOutboxEvent(ctx context.Context, arg *InsertOrganizationOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationOutboxEvent,
		arg.OutboxEventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.PayloadJson,
		arg.DeduplicationKey,
		arg.CorrelationID,
		arg.AvailableAt,
	)
	return err
}

const insertOrganizationSecurityVersions = `-- name: InsertOrganizationSecurityVersions :exec
INSERT INTO organization_security_versions (organization_id, updated_at)
VALUES ($1, $2)
`

type InsertOrganizationSecurityVersionsParams struct {
	OrganizationID pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertOrganizationSecurityVersions(ctx context.Context, arg *InsertOrganizationSecurityVersionsParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationSecurityVersions, arg.OrganizationID, arg.UpdatedAt)
	return err
}

const insertQuotaReservation = `-- name: InsertQuotaReservation :one
INSERT INTO quota_reservations (
    quota_reservation_id, space_id, user_id, reserved_bytes, expires_at,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING quota_reservation_id, space_id, user_id, reserved_bytes, status, expires_at, created_at, updated_at, consumed_at, released_at, row_version
`

type InsertQuotaReservationParams struct {
	QuotaReservationID pgtype.UUID
	SpaceID            pgtype.UUID
	UserID             pgtype.UUID
	ReservedBytes      int64
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertQuotaReservation(ctx context.Context, arg *InsertQuotaReservationParams) (*QuotaReservation, error) {
	row := q.db.QueryRow(ctx, insertQuotaReservation,
		arg.QuotaReservationID,
		arg.SpaceID,
		arg.UserID,
		arg.ReservedBytes,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i QuotaReservation
	err := row.Scan(
		&i.QuotaReservationID,
		&i.SpaceID,
		&i.UserID,
		&i.ReservedBytes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsumedAt,
		&i.ReleasedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertSpace = `-- name: InsertSpace :one
INSERT INTO spaces (
    space_id, space_type, name, normalized_name, owner_user_id, organization_id,
    quota_bytes, config_schema_version, config_json, created_by_user_id,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
RETURNING space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type InsertSpaceParams struct {
	SpaceID             pgtype.UUID
	SpaceType           string
	Name                string
	NormalizedName      string
	OwnerUserID         pgtype.UUID
	OrganizationID      pgtype.UUID
	QuotaBytes          int64
	ConfigSchemaVersion int32
	ConfigJson          []byte
	CreatedByUserID     pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) InsertSpace(ctx context.Context, arg *InsertSpaceParams) (*Space, error) {
	row := q.db.QueryRow(ctx, insertSpace,
		arg.SpaceID,
		arg.SpaceType,
		arg.Name,
		arg.NormalizedName,
		arg.OwnerUserID,
		arg.OrganizationID,
		arg.QuotaBytes,
		arg.ConfigSchemaVersion,
		arg.ConfigJson,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT user_organization_id, user_id, organization_id, membership_type, job_title, status, effective_from, effective_until, created_by_user_id, created_at, updated_at, row_version
FROM user_organizations
WHERE ($1::uuid IS NULL OR organization_id = $1)
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL OR (
      effective_from <= $4
      AND (effective_until IS NULL OR effective_until > $4)
  ))
ORDER BY effective_from DESC, user_organization_id DESC
LIMIT $6::integer OFFSET $5::bigint
`

type ListMembershipsParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Status         pgtype.Text
	EffectiveAt    pgtype.Timestamptz
	PageOffset     int64
	PageSize       int32
}

func (q *Queries) ListMemberships(ctx context.Context, arg *ListMembershipsParams) ([]*UserOrganization, error) {
	rows, err := q.db.Query(ctx, listMemberships,
		arg.OrganizationID,
		arg.UserID,
		arg.Status,
		arg.EffectiveAt,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserOrganization{}
	for rows.Next() {
		var i UserOrganization
		if err := rows.Scan(
			&i.UserOrganizationID,
			&i.UserID,
			&i.OrganizationID,
			&i.MembershipType,
			&i.JobTitle,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationChangeOperations = `-- name: ListOrganizationChangeOperations :many
SELECT organization_change_operation_id, organization_change_plan_id, sequence_number, operation_type, source_organization_id, target_organization_id, operation_schema_version, operation_json, status, created_at, updated_at, completed_at, failure_code, row_version
FROM organization_change_operations
WHERE organization_change_plan_id = $1
ORDER BY sequence_number, organization_change_operation_id
`

func (q *Queries) ListOrganizationChangeOperations(ctx context.Context, organizationChangePlanID pgtype.UUID) ([]*OrganizationChangeOperation, error) {
	rows, err := q.db.Query(ctx, listOrganizationChangeOperations, organizationChangePlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrganizationChangeOperation{}
	for rows.Next() {
		var i OrganizationChangeOperation
		if err := rows.Scan(
			&i.OrganizationChangeOperationID,
			&i.OrganizationChangePlanID,
			&i.SequenceNumber,
			&i.OperationType,
			&i.SourceOrganizationID,
			&i.TargetOrganizationID,
			&i.OperationSchemaVersion,
			&i.OperationJson,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.FailureCode,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationChangePlans = `-- name: ListOrganizationChangePlans :many
SELECT organization_change_plan_id, plan_type, name, status, expected_tree_version, created_by_user_id, approved_by_user_id, created_at, updated_at, validated_at, approved_at, started_at, completed_at, failure_code, row_version
FROM organization_change_plans
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC, organization_change_plan_id DESC
LIMIT $3::integer OFFSET $2::bigint
`

type ListOrganizationChangePlansParams struct {
	Status     pgtype.Text
	PageOffset int64
	PageSize   int32
}

func (q *Queries) ListOrganizationChangePlans(ctx context.Context, arg *ListOrganizationChangePlansParams) ([]*OrganizationChangePlan, error) {
	rows, err := q.db.Query(ctx, listOrganizationChangePlans, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrganizationChangePlan{}
	for rows.Next() {
		var i OrganizationChangePlan
		if err := rows.Scan(
			&i.OrganizationChangePlanID,
			&i.PlanType,
			&i.Name,
			&i.Status,
			&i.ExpectedTreeVersion,
			&i.CreatedByUserID,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ValidatedAt,
			&i.ApprovedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureCode,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT organization_id, parent_organization_id, name, normalized_name, code, normalized_code, type_label, sort_order, path_cache, depth, tree_version, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM organizations
WHERE ($1::uuid IS NULL OR parent_organization_id = $1)
  AND ($2::text IS NULL OR status = $2)
ORDER BY sort_order, normalized_name, organization_id
LIMIT $4::integer OFFSET $3::bigint
`

type ListOrganizationsParams struct {
	ParentOrganizationID pgtype.UUID
	Status               pgtype.Text
	PageOffset           int64
	PageSize             int32
}

func (q *Queries) ListOrganizations(ctx context.Context, arg *ListOrganizationsParams) ([]*Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.ParentOrganizationID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ParentOrganizationID,
			&i.Name,
			&i.NormalizedName,
			&i.Code,
			&i.NormalizedCode,
			&i.TypeLabel,
			&i.SortOrder,
			&i.PathCache,
			&i.Depth,
			&i.TreeVersion,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM spaces
WHERE ($1::text IS NULL OR space_type = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR organization_id = $3)
  AND ($4::uuid IS NULL OR owner_user_id = $4)
ORDER BY created_at DESC, space_id DESC
LIMIT $6::integer OFFSET $5::bigint
`

type ListSpacesParams struct {
	SpaceType      pgtype.Text
	Status         pgtype.Text
	OrganizationID pgtype.UUID
	OwnerUserID    pgtype.UUID
	PageOffset     int64
	PageSize       int32
}

func (q *Queries) ListSpaces(ctx context.Context, arg *ListSpacesParams) ([]*Space, error) {
	rows, err := q.db.Query(ctx, listSpaces,
		arg.SpaceType,
		arg.Status,
		arg.OrganizationID,
		arg.OwnerUserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.SpaceID,
			&i.SpaceType,
			&i.Name,
			&i.NormalizedName,
			&i.OwnerUserID,
			&i.OrganizationID,
			&i.RootFolderID,
			&i.QuotaBytes,
			&i.UsedBytes,
			&i.ReservedBytes,
			&i.AclVersion,
			&i.SecurityEpoch,
			&i.ConfigSchemaVersion,
			&i.ConfigJson,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationTreeMutation = `-- name: LockOrganizationTreeMutation :exec
SELECT pg_advisory_xact_lock(hashtextextended('file_workshop:organization_tree', 0))
`

func (q *Queries) LockOrganizationTreeMutation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOrganizationTreeMutation)
	return err
}

const markOrganizationChangeOperation = `-- name: MarkOrganizationChangeOperation :one
UPDATE organization_change_operations
SET status = $2,
    completed_at = $3,
    failure_code = $4,
    updated_at = $3,
    row_version = row_version + 1
WHERE organization_change_operation_id = $1
  AND status = 'PENDING'
RETURNING organization_change_operation_id, organization_change_plan_id, sequence_number, operation_type, source_organization_id, target_organization_id, operation_schema_version, operation_json, status, created_at, updated_at, completed_at, failure_code, row_version
`

type MarkOrganizationChangeOperationParams struct {
	OrganizationChangeOperationID pgtype.UUID
	Status                        string
	CompletedAt                   pgtype.Timestamptz
	FailureCode                   pgtype.Text
}

func (q *Queries) MarkOrganizationChangeOperation(ctx context.Context, arg *MarkOrganizationChangeOperationParams) (*OrganizationChangeOperation, error) {
	row := q.db.QueryRow(ctx, markOrganizationChangeOperation,
		arg.OrganizationChangeOperationID,
		arg.Status,
		arg.CompletedAt,
		arg.FailureCode,
	)
	var i OrganizationChangeOperation
	err := row.Scan(
		&i.OrganizationChangeOperationID,
		&i.OrganizationChangePlanID,
		&i.SequenceNumber,
		&i.OperationType,
		&i.SourceOrganizationID,
		&i.TargetOrganizationID,
		&i.OperationSchemaVersion,
		&i.OperationJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const markQuotaReservationConsumed = `-- name: MarkQuotaReservationConsumed :one
UPDATE quota_reservations
SET status = 'CONSUMED',
    consumed_at = $2,
    updated_at = $2,
    row_version = row_version + 1
WHERE quota_reservation_id = $1
  AND status = 'ACTIVE'
RETURNING quota_reservation_id, space_id, user_id, reserved_bytes, status, expires_at, created_at, updated_at, consumed_at, released_at, row_version
`

type MarkQuotaReservationConsumedParams struct {
	QuotaReservationID pgtype.UUID
	ConsumedAt         pgtype.Timestamptz
}

func (q *Queries) MarkQuotaReservationConsumed(ctx context.Context, arg *MarkQuotaReservationConsumedParams) (*QuotaReservation, error) {
	row := q.db.QueryRow(ctx, markQuotaReservationConsumed, arg.QuotaReservationID, arg.ConsumedAt)
	var i QuotaReservation
	err := row.Scan(
		&i.QuotaReservationID,
		&i.SpaceID,
		&i.UserID,
		&i.ReservedBytes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsumedAt,
		&i.ReleasedAt,
		&i.RowVersion,
	)
	return &i, err
}

const markQuotaReservationReleased = `-- name: MarkQuotaReservationReleased :one
UPDATE quota_reservations
SET status = $2,
    released_at = $3,
    updated_at = $3,
    row_version = row_version + 1
WHERE quota_reservation_id = $1
  AND status = 'ACTIVE'
RETURNING quota_reservation_id, space_id, user_id, reserved_bytes, status, expires_at, created_at, updated_at, consumed_at, released_at, row_version
`

type MarkQuotaReservationReleasedParams struct {
	QuotaReservationID pgtype.UUID
	Status             string
	ReleasedAt         pgtype.Timestamptz
}

func (q *Queries) MarkQuotaReservationReleased(ctx context.Context, arg *MarkQuotaReservationReleasedParams) (*QuotaReservation, error) {
	row := q.db.QueryRow(ctx, markQuotaReservationReleased, arg.QuotaReservationID, arg.Status, arg.ReleasedAt)
	var i QuotaReservation
	err := row.Scan(
		&i.QuotaReservationID,
		&i.SpaceID,
		&i.UserID,
		&i.ReservedBytes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsumedAt,
		&i.ReleasedAt,
		&i.RowVersion,
	)
	return &i, err
}

const organizationDeletionBlocked = `-- name: OrganizationDeletionBlocked :one
SELECT (
    EXISTS (
        SELECT 1 FROM organizations
        WHERE parent_organization_id = $1 AND status <> 'DELETED'
    )
    OR EXISTS (
        SELECT 1 FROM user_organizations
        WHERE organization_id = $1 AND status = 'ACTIVE'
    )
    OR EXISTS (
        SELECT 1 FROM spaces
        WHERE organization_id = $1 AND status <> 'DELETED'
    )
    OR EXISTS (
        SELECT 1 FROM admin_delegations
        WHERE organization_id = $1 AND status = 'ACTIVE'
          AND (valid_until IS NULL OR valid_until > $2)
    )
    OR EXISTS (
        SELECT 1
        FROM migration_jobs AS job
        JOIN spaces AS space ON space.space_id = job.target_space_id
        WHERE space.organization_id = $1
          AND job.status IN ('PENDING', 'RUNNING', 'PAUSED')
    )
    OR EXISTS (
        SELECT 1
        FROM legal_holds AS hold
        JOIN documents AS document ON document.document_id = hold.document_id
        JOIN namespace_entries AS entry ON entry.namespace_entry_id = document.document_id
        JOIN spaces AS space ON space.space_id = entry.space_id
        WHERE space.organization_id = $1 AND hold.status = 'ACTIVE'
    )
)::boolean
`

type OrganizationDeletionBlockedParams struct {
	ParentOrganizationID pgtype.UUID
	ValidUntil           pgtype.Timestamptz
}

func (q *Queries) OrganizationDeletionBlocked(ctx context.Context, arg *OrganizationDeletionBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, organizationDeletionBlocked, arg.ParentOrganizationID, arg.ValidUntil)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const organizationWouldCreateCycle = `-- name: OrganizationWouldCreateCycle :one
SELECT EXISTS (
    SELECT 1
    FROM organization_closure
    WHERE ancestor_organization_id = $1
      AND descendant_organization_id = $2
)::boolean
`

type OrganizationWouldCreateCycleParams struct {
	AncestorOrganizationID   pgtype.UUID
	DescendantOrganizationID pgtype.UUID
}

func (q *Queries) OrganizationWouldCreateCycle(ctx context.Context, arg *OrganizationWouldCreateCycleParams) (bool, error) {
	row := q.db.QueryRow(ctx, organizationWouldCreateCycle, arg.AncestorOrganizationID, arg.DescendantOrganizationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const releaseSpaceQuotaReservation = `-- name: ReleaseSpaceQuotaReservation :execrows
UPDATE spaces
SET reserved_bytes = reserved_bytes - $2,
    updated_at = $3,
    row_version = row_version + 1
WHERE space_id = $1
  AND reserved_bytes >= $2
`

type ReleaseSpaceQuotaReservationParams struct {
	SpaceID       pgtype.UUID
	ReservedBytes int64
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ReleaseSpaceQuotaReservation(ctx context.Context, arg *ReleaseSpaceQuotaReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseSpaceQuotaReservation, arg.SpaceID, arg.ReservedBytes, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveSpaceQuota = `-- name: ReserveSpaceQuota :one
UPDATE spaces
SET reserved_bytes = reserved_bytes + $2,
    updated_at = $3,
    row_version = row_version + 1
WHERE space_id = $1
  AND status = 'ACTIVE'
  AND used_bytes + reserved_bytes + $2 <= quota_bytes
RETURNING space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type ReserveSpaceQuotaParams struct {
	SpaceID       pgtype.UUID
	ReservedBytes int64
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ReserveSpaceQuota(ctx context.Context, arg *ReserveSpaceQuotaParams) (*Space, error) {
	row := q.db.QueryRow(ctx, reserveSpaceQuota, arg.SpaceID, arg.ReservedBytes, arg.UpdatedAt)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const setOrganizationChangePlanStatus = `-- name: SetOrganizationChangePlanStatus :one
UPDATE organization_change_plans
SET status = $1::varchar(32),
    approved_by_user_id = CASE WHEN $1::varchar(32) = 'APPROVED' THEN $2::uuid ELSE approved_by_user_id END,
    validated_at = CASE WHEN $1::varchar(32) = 'VALIDATED' THEN $3::timestamptz ELSE validated_at END,
    approved_at = CASE WHEN $1::varchar(32) = 'APPROVED' THEN $3::timestamptz ELSE approved_at END,
    started_at = CASE WHEN $1::varchar(32) = 'EXECUTING' THEN $3::timestamptz ELSE started_at END,
    completed_at = CASE WHEN $1::varchar(32) = 'COMPLETED' THEN $3::timestamptz ELSE completed_at END,
    failure_code = $4::varchar(64),
    updated_at = $3::timestamptz,
    row_version = row_version + 1
WHERE organization_change_plan_id = $5::uuid
  AND row_version = $6::bigint
RETURNING organization_change_plan_id, plan_type, name, status, expected_tree_version, created_by_user_id, approved_by_user_id, created_at, updated_at, validated_at, approved_at, started_at, completed_at, failure_code, row_version
`

type SetOrganizationChangePlanStatusParams struct {
	Status                   string
	ApprovedByUserID         pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
	FailureCode              pgtype.Text
	OrganizationChangePlanID pgtype.UUID
	RowVersion               int64
}

func (q *Queries) SetOrganizationChangePlanStatus(ctx context.Context, arg *SetOrganizationChangePlanStatusParams) (*OrganizationChangePlan, error) {
	row := q.db.QueryRow(ctx, setOrganizationChangePlanStatus,
		arg.Status,
		arg.ApprovedByUserID,
		arg.UpdatedAt,
		arg.FailureCode,
		arg.OrganizationChangePlanID,
		arg.RowVersion,
	)
	var i OrganizationChangePlan
	err := row.Scan(
		&i.OrganizationChangePlanID,
		&i.PlanType,
		&i.Name,
		&i.Status,
		&i.ExpectedTreeVersion,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ValidatedAt,
		&i.ApprovedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const setOrganizationStatus = `-- name: SetOrganizationStatus :one
UPDATE organizations
SET status = $1::varchar(32),
    deleted_at = CASE WHEN $1::varchar(32) = 'DELETED' THEN $2::timestamptz ELSE NULL END,
    updated_at = $2::timestamptz,
    row_version = row_version + 1
WHERE organization_id = $3::uuid
  AND row_version = $4::bigint
  AND status <> 'DELETED'
RETURNING organization_id, parent_organization_id, name, normalized_name, code, normalized_code, type_label, sort_order, path_cache, depth, tree_version, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type SetOrganizationStatusParams struct {
	Status         string
	UpdatedAt      pgtype.Timestamptz
	OrganizationID pgtype.UUID
	RowVersion     int64
}

func (q *Queries) SetOrganizationStatus(ctx context.Context, arg *SetOrganizationStatusParams) (*Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.RowVersion,
	)
	var i Organization
	err := row.Scan(
		&i.OrganizationID,
		&i.ParentOrganizationID,
		&i.Name,
		&i.NormalizedName,
		&i.Code,
		&i.NormalizedCode,
		&i.TypeLabel,
		&i.SortOrder,
		&i.PathCache,
		&i.Depth,
		&i.TreeVersion,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const setSpaceStatus = `-- name: SetSpaceStatus :one
UPDATE spaces
SET status = $1::varchar(32),
    deleted_at = CASE WHEN $1::varchar(32) = 'DELETED' THEN $2::timestamptz ELSE NULL END,
    security_epoch = security_epoch + 1,
    updated_at = $2::timestamptz,
    row_version = row_version + 1
WHERE space_id = $3::uuid
  AND row_version = $4::bigint
  AND status <> 'DELETED'
RETURNING space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type SetSpaceStatusParams struct {
	Status     string
	UpdatedAt  pgtype.Timestamptz
	SpaceID    pgtype.UUID
	RowVersion int64
}

func (q *Queries) SetSpaceStatus(ctx context.Context, arg *SetSpaceStatusParams) (*Space, error) {
	row := q.db.QueryRow(ctx, setSpaceStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.SpaceID,
		arg.RowVersion,
	)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const spaceDeletionBlocked = `-- name: SpaceDeletionBlocked :one
SELECT (
    EXISTS (SELECT 1 FROM namespace_entries AS entry WHERE entry.space_id = $1)
    OR EXISTS (SELECT 1 FROM quota_reservations AS reservation WHERE reservation.space_id = $1 AND reservation.status = 'ACTIVE')
    OR EXISTS (SELECT 1 FROM migration_jobs AS job WHERE job.target_space_id = $1 AND job.status IN ('PENDING', 'RUNNING', 'PAUSED'))
    OR EXISTS (SELECT 1 FROM retention_policy_targets AS target WHERE target.space_id = $1)
)::boolean
`

func (q *Queries) SpaceDeletionBlocked(ctx context.Context, spaceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, spaceDeletionBlocked, spaceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const touchDraftOrganizationChangePlan = `-- name: TouchDraftOrganizationChangePlan :one
UPDATE organization_change_plans
SET updated_at = $2,
    row_version = row_version + 1
WHERE organization_change_plan_id = $1
  AND status = 'DRAFT'
RETURNING organization_change_plan_id, plan_type, name, status, expected_tree_version, created_by_user_id, approved_by_user_id, created_at, updated_at, validated_at, approved_at, started_at, completed_at, failure_code, row_version
`

type TouchDraftOrganizationChangePlanParams struct {
	OrganizationChangePlanID pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
}

func (q *Queries) TouchDraftOrganizationChangePlan(ctx context.Context, arg *TouchDraftOrganizationChangePlanParams) (*OrganizationChangePlan, error) {
	row := q.db.QueryRow(ctx, touchDraftOrganizationChangePlan, arg.OrganizationChangePlanID, arg.UpdatedAt)
	var i OrganizationChangePlan
	err := row.Scan(
		&i.OrganizationChangePlanID,
		&i.PlanType,
		&i.Name,
		&i.Status,
		&i.ExpectedTreeVersion,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ValidatedAt,
		&i.ApprovedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.RowVersion,
	)
	return &i, err
}

const tryCreateOrganizationIdempotencyRecord = `-- name: TryCreateOrganizationIdempotencyRecord :execrows
INSERT INTO idempotency_records (
    idempotency_record_id, principal_kind, user_id, operation, idempotency_key,
    request_hash, status, expires_at, created_at, updated_at
) VALUES ($1, 'USER', $2, $3, $4, $5, 'IN_PROGRESS', $6, $7, $7)
ON CONFLICT DO NOTHING
`

type TryCreateOrganizationIdempotencyRecordParams struct {
	IdempotencyRecordID pgtype.UUID
	UserID              pgtype.UUID
	Operation           string
	IdempotencyKey      string
	RequestHash         []byte
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) TryCreateOrganizationIdempotencyRecord(ctx context.Context, arg *TryCreateOrganizationIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryCreateOrganizationIdempotencyRecord,
		arg.IdempotencyRecordID,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE user_organizations
SET membership_type = $3,
    job_title = $4,
    status = $5,
    effective_until = $6,
    updated_at = $7,
    row_version = row_version + 1
WHERE user_organization_id = $1
  AND organization_id = $2
  AND row_version = $8
RETURNING user_organization_id, user_id, organization_id, membership_type, job_title, status, effective_from, effective_until, created_by_user_id, created_at, updated_at, row_version
`

type UpdateMembershipParams struct {
	UserOrganizationID pgtype.UUID
	OrganizationID     pgtype.UUID
	MembershipType     string
	JobTitle           pgtype.Text
	Status             string
	EffectiveUntil     pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	RowVersion         int64
}

func (q *Queries) UpdateMembership(ctx context.Context, arg *UpdateMembershipParams) (*UserOrganization, error) {
	row := q.db.QueryRow(ctx, updateMembership,
		arg.UserOrganizationID,
		arg.OrganizationID,
		arg.MembershipType,
		arg.JobTitle,
		arg.Status,
		arg.EffectiveUntil,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i UserOrganization
	err := row.Scan(
		&i.UserOrganizationID,
		&i.UserID,
		&i.OrganizationID,
		&i.MembershipType,
		&i.JobTitle,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const updateMovedOrganizationSubtree = `-- name: UpdateMovedOrganizationSubtree :exec
UPDATE organizations
SET depth = depth + $1::integer,
    parent_organization_id = CASE
        WHEN organization_id = $2::uuid THEN $3::uuid
        ELSE parent_organization_id
    END,
    path_cache = NULL,
    tree_version = tree_version + 1,
    updated_at = $4::timestamptz,
    row_version = row_version + 1
WHERE organization_id IN (
    SELECT descendant_organization_id
    FROM organization_closure
    WHERE ancestor_organization_id = $2::uuid
)
  AND (
    organization_id <> $2::uuid
    OR row_version = $5::bigint
  )
`

type UpdateMovedOrganizationSubtreeParams struct {
	DepthDelta              int32
	OrganizationID          pgtype.UUID
	NewParentOrganizationID pgtype.UUID
	UpdatedAt               pgtype.Timestamptz
	ExpectedRowVersion      int64
}

func (q *Queries) UpdateMovedOrganizationSubtree(ctx context.Context, arg *UpdateMovedOrganizationSubtreeParams) error {
	_, err := q.db.Exec(ctx, updateMovedOrganizationSubtree,
		arg.DepthDelta,
		arg.OrganizationID,
		arg.NewParentOrganizationID,
		arg.UpdatedAt,
		arg.ExpectedRowVersion,
	)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2,
    normalized_name = $3,
    code = $4,
    normalized_code = $5,
    type_label = $6,
    sort_order = $7,
    updated_at = $8,
    row_version = row_version + 1
WHERE organization_id = $1
  AND row_version = $9
  AND status <> 'DELETED'
RETURNING organization_id, parent_organization_id, name, normalized_name, code, normalized_code, type_label, sort_order, path_cache, depth, tree_version, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type UpdateOrganizationParams struct {
	OrganizationID pgtype.UUID
	Name           string
	NormalizedName string
	Code           pgtype.Text
	NormalizedCode pgtype.Text
	TypeLabel      pgtype.Text
	SortOrder      int32
	UpdatedAt      pgtype.Timestamptz
	RowVersion     int64
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg *UpdateOrganizationParams) (*Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.OrganizationID,
		arg.Name,
		arg.NormalizedName,
		arg.Code,
		arg.NormalizedCode,
		arg.TypeLabel,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i Organization
	err := row.Scan(
		&i.OrganizationID,
		&i.ParentOrganizationID,
		&i.Name,
		&i.NormalizedName,
		&i.Code,
		&i.NormalizedCode,
		&i.TypeLabel,
		&i.SortOrder,
		&i.PathCache,
		&i.Depth,
		&i.TreeVersion,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces
SET name = $2,
    normalized_name = $3,
    quota_bytes = $4,
    config_schema_version = $5,
    config_json = $6,
    updated_at = $7,
    row_version = row_version + 1
WHERE space_id = $1
  AND row_version = $8
  AND status <> 'DELETED'
  AND used_bytes + reserved_bytes <= $4
RETURNING space_id, space_type, name, normalized_name, owner_user_id, organization_id, root_folder_id, quota_bytes, used_bytes, reserved_bytes, acl_version, security_epoch, config_schema_version, config_json, status, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type UpdateSpaceParams struct {
	SpaceID             pgtype.UUID
	Name                string
	NormalizedName      string
	QuotaBytes          int64
	ConfigSchemaVersion int32
	ConfigJson          []byte
	UpdatedAt           pgtype.Timestamptz
	RowVersion          int64
}

func (q *Queries) UpdateSpace(ctx context.Context, arg *UpdateSpaceParams) (*Space, error) {
	row := q.db.QueryRow(ctx, updateSpace,
		arg.SpaceID,
		arg.Name,
		arg.NormalizedName,
		arg.QuotaBytes,
		arg.ConfigSchemaVersion,
		arg.ConfigJson,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i Space
	err := row.Scan(
		&i.SpaceID,
		&i.SpaceType,
		&i.Name,
		&i.NormalizedName,
		&i.OwnerUserID,
		&i.OrganizationID,
		&i.RootFolderID,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.ReservedBytes,
		&i.AclVersion,
		&i.SecurityEpoch,
		&i.ConfigSchemaVersion,
		&i.ConfigJson,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const userCanJoinOrganization = `-- name: UserCanJoinOrganization :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE user_id = $1 AND status = 'ACTIVE'
) AND EXISTS (
    SELECT 1 FROM organizations
    WHERE organization_id = $2 AND status = 'ACTIVE'
) AS allowed
`

type UserCanJoinOrganizationParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) UserCanJoinOrganization(ctx context.Context, arg *UserCanJoinOrganizationParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, userCanJoinOrganization, arg.UserID, arg.OrganizationID)
	var allowed pgtype.Bool
	err := row.Scan(&allowed)
	return allowed, err
}

const userExistsAndIsActive = `-- name: UserExistsAndIsActive :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE user_id = $1 AND status = 'ACTIVE'
)::boolean
`

func (q *Queries) UserExistsAndIsActive(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsAndIsActive, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
