// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_shares.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCandidateShareGrants = `-- name: ListCandidateShareGrants :many
SELECT s.share_id, COALESCE(array_agg(a.action ORDER BY a.action), ARRAY[]::varchar[])::text[] AS actions
FROM shares s
JOIN share_actions a ON a.share_id = s.share_id
WHERE s.status = 'ACTIVE'
  AND s.valid_from <= $1::timestamptz
  AND (s.valid_until IS NULL OR s.valid_until > $1)
  AND s.target_kind IN ('USER', 'ORGANIZATION')
  AND (
    s.target_user_id = $2::uuid
    OR s.target_organization_id = ANY($3::uuid[])
  )
  AND (
    s.source_document_id = $4::uuid
    OR s.source_folder_id = ANY($5::uuid[])
  )
GROUP BY s.share_id
ORDER BY s.created_at, s.share_id
`

type ListCandidateShareGrantsParams struct {
	EffectiveAt     pgtype.Timestamptz
	UserID          pgtype.UUID
	OrganizationIds []pgtype.UUID
	DocumentID      pgtype.UUID
	FolderIds       []pgtype.UUID
}

type ListCandidateShareGrantsRow struct {
	ShareID pgtype.UUID
	Actions []string
}

func (q *Queries) ListCandidateShareGrants(ctx context.Context, arg *ListCandidateShareGrantsParams) ([]*ListCandidateShareGrantsRow, error) {
	rows, err := q.db.Query(ctx, listCandidateShareGrants,
		arg.EffectiveAt,
		arg.UserID,
		arg.OrganizationIds,
		arg.DocumentID,
		arg.FolderIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListCandidateShareGrantsRow{}
	for rows.Next() {
		var i ListCandidateShareGrantsRow
		if err := rows.Scan(&i.ShareID, &i.Actions); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
