// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminDelegationIsEffective(ctx context.Context, arg *AdminDelegationIsEffectiveParams) (bool, error)
	ChangeDocumentInheritance(ctx context.Context, arg *ChangeDocumentInheritanceParams) (*ChangeDocumentInheritanceRow, error)
	ChangeFolderInheritance(ctx context.Context, arg *ChangeFolderInheritanceParams) (*ChangeFolderInheritanceRow, error)
	CompleteFileIdempotencyRecord(ctx context.Context, arg *CompleteFileIdempotencyRecordParams) error
	CompleteOrganizationIdempotencyRecord(ctx context.Context, arg *CompleteOrganizationIdempotencyRecordParams) error
	CompletePermissionIdempotency(ctx context.Context, arg *CompletePermissionIdempotencyParams) error
	CompleteUserIdempotencyRecord(ctx context.Context, arg *CompleteUserIdempotencyRecordParams) error
	ConsumeSpaceQuotaReservation(ctx context.Context, arg *ConsumeSpaceQuotaReservationParams) (int64, error)
	CountDirectPermissionGrants(ctx context.Context, arg *CountDirectPermissionGrantsParams) (int64, error)
	CountFileChildEntries(ctx context.Context, arg *CountFileChildEntriesParams) (int64, error)
	CountManagedUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountManagedUsers(ctx context.Context, arg *CountManagedUsersParams) (int64, error)
	CountMemberships(ctx context.Context, arg *CountMembershipsParams) (int64, error)
	CountOrganizationAdministrators(ctx context.Context, arg *CountOrganizationAdministratorsParams) (int64, error)
	CountOrganizationChangePlans(ctx context.Context, status pgtype.Text) (int64, error)
	CountOrganizationRowVersion(ctx context.Context, arg *CountOrganizationRowVersionParams) (int64, error)
	CountOrganizations(ctx context.Context, arg *CountOrganizationsParams) (int64, error)
	CountSpaces(ctx context.Context, arg *CountSpacesParams) (int64, error)
	CountVisibleAdminDelegations(ctx context.Context, arg *CountVisibleAdminDelegationsParams) (int64, error)
	CreateSessionRefreshToken(ctx context.Context, arg *CreateSessionRefreshTokenParams) (*CreateSessionRefreshTokenRow, error)
	CreateUserSession(ctx context.Context, arg *CreateUserSessionParams) (*CreateUserSessionRow, error)
	DeactivateMembership(ctx context.Context, arg *DeactivateMembershipParams) (*UserOrganization, error)
	DeleteOrganizationExternalClosureLinks(ctx context.Context, ancestorOrganizationID pgtype.UUID) error
	DeletePermissionGrantActions(ctx context.Context, permissionGrantID pgtype.UUID) error
	FileFolderIsDescendantOf(ctx context.Context, arg *FileFolderIsDescendantOfParams) (bool, error)
	FindEffectiveAdminDelegation(ctx context.Context, arg *FindEffectiveAdminDelegationParams) (*FindEffectiveAdminDelegationRow, error)
	GetAdminDelegationWithCapabilities(ctx context.Context, adminDelegationID pgtype.UUID) (*GetAdminDelegationWithCapabilitiesRow, error)
	GetAdminDelegationWithCapabilitiesForUpdate(ctx context.Context, adminDelegationID pgtype.UUID) (*GetAdminDelegationWithCapabilitiesForUpdateRow, error)
	GetCurrentSessionIdentity(ctx context.Context, userSessionID pgtype.UUID) (*GetCurrentSessionIdentityRow, error)
	GetDatabaseHealth(ctx context.Context) (*GetDatabaseHealthRow, error)
	GetDocumentAuthorizationResource(ctx context.Context, documentID pgtype.UUID) (*GetDocumentAuthorizationResourceRow, error)
	GetFileIdempotencyRecord(ctx context.Context, arg *GetFileIdempotencyRecordParams) (*GetFileIdempotencyRecordRow, error)
	GetFileNamespaceEntry(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetFileNamespaceEntryRow, error)
	GetFileNamespaceEntryForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetFileNamespaceEntryForUpdateRow, error)
	GetFileSpaceDirectoryInfo(ctx context.Context, spaceID pgtype.UUID) (*GetFileSpaceDirectoryInfoRow, error)
	GetFileSpaceDirectoryInfoForUpdate(ctx context.Context, spaceID pgtype.UUID) (*GetFileSpaceDirectoryInfoForUpdateRow, error)
	GetFolderAuthorizationResource(ctx context.Context, folderID pgtype.UUID) (*GetFolderAuthorizationResourceRow, error)
	GetManagedUserByID(ctx context.Context, userID pgtype.UUID) (*GetManagedUserByIDRow, error)
	GetManagedUserForUpdate(ctx context.Context, userID pgtype.UUID) (*GetManagedUserForUpdateRow, error)
	GetMembership(ctx context.Context, userOrganizationID pgtype.UUID) (*UserOrganization, error)
	GetMembershipForUpdate(ctx context.Context, arg *GetMembershipForUpdateParams) (*UserOrganization, error)
	GetOrganization(ctx context.Context, organizationID pgtype.UUID) (*Organization, error)
	GetOrganizationChangePlan(ctx context.Context, organizationChangePlanID pgtype.UUID) (*OrganizationChangePlan, error)
	GetOrganizationChangePlanForUpdate(ctx context.Context, organizationChangePlanID pgtype.UUID) (*OrganizationChangePlan, error)
	GetOrganizationForUpdate(ctx context.Context, organizationID pgtype.UUID) (*Organization, error)
	GetOrganizationIdempotencyRecordForUpdate(ctx context.Context, arg *GetOrganizationIdempotencyRecordForUpdateParams) (*GetOrganizationIdempotencyRecordForUpdateRow, error)
	GetOrganizationSpace(ctx context.Context, organizationID pgtype.UUID) (*Space, error)
	GetOwnedUserSession(ctx context.Context, arg *GetOwnedUserSessionParams) (pgtype.UUID, error)
	GetPasswordLoginIdentity(ctx context.Context, arg *GetPasswordLoginIdentityParams) (*GetPasswordLoginIdentityRow, error)
	GetPermissionAuthorizationVersion(ctx context.Context, arg *GetPermissionAuthorizationVersionParams) (string, error)
	GetPermissionGrantWithActions(ctx context.Context, permissionGrantID pgtype.UUID) (*GetPermissionGrantWithActionsRow, error)
	GetPermissionGrantWithActionsForUpdate(ctx context.Context, permissionGrantID pgtype.UUID) (*GetPermissionGrantWithActionsForUpdateRow, error)
	GetPermissionIdempotency(ctx context.Context, arg *GetPermissionIdempotencyParams) (*GetPermissionIdempotencyRow, error)
	GetPersonalSpaceByUser(ctx context.Context, ownerUserID pgtype.UUID) (*Space, error)
	GetQuotaReservationForUpdate(ctx context.Context, quotaReservationID pgtype.UUID) (*QuotaReservation, error)
	GetRecentLoginFailureState(ctx context.Context, arg *GetRecentLoginFailureStateParams) (*GetRecentLoginFailureStateRow, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (*GetRefreshTokenForUpdateRow, error)
	GetSessionIDByRefreshTokenHash(ctx context.Context, tokenHash []byte) (pgtype.UUID, error)
	GetSpace(ctx context.Context, spaceID pgtype.UUID) (*Space, error)
	GetSpaceAuthorizationResource(ctx context.Context, spaceID pgtype.UUID) (*GetSpaceAuthorizationResourceRow, error)
	GetSpaceForUpdate(ctx context.Context, spaceID pgtype.UUID) (*Space, error)
	GetUserIdempotencyRecordForUpdate(ctx context.Context, arg *GetUserIdempotencyRecordForUpdateParams) (*GetUserIdempotencyRecordForUpdateRow, error)
	IncrementDocumentACLVersion(ctx context.Context, arg *IncrementDocumentACLVersionParams) error
	IncrementFolderACLVersion(ctx context.Context, arg *IncrementFolderACLVersionParams) error
	IncrementGlobalAuthorizationVersion(ctx context.Context, arg *IncrementGlobalAuthorizationVersionParams) error
	IncrementOrganizationDelegationVersion(ctx context.Context, arg *IncrementOrganizationDelegationVersionParams) error
	IncrementOrganizationGrantVersion(ctx context.Context, arg *IncrementOrganizationGrantVersionParams) error
	IncrementOrganizationMembershipVersion(ctx context.Context, arg *IncrementOrganizationMembershipVersionParams) error
	IncrementOrganizationSubtreeSecurityEpochs(ctx context.Context, arg *IncrementOrganizationSubtreeSecurityEpochsParams) error
	IncrementPrincipalDelegationVersion(ctx context.Context, arg *IncrementPrincipalDelegationVersionParams) error
	IncrementPrincipalGrantVersion(ctx context.Context, arg *IncrementPrincipalGrantVersionParams) error
	IncrementSpaceACLVersion(ctx context.Context, arg *IncrementSpaceACLVersionParams) error
	IncrementUserOrganizationMembershipVersion(ctx context.Context, arg *IncrementUserOrganizationMembershipVersionParams) error
	InsertAdminDelegation(ctx context.Context, arg *InsertAdminDelegationParams) (*AdminDelegation, error)
	InsertAdminDelegationCapability(ctx context.Context, arg *InsertAdminDelegationCapabilityParams) error
	InsertFileDocument(ctx context.Context, arg *InsertFileDocumentParams) (*Document, error)
	InsertFileFolder(ctx context.Context, arg *InsertFileFolderParams) error
	InsertFileNamespaceEntry(ctx context.Context, arg *InsertFileNamespaceEntryParams) (*NamespaceEntry, error)
	InsertFileOutboxEvent(ctx context.Context, arg *InsertFileOutboxEventParams) error
	InsertLoginAttempt(ctx context.Context, arg *InsertLoginAttemptParams) error
	InsertManagedPasswordCredential(ctx context.Context, arg *InsertManagedPasswordCredentialParams) error
	InsertManagedUser(ctx context.Context, arg *InsertManagedUserParams) (*InsertManagedUserRow, error)
	InsertMembership(ctx context.Context, arg *InsertMembershipParams) (*UserOrganization, error)
	InsertMovedOrganizationClosureLinks(ctx context.Context, arg *InsertMovedOrganizationClosureLinksParams) error
	InsertOrganization(ctx context.Context, arg *InsertOrganizationParams) (*Organization, error)
	InsertOrganizationChangeOperation(ctx context.Context, arg *InsertOrganizationChangeOperationParams) (*OrganizationChangeOperation, error)
	InsertOrganizationChangePlan(ctx context.Context, arg *InsertOrganizationChangePlanParams) (*OrganizationChangePlan, error)
	InsertOrganizationClosure(ctx context.Context, arg *InsertOrganizationClosureParams) error
	InsertOrganizationOutboxEvent(ctx context.Context, arg *InsertOrganizationOutboxEventParams) error
	InsertOrganizationSecurityVersions(ctx context.Context, arg *InsertOrganizationSecurityVersionsParams) error
	InsertPermissionGrant(ctx context.Context, arg *InsertPermissionGrantParams) (*PermissionGrant, error)
	InsertPermissionGrantAction(ctx context.Context, arg *InsertPermissionGrantActionParams) error
	InsertPermissionOutboxEvent(ctx context.Context, arg *InsertPermissionOutboxEventParams) error
	InsertPrincipalSecurityVersions(ctx context.Context, arg *InsertPrincipalSecurityVersionsParams) error
	InsertQuotaReservation(ctx context.Context, arg *InsertQuotaReservationParams) (*QuotaReservation, error)
	InsertSpace(ctx context.Context, arg *InsertSpaceParams) (*Space, error)
	InsertUserOutboxEvent(ctx context.Context, arg *InsertUserOutboxEventParams) error
	InvalidateDescendantAdminDelegations(ctx context.Context, arg *InvalidateDescendantAdminDelegationsParams) ([]pgtype.UUID, error)
	ListActivePermissionUserOrganizations(ctx context.Context, arg *ListActivePermissionUserOrganizationsParams) ([]pgtype.UUID, error)
	ListCandidatePermissionGrants(ctx context.Context, arg *ListCandidatePermissionGrantsParams) ([]*ListCandidatePermissionGrantsRow, error)
	ListDirectPermissionGrants(ctx context.Context, arg *ListDirectPermissionGrantsParams) ([]*ListDirectPermissionGrantsRow, error)
	ListFileChildEntries(ctx context.Context, arg *ListFileChildEntriesParams) ([]*ListFileChildEntriesRow, error)
	ListFolderAuthorizationAncestors(ctx context.Context, resourceID pgtype.UUID) ([]*ListFolderAuthorizationAncestorsRow, error)
	ListManagedUserSessions(ctx context.Context, arg *ListManagedUserSessionsParams) ([]*UserSession, error)
	ListManagedUsers(ctx context.Context, arg *ListManagedUsersParams) ([]*ListManagedUsersRow, error)
	ListMemberships(ctx context.Context, arg *ListMembershipsParams) ([]*UserOrganization, error)
	ListOrganizationAdministrators(ctx context.Context, arg *ListOrganizationAdministratorsParams) ([]*ListOrganizationAdministratorsRow, error)
	ListOrganizationChangeOperations(ctx context.Context, organizationChangePlanID pgtype.UUID) ([]*OrganizationChangeOperation, error)
	ListOrganizationChangePlans(ctx context.Context, arg *ListOrganizationChangePlansParams) ([]*OrganizationChangePlan, error)
	ListOrganizations(ctx context.Context, arg *ListOrganizationsParams) ([]*Organization, error)
	ListSpaces(ctx context.Context, arg *ListSpacesParams) ([]*Space, error)
	ListVisibleAdminDelegations(ctx context.Context, arg *ListVisibleAdminDelegationsParams) ([]*ListVisibleAdminDelegationsRow, error)
	LockActiveSystemAdministrators(ctx context.Context) ([]pgtype.UUID, error)
	LockOrganizationTreeMutation(ctx context.Context) error
	LockSystemAdminMutation(ctx context.Context) error
	MarkOrganizationChangeOperation(ctx context.Context, arg *MarkOrganizationChangeOperationParams) (*OrganizationChangeOperation, error)
	MarkQuotaReservationConsumed(ctx context.Context, arg *MarkQuotaReservationConsumedParams) (*QuotaReservation, error)
	MarkQuotaReservationReleased(ctx context.Context, arg *MarkQuotaReservationReleasedParams) (*QuotaReservation, error)
	MarkRefreshTokenReused(ctx context.Context, arg *MarkRefreshTokenReusedParams) error
	MarkRefreshTokenUsed(ctx context.Context, arg *MarkRefreshTokenUsedParams) (int64, error)
	MoveFileNamespaceEntry(ctx context.Context, arg *MoveFileNamespaceEntryParams) (*NamespaceEntry, error)
	OrganizationDeletionBlocked(ctx context.Context, arg *OrganizationDeletionBlockedParams) (bool, error)
	OrganizationWouldCreateCycle(ctx context.Context, arg *OrganizationWouldCreateCycleParams) (bool, error)
	PermissionOrganizationExists(ctx context.Context, organizationID pgtype.UUID) (bool, error)
	ReleaseSpaceQuotaReservation(ctx context.Context, arg *ReleaseSpaceQuotaReservationParams) (int64, error)
	RenameFileNamespaceEntry(ctx context.Context, arg *RenameFileNamespaceEntryParams) (*NamespaceEntry, error)
	ReserveSpaceQuota(ctx context.Context, arg *ReserveSpaceQuotaParams) (*Space, error)
	RevokeActiveRefreshTokensForSession(ctx context.Context, arg *RevokeActiveRefreshTokensForSessionParams) error
	RevokeAdminDelegation(ctx context.Context, arg *RevokeAdminDelegationParams) (*AdminDelegation, error)
	RevokeManagedUserCredentials(ctx context.Context, arg *RevokeManagedUserCredentialsParams) error
	RevokeManagedUserRefreshTokens(ctx context.Context, arg *RevokeManagedUserRefreshTokensParams) error
	RevokeManagedUserSessions(ctx context.Context, arg *RevokeManagedUserSessionsParams) error
	RevokeOwnedUserSession(ctx context.Context, arg *RevokeOwnedUserSessionParams) (int64, error)
	RevokeOwnedUserSessionTokens(ctx context.Context, arg *RevokeOwnedUserSessionTokensParams) error
	RevokePermissionGrant(ctx context.Context, arg *RevokePermissionGrantParams) (*PermissionGrant, error)
	RevokeUserSession(ctx context.Context, arg *RevokeUserSessionParams) error
	SetManagedUserStatus(ctx context.Context, arg *SetManagedUserStatusParams) (*SetManagedUserStatusRow, error)
	SetOrganizationChangePlanStatus(ctx context.Context, arg *SetOrganizationChangePlanStatusParams) (*OrganizationChangePlan, error)
	SetOrganizationStatus(ctx context.Context, arg *SetOrganizationStatusParams) (*Organization, error)
	SetSpaceStatus(ctx context.Context, arg *SetSpaceStatusParams) (*Space, error)
	SpaceDeletionBlocked(ctx context.Context, spaceID pgtype.UUID) (bool, error)
	TouchCredentialAfterLogin(ctx context.Context, arg *TouchCredentialAfterLoginParams) error
	TouchDraftOrganizationChangePlan(ctx context.Context, arg *TouchDraftOrganizationChangePlanParams) (*OrganizationChangePlan, error)
	TouchFileSpaceSecurityEpoch(ctx context.Context, arg *TouchFileSpaceSecurityEpochParams) error
	TouchManagedUserForPasswordReset(ctx context.Context, arg *TouchManagedUserForPasswordResetParams) (int64, error)
	TouchUserAfterLogin(ctx context.Context, arg *TouchUserAfterLoginParams) error
	TouchUserSession(ctx context.Context, arg *TouchUserSessionParams) error
	TryCreateFileIdempotencyRecord(ctx context.Context, arg *TryCreateFileIdempotencyRecordParams) (int64, error)
	TryCreateOrganizationIdempotencyRecord(ctx context.Context, arg *TryCreateOrganizationIdempotencyRecordParams) (int64, error)
	TryCreatePermissionIdempotency(ctx context.Context, arg *TryCreatePermissionIdempotencyParams) (int64, error)
	TryCreateUserIdempotencyRecord(ctx context.Context, arg *TryCreateUserIdempotencyRecordParams) (int64, error)
	UpdateFileDescendantPaths(ctx context.Context, arg *UpdateFileDescendantPathsParams) error
	UpdateFileDocumentExtension(ctx context.Context, arg *UpdateFileDocumentExtensionParams) error
	UpdateFileSpaceRootFolder(ctx context.Context, arg *UpdateFileSpaceRootFolderParams) error
	UpdateManagedPasswordCredential(ctx context.Context, arg *UpdateManagedPasswordCredentialParams) (int64, error)
	UpdateManagedUser(ctx context.Context, arg *UpdateManagedUserParams) (*UpdateManagedUserRow, error)
	UpdateMembership(ctx context.Context, arg *UpdateMembershipParams) (*UserOrganization, error)
	UpdateMovedOrganizationSubtree(ctx context.Context, arg *UpdateMovedOrganizationSubtreeParams) error
	UpdateOrganization(ctx context.Context, arg *UpdateOrganizationParams) (*Organization, error)
	UpdatePermissionGrant(ctx context.Context, arg *UpdatePermissionGrantParams) (*PermissionGrant, error)
	UpdateSpace(ctx context.Context, arg *UpdateSpaceParams) (*Space, error)
	UserCanJoinOrganization(ctx context.Context, arg *UserCanJoinOrganizationParams) (pgtype.Bool, error)
	UserExistsAndIsActive(ctx context.Context, userID pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
