// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbortUploadSession(ctx context.Context, arg *AbortUploadSessionParams) (*UploadSession, error)
	ActiveLegalHoldExistsForEntrySubtree(ctx context.Context, namespaceEntryID pgtype.UUID) (bool, error)
	AdminDelegationIsEffective(ctx context.Context, arg *AdminDelegationIsEffectiveParams) (bool, error)
	CancelBackgroundJob(ctx context.Context, arg *CancelBackgroundJobParams) (*BackgroundJob, error)
	ChangeDocumentInheritance(ctx context.Context, arg *ChangeDocumentInheritanceParams) (*ChangeDocumentInheritanceRow, error)
	ChangeFolderInheritance(ctx context.Context, arg *ChangeFolderInheritanceParams) (*ChangeFolderInheritanceRow, error)
	ClaimBackgroundJobsByType(ctx context.Context, arg *ClaimBackgroundJobsByTypeParams) ([]*BackgroundJob, error)
	ClaimOutboxEventsByType(ctx context.Context, arg *ClaimOutboxEventsByTypeParams) ([]*OutboxEvent, error)
	CompleteFileIdempotencyRecord(ctx context.Context, arg *CompleteFileIdempotencyRecordParams) error
	CompleteLifecycleIdempotency(ctx context.Context, arg *CompleteLifecycleIdempotencyParams) error
	CompleteOrganizationIdempotencyRecord(ctx context.Context, arg *CompleteOrganizationIdempotencyRecordParams) error
	CompletePermissionIdempotency(ctx context.Context, arg *CompletePermissionIdempotencyParams) error
	CompleteShareIdempotency(ctx context.Context, arg *CompleteShareIdempotencyParams) error
	CompleteUserIdempotencyRecord(ctx context.Context, arg *CompleteUserIdempotencyRecordParams) error
	ConsumeSpaceQuotaReservation(ctx context.Context, arg *ConsumeSpaceQuotaReservationParams) (int64, error)
	CountAuditChainHeads(ctx context.Context, arg *CountAuditChainHeadsParams) (int64, error)
	CountAuditChainHeadsByStatus(ctx context.Context, arg *CountAuditChainHeadsByStatusParams) ([]*CountAuditChainHeadsByStatusRow, error)
	CountAuditEvents(ctx context.Context, arg *CountAuditEventsParams) (int64, error)
	CountAuditEventsByActorType(ctx context.Context, arg *CountAuditEventsByActorTypeParams) ([]*CountAuditEventsByActorTypeRow, error)
	CountAuditEventsByEventType(ctx context.Context, arg *CountAuditEventsByEventTypeParams) ([]*CountAuditEventsByEventTypeRow, error)
	CountAuditEventsByFailureCode(ctx context.Context, arg *CountAuditEventsByFailureCodeParams) ([]*CountAuditEventsByFailureCodeRow, error)
	CountAuditEventsByResourceType(ctx context.Context, arg *CountAuditEventsByResourceTypeParams) ([]*CountAuditEventsByResourceTypeRow, error)
	CountAuditEventsByResult(ctx context.Context, arg *CountAuditEventsByResultParams) ([]*CountAuditEventsByResultRow, error)
	CountAuditEventsByRiskLevel(ctx context.Context, arg *CountAuditEventsByRiskLevelParams) ([]*CountAuditEventsByRiskLevelRow, error)
	CountBackgroundJobFailuresByErrorCode(ctx context.Context) ([]*CountBackgroundJobFailuresByErrorCodeRow, error)
	CountBackgroundJobs(ctx context.Context, arg *CountBackgroundJobsParams) (int64, error)
	CountBackgroundJobsByStatus(ctx context.Context) ([]*CountBackgroundJobsByStatusRow, error)
	CountCreatedShares(ctx context.Context, creatorUserID pgtype.UUID) (int64, error)
	CountDirectPermissionGrants(ctx context.Context, arg *CountDirectPermissionGrantsParams) (int64, error)
	CountDocumentVersions(ctx context.Context, documentID pgtype.UUID) (int64, error)
	CountFileChildEntries(ctx context.Context, arg *CountFileChildEntriesParams) (int64, error)
	CountManagedUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountManagedUsers(ctx context.Context, arg *CountManagedUsersParams) (int64, error)
	CountMemberships(ctx context.Context, arg *CountMembershipsParams) (int64, error)
	CountOrganizationAdministrators(ctx context.Context, arg *CountOrganizationAdministratorsParams) (int64, error)
	CountOrganizationChangePlans(ctx context.Context, status pgtype.Text) (int64, error)
	CountOrganizationRowVersion(ctx context.Context, arg *CountOrganizationRowVersionParams) (int64, error)
	CountOrganizations(ctx context.Context, arg *CountOrganizationsParams) (int64, error)
	CountOutboxEvents(ctx context.Context, arg *CountOutboxEventsParams) (int64, error)
	CountOutboxEventsByStatus(ctx context.Context) ([]*CountOutboxEventsByStatusRow, error)
	CountOutboxFailuresByErrorCode(ctx context.Context) ([]*CountOutboxFailuresByErrorCodeRow, error)
	CountPreservationHolds(ctx context.Context, arg *CountPreservationHoldsParams) (int64, error)
	CountReceivedShares(ctx context.Context, arg *CountReceivedSharesParams) (int64, error)
	CountRecycleItems(ctx context.Context, spaceID pgtype.UUID) (int64, error)
	CountSpaces(ctx context.Context, arg *CountSpacesParams) (int64, error)
	CountVisibleAdminDelegations(ctx context.Context, arg *CountVisibleAdminDelegationsParams) (int64, error)
	CreateSessionRefreshToken(ctx context.Context, arg *CreateSessionRefreshTokenParams) (*CreateSessionRefreshTokenRow, error)
	CreateUserSession(ctx context.Context, arg *CreateUserSessionParams) (*CreateUserSessionRow, error)
	DeactivateMembership(ctx context.Context, arg *DeactivateMembershipParams) (*UserOrganization, error)
	DeleteOrganizationExternalClosureLinks(ctx context.Context, ancestorOrganizationID pgtype.UUID) error
	DeletePermissionGrantActions(ctx context.Context, permissionGrantID pgtype.UUID) error
	DeleteShareActions(ctx context.Context, shareID pgtype.UUID) error
	EnsureDocumentLockCounter(ctx context.Context, arg *EnsureDocumentLockCounterParams) error
	ExpireDocumentLocks(ctx context.Context, arg *ExpireDocumentLocksParams) error
	ExpireShares(ctx context.Context, updatedAt pgtype.Timestamptz) error
	FileFolderIsDescendantOf(ctx context.Context, arg *FileFolderIsDescendantOfParams) (bool, error)
	FindEffectiveAdminDelegation(ctx context.Context, arg *FindEffectiveAdminDelegationParams) (*FindEffectiveAdminDelegationRow, error)
	ForceReleaseDocumentLock(ctx context.Context, arg *ForceReleaseDocumentLockParams) (*DocumentLock, error)
	GetActiveDocumentLock(ctx context.Context, documentID pgtype.UUID) (*DocumentLock, error)
	GetActiveDocumentLockForUpdate(ctx context.Context, documentID pgtype.UUID) (*DocumentLock, error)
	GetAdminDelegationWithCapabilities(ctx context.Context, adminDelegationID pgtype.UUID) (*GetAdminDelegationWithCapabilitiesRow, error)
	GetAdminDelegationWithCapabilitiesForUpdate(ctx context.Context, adminDelegationID pgtype.UUID) (*GetAdminDelegationWithCapabilitiesForUpdateRow, error)
	GetAuditChainHeadForUpdate(ctx context.Context, arg *GetAuditChainHeadForUpdateParams) (*AuditChainHead, error)
	GetAuditEvent(ctx context.Context, arg *GetAuditEventParams) (*GetAuditEventRow, error)
	GetBackgroundJob(ctx context.Context, backgroundJobID pgtype.UUID) (*BackgroundJob, error)
	GetCurrentSessionIdentity(ctx context.Context, userSessionID pgtype.UUID) (*GetCurrentSessionIdentityRow, error)
	GetDatabaseHealth(ctx context.Context) (*GetDatabaseHealthRow, error)
	GetDocumentAuthorizationResource(ctx context.Context, documentID pgtype.UUID) (*GetDocumentAuthorizationResourceRow, error)
	GetDocumentVersion(ctx context.Context, arg *GetDocumentVersionParams) (*DocumentVersion, error)
	GetFileIdempotencyRecord(ctx context.Context, arg *GetFileIdempotencyRecordParams) (*GetFileIdempotencyRecordRow, error)
	GetFileNamespaceEntry(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetFileNamespaceEntryRow, error)
	GetFileNamespaceEntryForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetFileNamespaceEntryForUpdateRow, error)
	GetFileSpaceDirectoryInfo(ctx context.Context, spaceID pgtype.UUID) (*GetFileSpaceDirectoryInfoRow, error)
	GetFileSpaceDirectoryInfoForUpdate(ctx context.Context, spaceID pgtype.UUID) (*GetFileSpaceDirectoryInfoForUpdateRow, error)
	GetFolderAuthorizationResource(ctx context.Context, folderID pgtype.UUID) (*GetFolderAuthorizationResourceRow, error)
	GetLifecycleDocumentRef(ctx context.Context, documentID pgtype.UUID) (*GetLifecycleDocumentRefRow, error)
	GetLifecycleEntryForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetLifecycleEntryForUpdateRow, error)
	GetLifecycleFolderForUpdate(ctx context.Context, namespaceEntryID pgtype.UUID) (*GetLifecycleFolderForUpdateRow, error)
	GetLifecycleIdempotency(ctx context.Context, arg *GetLifecycleIdempotencyParams) (*GetLifecycleIdempotencyRow, error)
	GetManagedUserByID(ctx context.Context, userID pgtype.UUID) (*GetManagedUserByIDRow, error)
	GetManagedUserForUpdate(ctx context.Context, userID pgtype.UUID) (*GetManagedUserForUpdateRow, error)
	GetMembership(ctx context.Context, userOrganizationID pgtype.UUID) (*UserOrganization, error)
	GetMembershipForUpdate(ctx context.Context, arg *GetMembershipForUpdateParams) (*UserOrganization, error)
	GetOrganization(ctx context.Context, organizationID pgtype.UUID) (*Organization, error)
	GetOrganizationChangePlan(ctx context.Context, organizationChangePlanID pgtype.UUID) (*OrganizationChangePlan, error)
	GetOrganizationChangePlanForUpdate(ctx context.Context, organizationChangePlanID pgtype.UUID) (*OrganizationChangePlan, error)
	GetOrganizationForUpdate(ctx context.Context, organizationID pgtype.UUID) (*Organization, error)
	GetOrganizationIdempotencyRecordForUpdate(ctx context.Context, arg *GetOrganizationIdempotencyRecordForUpdateParams) (*GetOrganizationIdempotencyRecordForUpdateRow, error)
	GetOrganizationSpace(ctx context.Context, organizationID pgtype.UUID) (*Space, error)
	GetOutboxEvent(ctx context.Context, outboxEventID pgtype.UUID) (*OutboxEvent, error)
	GetOwnedUserSession(ctx context.Context, arg *GetOwnedUserSessionParams) (pgtype.UUID, error)
	GetPasswordLoginIdentity(ctx context.Context, arg *GetPasswordLoginIdentityParams) (*GetPasswordLoginIdentityRow, error)
	GetPermissionAuthorizationVersion(ctx context.Context, arg *GetPermissionAuthorizationVersionParams) (string, error)
	GetPermissionGrantWithActions(ctx context.Context, permissionGrantID pgtype.UUID) (*GetPermissionGrantWithActionsRow, error)
	GetPermissionGrantWithActionsForUpdate(ctx context.Context, permissionGrantID pgtype.UUID) (*GetPermissionGrantWithActionsForUpdateRow, error)
	GetPermissionIdempotency(ctx context.Context, arg *GetPermissionIdempotencyParams) (*GetPermissionIdempotencyRow, error)
	GetPersonalSpaceByUser(ctx context.Context, ownerUserID pgtype.UUID) (*Space, error)
	GetPreservationHold(ctx context.Context, legalHoldID pgtype.UUID) (*LegalHold, error)
	GetPreservationHoldForUpdate(ctx context.Context, legalHoldID pgtype.UUID) (*LegalHold, error)
	GetQuotaReservationForUpdate(ctx context.Context, quotaReservationID pgtype.UUID) (*QuotaReservation, error)
	GetRecentLoginFailureState(ctx context.Context, arg *GetRecentLoginFailureStateParams) (*GetRecentLoginFailureStateRow, error)
	GetRecycleItemWithEntry(ctx context.Context, recycleItemID pgtype.UUID) (*GetRecycleItemWithEntryRow, error)
	GetRecycleItemWithEntryForUpdate(ctx context.Context, recycleItemID pgtype.UUID) (*GetRecycleItemWithEntryForUpdateRow, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (*GetRefreshTokenForUpdateRow, error)
	GetSearchIndexDocumentTarget(ctx context.Context, documentID pgtype.UUID) (*GetSearchIndexDocumentTargetRow, error)
	GetSessionIDByRefreshTokenHash(ctx context.Context, tokenHash []byte) (pgtype.UUID, error)
	GetShareIdempotency(ctx context.Context, arg *GetShareIdempotencyParams) (*GetShareIdempotencyRow, error)
	GetShareSourceResource(ctx context.Context, arg *GetShareSourceResourceParams) (*GetShareSourceResourceRow, error)
	GetShareWithActions(ctx context.Context, shareID pgtype.UUID) (*GetShareWithActionsRow, error)
	GetShareWithActionsForUpdate(ctx context.Context, shareID pgtype.UUID) (*GetShareWithActionsForUpdateRow, error)
	GetSpace(ctx context.Context, spaceID pgtype.UUID) (*Space, error)
	GetSpaceAuthorizationResource(ctx context.Context, spaceID pgtype.UUID) (*GetSpaceAuthorizationResourceRow, error)
	GetSpaceForUpdate(ctx context.Context, spaceID pgtype.UUID) (*Space, error)
	GetUploadDocumentContext(ctx context.Context, arg *GetUploadDocumentContextParams) (*GetUploadDocumentContextRow, error)
	GetUploadFolderContext(ctx context.Context, arg *GetUploadFolderContextParams) (*GetUploadFolderContextRow, error)
	GetUploadSession(ctx context.Context, uploadSessionID pgtype.UUID) (*UploadSession, error)
	GetUploadSessionForUpdate(ctx context.Context, uploadSessionID pgtype.UUID) (*UploadSession, error)
	GetUserIdempotencyRecordForUpdate(ctx context.Context, arg *GetUserIdempotencyRecordForUpdateParams) (*GetUserIdempotencyRecordForUpdateRow, error)
	GetVersionDocumentContext(ctx context.Context, documentID pgtype.UUID) (*GetVersionDocumentContextRow, error)
	GetVersionDocumentForUpdate(ctx context.Context, documentID pgtype.UUID) (*Document, error)
	HeartbeatDocumentLock(ctx context.Context, arg *HeartbeatDocumentLockParams) (*DocumentLock, error)
	IncrementDocumentACLVersion(ctx context.Context, arg *IncrementDocumentACLVersionParams) error
	IncrementDocumentLockCounter(ctx context.Context, arg *IncrementDocumentLockCounterParams) (int64, error)
	IncrementFolderACLVersion(ctx context.Context, arg *IncrementFolderACLVersionParams) error
	IncrementGlobalAuthorizationVersion(ctx context.Context, arg *IncrementGlobalAuthorizationVersionParams) error
	IncrementOrganizationDelegationVersion(ctx context.Context, arg *IncrementOrganizationDelegationVersionParams) error
	IncrementOrganizationGrantVersion(ctx context.Context, arg *IncrementOrganizationGrantVersionParams) error
	IncrementOrganizationMembershipVersion(ctx context.Context, arg *IncrementOrganizationMembershipVersionParams) error
	IncrementOrganizationSubtreeSecurityEpochs(ctx context.Context, arg *IncrementOrganizationSubtreeSecurityEpochsParams) error
	IncrementPrincipalDelegationVersion(ctx context.Context, arg *IncrementPrincipalDelegationVersionParams) error
	IncrementPrincipalGrantVersion(ctx context.Context, arg *IncrementPrincipalGrantVersionParams) error
	IncrementShareOrganizationVersion(ctx context.Context, arg *IncrementShareOrganizationVersionParams) error
	IncrementSharePrincipalVersion(ctx context.Context, arg *IncrementSharePrincipalVersionParams) error
	IncrementSpaceACLVersion(ctx context.Context, arg *IncrementSpaceACLVersionParams) error
	IncrementUserOrganizationMembershipVersion(ctx context.Context, arg *IncrementUserOrganizationMembershipVersionParams) error
	InsertAdminDelegation(ctx context.Context, arg *InsertAdminDelegationParams) (*AdminDelegation, error)
	InsertAdminDelegationCapability(ctx context.Context, arg *InsertAdminDelegationCapabilityParams) error
	InsertAuditChainHead(ctx context.Context, arg *InsertAuditChainHeadParams) error
	InsertAuditEvent(ctx context.Context, arg *InsertAuditEventParams) error
	InsertBackgroundJob(ctx context.Context, arg *InsertBackgroundJobParams) (*BackgroundJob, error)
	InsertDocumentLock(ctx context.Context, arg *InsertDocumentLockParams) (*DocumentLock, error)
	InsertFileDocument(ctx context.Context, arg *InsertFileDocumentParams) (*Document, error)
	InsertFileFolder(ctx context.Context, arg *InsertFileFolderParams) error
	InsertFileNamespaceEntry(ctx context.Context, arg *InsertFileNamespaceEntryParams) (*NamespaceEntry, error)
	InsertFileOutboxEvent(ctx context.Context, arg *InsertFileOutboxEventParams) error
	InsertLifecycleOutboxEvent(ctx context.Context, arg *InsertLifecycleOutboxEventParams) error
	InsertLoginAttempt(ctx context.Context, arg *InsertLoginAttemptParams) error
	InsertManagedPasswordCredential(ctx context.Context, arg *InsertManagedPasswordCredentialParams) error
	InsertManagedUser(ctx context.Context, arg *InsertManagedUserParams) (*InsertManagedUserRow, error)
	InsertMembership(ctx context.Context, arg *InsertMembershipParams) (*UserOrganization, error)
	InsertMovedOrganizationClosureLinks(ctx context.Context, arg *InsertMovedOrganizationClosureLinksParams) error
	InsertOrganization(ctx context.Context, arg *InsertOrganizationParams) (*Organization, error)
	InsertOrganizationChangeOperation(ctx context.Context, arg *InsertOrganizationChangeOperationParams) (*OrganizationChangeOperation, error)
	InsertOrganizationChangePlan(ctx context.Context, arg *InsertOrganizationChangePlanParams) (*OrganizationChangePlan, error)
	InsertOrganizationClosure(ctx context.Context, arg *InsertOrganizationClosureParams) error
	InsertOrganizationOutboxEvent(ctx context.Context, arg *InsertOrganizationOutboxEventParams) error
	InsertOrganizationSecurityVersions(ctx context.Context, arg *InsertOrganizationSecurityVersionsParams) error
	InsertPermissionGrant(ctx context.Context, arg *InsertPermissionGrantParams) (*PermissionGrant, error)
	InsertPermissionGrantAction(ctx context.Context, arg *InsertPermissionGrantActionParams) error
	InsertPermissionOutboxEvent(ctx context.Context, arg *InsertPermissionOutboxEventParams) error
	InsertPreservationHold(ctx context.Context, arg *InsertPreservationHoldParams) (*LegalHold, error)
	InsertPrincipalSecurityVersions(ctx context.Context, arg *InsertPrincipalSecurityVersionsParams) error
	InsertQuotaReservation(ctx context.Context, arg *InsertQuotaReservationParams) (*QuotaReservation, error)
	InsertRecycleItem(ctx context.Context, arg *InsertRecycleItemParams) (*RecycleItem, error)
	InsertRestoredDocumentVersion(ctx context.Context, arg *InsertRestoredDocumentVersionParams) (*DocumentVersion, error)
	InsertShare(ctx context.Context, arg *InsertShareParams) (*Share, error)
	InsertShareAction(ctx context.Context, arg *InsertShareActionParams) error
	InsertShareOutboxEvent(ctx context.Context, arg *InsertShareOutboxEventParams) error
	InsertSpace(ctx context.Context, arg *InsertSpaceParams) (*Space, error)
	InsertUploadSession(ctx context.Context, arg *InsertUploadSessionParams) (*UploadSession, error)
	InsertUserOutboxEvent(ctx context.Context, arg *InsertUserOutboxEventParams) error
	InsertVersionOutboxEvent(ctx context.Context, arg *InsertVersionOutboxEventParams) error
	InvalidateDescendantAdminDelegations(ctx context.Context, arg *InvalidateDescendantAdminDelegationsParams) ([]pgtype.UUID, error)
	LifecycleNameExists(ctx context.Context, arg *LifecycleNameExistsParams) (bool, error)
	ListActivePermissionUserOrganizations(ctx context.Context, arg *ListActivePermissionUserOrganizationsParams) ([]pgtype.UUID, error)
	ListAuditChainEventsForVerify(ctx context.Context, arg *ListAuditChainEventsForVerifyParams) ([]*ListAuditChainEventsForVerifyRow, error)
	ListAuditChainHeads(ctx context.Context, arg *ListAuditChainHeadsParams) ([]*AuditChainHead, error)
	ListAuditEvents(ctx context.Context, arg *ListAuditEventsParams) ([]*ListAuditEventsRow, error)
	ListBackgroundJobs(ctx context.Context, arg *ListBackgroundJobsParams) ([]*BackgroundJob, error)
	ListCandidatePermissionGrants(ctx context.Context, arg *ListCandidatePermissionGrantsParams) ([]*ListCandidatePermissionGrantsRow, error)
	ListCandidateShareGrants(ctx context.Context, arg *ListCandidateShareGrantsParams) ([]*ListCandidateShareGrantsRow, error)
	ListCreatedShares(ctx context.Context, arg *ListCreatedSharesParams) ([]*ListCreatedSharesRow, error)
	ListDirectPermissionGrants(ctx context.Context, arg *ListDirectPermissionGrantsParams) ([]*ListDirectPermissionGrantsRow, error)
	ListDocumentVersions(ctx context.Context, arg *ListDocumentVersionsParams) ([]*DocumentVersion, error)
	ListExpiredActiveRecycleItems(ctx context.Context, arg *ListExpiredActiveRecycleItemsParams) ([]*ListExpiredActiveRecycleItemsRow, error)
	ListFileChildEntries(ctx context.Context, arg *ListFileChildEntriesParams) ([]*ListFileChildEntriesRow, error)
	ListFolderAuthorizationAncestors(ctx context.Context, resourceID pgtype.UUID) ([]*ListFolderAuthorizationAncestorsRow, error)
	ListManagedUserSessions(ctx context.Context, arg *ListManagedUserSessionsParams) ([]*UserSession, error)
	ListManagedUsers(ctx context.Context, arg *ListManagedUsersParams) ([]*ListManagedUsersRow, error)
	ListMemberships(ctx context.Context, arg *ListMembershipsParams) ([]*UserOrganization, error)
	ListOrganizationAdministrators(ctx context.Context, arg *ListOrganizationAdministratorsParams) ([]*ListOrganizationAdministratorsRow, error)
	ListOrganizationChangeOperations(ctx context.Context, organizationChangePlanID pgtype.UUID) ([]*OrganizationChangeOperation, error)
	ListOrganizationChangePlans(ctx context.Context, arg *ListOrganizationChangePlansParams) ([]*OrganizationChangePlan, error)
	ListOrganizations(ctx context.Context, arg *ListOrganizationsParams) ([]*Organization, error)
	ListOutboxEvents(ctx context.Context, arg *ListOutboxEventsParams) ([]*OutboxEvent, error)
	ListPreservationHolds(ctx context.Context, arg *ListPreservationHoldsParams) ([]*LegalHold, error)
	ListReceivedShares(ctx context.Context, arg *ListReceivedSharesParams) ([]*ListReceivedSharesRow, error)
	ListRecycleItems(ctx context.Context, arg *ListRecycleItemsParams) ([]*ListRecycleItemsRow, error)
	ListSpaces(ctx context.Context, arg *ListSpacesParams) ([]*Space, error)
	ListVisibleAdminDelegations(ctx context.Context, arg *ListVisibleAdminDelegationsParams) ([]*ListVisibleAdminDelegationsRow, error)
	LockActiveSystemAdministrators(ctx context.Context) ([]pgtype.UUID, error)
	LockOrganizationTreeMutation(ctx context.Context) error
	LockSystemAdminMutation(ctx context.Context) error
	MarkAuditChainInvalid(ctx context.Context, arg *MarkAuditChainInvalidParams) (int64, error)
	MarkAuditChainVerified(ctx context.Context, arg *MarkAuditChainVerifiedParams) (int64, error)
	MarkBackgroundJobDead(ctx context.Context, arg *MarkBackgroundJobDeadParams) (int64, error)
	MarkBackgroundJobFailed(ctx context.Context, arg *MarkBackgroundJobFailedParams) (int64, error)
	MarkBackgroundJobManuallyDead(ctx context.Context, arg *MarkBackgroundJobManuallyDeadParams) (*BackgroundJob, error)
	MarkBackgroundJobSuccess(ctx context.Context, arg *MarkBackgroundJobSuccessParams) (int64, error)
	MarkLifecycleEntrySubtreePurging(ctx context.Context, arg *MarkLifecycleEntrySubtreePurgingParams) (int64, error)
	MarkOrganizationChangeOperation(ctx context.Context, arg *MarkOrganizationChangeOperationParams) (*OrganizationChangeOperation, error)
	MarkOutboxEventDead(ctx context.Context, arg *MarkOutboxEventDeadParams) (int64, error)
	MarkOutboxEventFailed(ctx context.Context, arg *MarkOutboxEventFailedParams) (int64, error)
	MarkOutboxEventPublished(ctx context.Context, arg *MarkOutboxEventPublishedParams) (int64, error)
	MarkQuotaReservationConsumed(ctx context.Context, arg *MarkQuotaReservationConsumedParams) (*QuotaReservation, error)
	MarkQuotaReservationReleased(ctx context.Context, arg *MarkQuotaReservationReleasedParams) (*QuotaReservation, error)
	MarkRecycleItemPurging(ctx context.Context, arg *MarkRecycleItemPurgingParams) (*RecycleItem, error)
	MarkRefreshTokenReused(ctx context.Context, arg *MarkRefreshTokenReusedParams) error
	MarkRefreshTokenUsed(ctx context.Context, arg *MarkRefreshTokenUsedParams) (int64, error)
	MarkSharesSourceUnavailableForEntrySubtree(ctx context.Context, arg *MarkSharesSourceUnavailableForEntrySubtreeParams) error
	MarkUploadSessionUploading(ctx context.Context, arg *MarkUploadSessionUploadingParams) (*UploadSession, error)
	MoveFileNamespaceEntry(ctx context.Context, arg *MoveFileNamespaceEntryParams) (*NamespaceEntry, error)
	MoveRestoreLifecycleRoot(ctx context.Context, arg *MoveRestoreLifecycleRootParams) (*NamespaceEntry, error)
	OrganizationDeletionBlocked(ctx context.Context, arg *OrganizationDeletionBlockedParams) (bool, error)
	OrganizationWouldCreateCycle(ctx context.Context, arg *OrganizationWouldCreateCycleParams) (bool, error)
	PermissionOrganizationExists(ctx context.Context, organizationID pgtype.UUID) (bool, error)
	RecoverExpiredBackgroundLeases(ctx context.Context, arg *RecoverExpiredBackgroundLeasesParams) (*RecoverExpiredBackgroundLeasesRow, error)
	ReleaseDocumentLock(ctx context.Context, arg *ReleaseDocumentLockParams) (*DocumentLock, error)
	ReleasePreservationHold(ctx context.Context, arg *ReleasePreservationHoldParams) (*LegalHold, error)
	ReleaseSpaceQuotaReservation(ctx context.Context, arg *ReleaseSpaceQuotaReservationParams) (int64, error)
	RenameFileNamespaceEntry(ctx context.Context, arg *RenameFileNamespaceEntryParams) (*NamespaceEntry, error)
	RenewBackgroundJobLease(ctx context.Context, arg *RenewBackgroundJobLeaseParams) (int64, error)
	RenewOutboxEventLease(ctx context.Context, arg *RenewOutboxEventLeaseParams) (int64, error)
	ReserveSpaceQuota(ctx context.Context, arg *ReserveSpaceQuotaParams) (*Space, error)
	RestoreLifecycleEntrySubtree(ctx context.Context, arg *RestoreLifecycleEntrySubtreeParams) (int64, error)
	RestoreRecycleItem(ctx context.Context, arg *RestoreRecycleItemParams) (*RecycleItem, error)
	RetryBackgroundJob(ctx context.Context, arg *RetryBackgroundJobParams) (*BackgroundJob, error)
	RetryOutboxEvent(ctx context.Context, arg *RetryOutboxEventParams) (*OutboxEvent, error)
	RevokeActiveRefreshTokensForSession(ctx context.Context, arg *RevokeActiveRefreshTokensForSessionParams) error
	RevokeAdminDelegation(ctx context.Context, arg *RevokeAdminDelegationParams) (*AdminDelegation, error)
	RevokeManagedUserCredentials(ctx context.Context, arg *RevokeManagedUserCredentialsParams) error
	RevokeManagedUserRefreshTokens(ctx context.Context, arg *RevokeManagedUserRefreshTokensParams) error
	RevokeManagedUserSessions(ctx context.Context, arg *RevokeManagedUserSessionsParams) error
	RevokeOwnedUserSession(ctx context.Context, arg *RevokeOwnedUserSessionParams) (int64, error)
	RevokeOwnedUserSessionTokens(ctx context.Context, arg *RevokeOwnedUserSessionTokensParams) error
	RevokePermissionGrant(ctx context.Context, arg *RevokePermissionGrantParams) (*PermissionGrant, error)
	RevokeShare(ctx context.Context, arg *RevokeShareParams) (*Share, error)
	RevokeUserSession(ctx context.Context, arg *RevokeUserSessionParams) error
	SearchDirectoryEntries(ctx context.Context, arg *SearchDirectoryEntriesParams) ([]*SearchDirectoryEntriesRow, error)
	SetDocumentCurrentVersion(ctx context.Context, arg *SetDocumentCurrentVersionParams) (int64, error)
	SetManagedUserStatus(ctx context.Context, arg *SetManagedUserStatusParams) (*SetManagedUserStatusRow, error)
	SetOrganizationChangePlanStatus(ctx context.Context, arg *SetOrganizationChangePlanStatusParams) (*OrganizationChangePlan, error)
	SetOrganizationStatus(ctx context.Context, arg *SetOrganizationStatusParams) (*Organization, error)
	SetSpaceStatus(ctx context.Context, arg *SetSpaceStatusParams) (*Space, error)
	SkipBackgroundJob(ctx context.Context, arg *SkipBackgroundJobParams) (*BackgroundJob, error)
	SpaceDeletionBlocked(ctx context.Context, spaceID pgtype.UUID) (bool, error)
	TouchCredentialAfterLogin(ctx context.Context, arg *TouchCredentialAfterLoginParams) error
	TouchDraftOrganizationChangePlan(ctx context.Context, arg *TouchDraftOrganizationChangePlanParams) (*OrganizationChangePlan, error)
	TouchFileSpaceSecurityEpoch(ctx context.Context, arg *TouchFileSpaceSecurityEpochParams) error
	TouchLifecycleSpaceSecurityEpoch(ctx context.Context, arg *TouchLifecycleSpaceSecurityEpochParams) error
	TouchManagedUserForPasswordReset(ctx context.Context, arg *TouchManagedUserForPasswordResetParams) (int64, error)
	TouchUserAfterLogin(ctx context.Context, arg *TouchUserAfterLoginParams) error
	TouchUserSession(ctx context.Context, arg *TouchUserSessionParams) error
	TrashLifecycleEntrySubtree(ctx context.Context, arg *TrashLifecycleEntrySubtreeParams) (int64, error)
	TryCreateFileIdempotencyRecord(ctx context.Context, arg *TryCreateFileIdempotencyRecordParams) (int64, error)
	TryCreateLifecycleIdempotency(ctx context.Context, arg *TryCreateLifecycleIdempotencyParams) (int64, error)
	TryCreateOrganizationIdempotencyRecord(ctx context.Context, arg *TryCreateOrganizationIdempotencyRecordParams) (int64, error)
	TryCreatePermissionIdempotency(ctx context.Context, arg *TryCreatePermissionIdempotencyParams) (int64, error)
	TryCreateShareIdempotency(ctx context.Context, arg *TryCreateShareIdempotencyParams) (int64, error)
	TryCreateUserIdempotencyRecord(ctx context.Context, arg *TryCreateUserIdempotencyRecordParams) (int64, error)
	UpdateAuditChainHead(ctx context.Context, arg *UpdateAuditChainHeadParams) (int64, error)
	UpdateFileDescendantPaths(ctx context.Context, arg *UpdateFileDescendantPathsParams) error
	UpdateFileDocumentExtension(ctx context.Context, arg *UpdateFileDocumentExtensionParams) error
	UpdateFileSpaceRootFolder(ctx context.Context, arg *UpdateFileSpaceRootFolderParams) error
	UpdateLifecycleDescendantPaths(ctx context.Context, arg *UpdateLifecycleDescendantPathsParams) error
	UpdateManagedPasswordCredential(ctx context.Context, arg *UpdateManagedPasswordCredentialParams) (int64, error)
	UpdateManagedUser(ctx context.Context, arg *UpdateManagedUserParams) (*UpdateManagedUserRow, error)
	UpdateMembership(ctx context.Context, arg *UpdateMembershipParams) (*UserOrganization, error)
	UpdateMovedOrganizationSubtree(ctx context.Context, arg *UpdateMovedOrganizationSubtreeParams) error
	UpdateOrganization(ctx context.Context, arg *UpdateOrganizationParams) (*Organization, error)
	UpdatePermissionGrant(ctx context.Context, arg *UpdatePermissionGrantParams) (*PermissionGrant, error)
	UpdateShare(ctx context.Context, arg *UpdateShareParams) (*Share, error)
	UpdateSpace(ctx context.Context, arg *UpdateSpaceParams) (*Space, error)
	UpsertDocumentIndexPending(ctx context.Context, arg *UpsertDocumentIndexPendingParams) (*DocumentIndexState, error)
	UserCanJoinOrganization(ctx context.Context, arg *UserCanJoinOrganizationParams) (pgtype.Bool, error)
	UserExistsAndIsActive(ctx context.Context, userID pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
