// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchDirectoryEntries = `-- name: SearchDirectoryEntries :many
SELECT
  e.namespace_entry_id, e.space_id, e.parent_folder_id, e.entry_type, e.name, e.normalized_name,
  e.path_cache, e.depth, e.lifecycle_status, e.created_by_user_id, e.created_at, e.updated_at,
  e.deleted_at, e.row_version, (sp.root_folder_id = e.namespace_entry_id) AS is_root,
  f.inheritance_mode AS folder_inheritance_mode,
  f.acl_version AS folder_acl_version,
  d.owner_user_id, d.current_version_id, d.availability_status, d.extension_normalized,
  d.inheritance_mode AS document_inheritance_mode,
  d.acl_version AS document_acl_version,
  d.classification, d.metadata_schema_version, d.metadata_json,
  s.status AS index_status
FROM namespace_entries e
JOIN spaces sp ON sp.space_id = e.space_id
LEFT JOIN folders f ON f.folder_id = e.namespace_entry_id
LEFT JOIN documents d ON d.document_id = e.namespace_entry_id
LEFT JOIN document_index_states s ON s.document_id = d.document_id
WHERE e.lifecycle_status = 'ACTIVE'
  AND sp.status <> 'DELETED'
  AND ($1::uuid IS NULL OR e.space_id = $1::uuid)
  AND ($2::text IS NULL OR e.entry_type = $2::text)
  AND (
    $3::text IS NULL
    OR e.normalized_name LIKE '%' || $3::text || '%'
    OR lower(e.name) LIKE '%' || $3::text || '%'
    OR lower(COALESCE(d.extension_normalized, '')) LIKE '%' || $3::text || '%'
    OR lower(COALESCE(d.classification, '')) LIKE '%' || $3::text || '%'
  )
  AND ($4::text IS NULL OR lower(COALESCE(d.extension_normalized, '')) = $4::text)
  AND ($5::text IS NULL OR lower(COALESCE(d.classification, '')) = $5::text)
  AND ($6::uuid IS NULL OR e.created_by_user_id = $6::uuid)
  AND ($7::timestamptz IS NULL OR e.updated_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR e.updated_at <= $8::timestamptz)
  AND (
    $9::text IS NULL
    OR d.metadata_json ->> $9::text IS NOT NULL
  )
  AND (
    $10::text IS NULL
    OR lower(COALESCE(d.metadata_json ->> $9::text, '')) LIKE '%' || $10::text || '%'
  )
ORDER BY
  CASE
    WHEN $3::text IS NOT NULL AND e.normalized_name = $3::text THEN 0
    WHEN $3::text IS NOT NULL AND e.normalized_name LIKE $3::text || '%' THEN 1
    ELSE 2
  END,
  e.updated_at DESC,
  e.namespace_entry_id DESC
LIMIT $12::integer OFFSET $11::bigint
`

type SearchDirectoryEntriesParams struct {
	SpaceID         pgtype.UUID
	EntryType       pgtype.Text
	Query           pgtype.Text
	Extension       pgtype.Text
	Classification  pgtype.Text
	CreatedByUserID pgtype.UUID
	UpdatedFrom     pgtype.Timestamptz
	UpdatedTo       pgtype.Timestamptz
	MetadataKey     pgtype.Text
	MetadataValue   pgtype.Text
	PageOffset      int64
	PageSize        int32
}

type SearchDirectoryEntriesRow struct {
	NamespaceEntryID        pgtype.UUID
	SpaceID                 pgtype.UUID
	ParentFolderID          pgtype.UUID
	EntryType               string
	Name                    string
	NormalizedName          string
	PathCache               pgtype.Text
	Depth                   int32
	LifecycleStatus         string
	CreatedByUserID         pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	RowVersion              int64
	IsRoot                  bool
	FolderInheritanceMode   pgtype.Text
	FolderAclVersion        pgtype.Int8
	OwnerUserID             pgtype.UUID
	CurrentVersionID        pgtype.UUID
	AvailabilityStatus      pgtype.Text
	ExtensionNormalized     pgtype.Text
	DocumentInheritanceMode pgtype.Text
	DocumentAclVersion      pgtype.Int8
	Classification          pgtype.Text
	MetadataSchemaVersion   pgtype.Int4
	MetadataJson            []byte
	IndexStatus             pgtype.Text
}

func (q *Queries) SearchDirectoryEntries(ctx context.Context, arg *SearchDirectoryEntriesParams) ([]*SearchDirectoryEntriesRow, error) {
	rows, err := q.db.Query(ctx, searchDirectoryEntries,
		arg.SpaceID,
		arg.EntryType,
		arg.Query,
		arg.Extension,
		arg.Classification,
		arg.CreatedByUserID,
		arg.UpdatedFrom,
		arg.UpdatedTo,
		arg.MetadataKey,
		arg.MetadataValue,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SearchDirectoryEntriesRow{}
	for rows.Next() {
		var i SearchDirectoryEntriesRow
		if err := rows.Scan(
			&i.NamespaceEntryID,
			&i.SpaceID,
			&i.ParentFolderID,
			&i.EntryType,
			&i.Name,
			&i.NormalizedName,
			&i.PathCache,
			&i.Depth,
			&i.LifecycleStatus,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RowVersion,
			&i.IsRoot,
			&i.FolderInheritanceMode,
			&i.FolderAclVersion,
			&i.OwnerUserID,
			&i.CurrentVersionID,
			&i.AvailabilityStatus,
			&i.ExtensionNormalized,
			&i.DocumentInheritanceMode,
			&i.DocumentAclVersion,
			&i.Classification,
			&i.MetadataSchemaVersion,
			&i.MetadataJson,
			&i.IndexStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
