// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeShareIdempotency = `-- name: CompleteShareIdempotency :exec
UPDATE idempotency_records
SET status = 'COMPLETED', result_resource_id = $4, result_resource_type = $5, completed_at = $6, updated_at = $6
WHERE principal_kind = 'USER' AND user_id = $1 AND operation = $2 AND idempotency_key = $3 AND status = 'IN_PROGRESS'
`

type CompleteShareIdempotencyParams struct {
	UserID             pgtype.UUID
	Operation          string
	IdempotencyKey     string
	ResultResourceID   pgtype.UUID
	ResultResourceType pgtype.Text
	CompletedAt        pgtype.Timestamptz
}

func (q *Queries) CompleteShareIdempotency(ctx context.Context, arg *CompleteShareIdempotencyParams) error {
	_, err := q.db.Exec(ctx, completeShareIdempotency,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.ResultResourceID,
		arg.ResultResourceType,
		arg.CompletedAt,
	)
	return err
}

const countCreatedShares = `-- name: CountCreatedShares :one
SELECT count(*)::bigint
FROM shares s
WHERE s.creator_user_id = $1
`

func (q *Queries) CountCreatedShares(ctx context.Context, creatorUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCreatedShares, creatorUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countReceivedShares = `-- name: CountReceivedShares :one
SELECT count(DISTINCT s.share_id)::bigint
FROM shares s
WHERE s.status = 'ACTIVE'
  AND s.valid_from <= $1::timestamptz
  AND (s.valid_until IS NULL OR s.valid_until > $1)
  AND (
    s.target_user_id = $2::uuid
    OR s.target_organization_id = ANY($3::uuid[])
  )
`

type CountReceivedSharesParams struct {
	EffectiveAt     pgtype.Timestamptz
	UserID          pgtype.UUID
	OrganizationIds []pgtype.UUID
}

func (q *Queries) CountReceivedShares(ctx context.Context, arg *CountReceivedSharesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReceivedShares, arg.EffectiveAt, arg.UserID, arg.OrganizationIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteShareActions = `-- name: DeleteShareActions :exec
DELETE FROM share_actions WHERE share_id = $1
`

func (q *Queries) DeleteShareActions(ctx context.Context, shareID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShareActions, shareID)
	return err
}

const expireShares = `-- name: ExpireShares :exec
UPDATE shares
SET status = 'EXPIRED',
    updated_at = $1::timestamptz,
    row_version = row_version + 1
WHERE status = 'ACTIVE'
  AND valid_until IS NOT NULL
  AND valid_until <= $1::timestamptz
`

func (q *Queries) ExpireShares(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireShares, updatedAt)
	return err
}

const getShareIdempotency = `-- name: GetShareIdempotency :one
SELECT request_hash, status, result_resource_id FROM idempotency_records
WHERE principal_kind = 'USER' AND user_id = $1 AND operation = $2 AND idempotency_key = $3
`

type GetShareIdempotencyParams struct {
	UserID         pgtype.UUID
	Operation      string
	IdempotencyKey string
}

type GetShareIdempotencyRow struct {
	RequestHash      []byte
	Status           string
	ResultResourceID pgtype.UUID
}

func (q *Queries) GetShareIdempotency(ctx context.Context, arg *GetShareIdempotencyParams) (*GetShareIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getShareIdempotency, arg.UserID, arg.Operation, arg.IdempotencyKey)
	var i GetShareIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.Status, &i.ResultResourceID)
	return &i, err
}

const getShareSourceResource = `-- name: GetShareSourceResource :one
SELECT
  e.namespace_entry_id AS resource_id,
  $1::text AS resource_type,
  e.space_id,
  e.name,
  s.space_type,
  s.owner_user_id AS space_owner_user_id,
  s.organization_id,
  COALESCE(d.owner_user_id, s.owner_user_id) AS owner_user_id,
  COALESCE(d.inheritance_mode, f.inheritance_mode) AS inheritance_mode,
  COALESCE(d.acl_version, f.acl_version) AS acl_version,
  COALESCE(d.row_version, f.row_version) AS row_version
FROM namespace_entries e
JOIN spaces s ON s.space_id = e.space_id
LEFT JOIN documents d ON d.document_id = e.namespace_entry_id AND $1::text = 'DOCUMENT'
LEFT JOIN folders f ON f.folder_id = e.namespace_entry_id AND $1::text = 'FOLDER'
WHERE e.namespace_entry_id = $2::uuid
  AND e.entry_type = $1::text
  AND e.lifecycle_status = 'ACTIVE'
  AND s.status <> 'DELETED'
`

type GetShareSourceResourceParams struct {
	SourceType string
	SourceID   pgtype.UUID
}

type GetShareSourceResourceRow struct {
	ResourceID       pgtype.UUID
	ResourceType     string
	SpaceID          pgtype.UUID
	Name             string
	SpaceType        string
	SpaceOwnerUserID pgtype.UUID
	OrganizationID   pgtype.UUID
	OwnerUserID      pgtype.UUID
	InheritanceMode  string
	AclVersion       int64
	RowVersion       int64
}

func (q *Queries) GetShareSourceResource(ctx context.Context, arg *GetShareSourceResourceParams) (*GetShareSourceResourceRow, error) {
	row := q.db.QueryRow(ctx, getShareSourceResource, arg.SourceType, arg.SourceID)
	var i GetShareSourceResourceRow
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceType,
		&i.SpaceID,
		&i.Name,
		&i.SpaceType,
		&i.SpaceOwnerUserID,
		&i.OrganizationID,
		&i.OwnerUserID,
		&i.InheritanceMode,
		&i.AclVersion,
		&i.RowVersion,
	)
	return &i, err
}

const getShareWithActions = `-- name: GetShareWithActions :one
SELECT s.share_id, s.source_document_id, s.source_folder_id, s.creator_user_id, s.target_kind, s.target_user_id, s.target_organization_id, s.target_space_id, s.token_hash, s.password_hash, s.allow_reshare, s.valid_from, s.valid_until, s.status, s.created_at, s.updated_at, s.revoked_at, s.revoked_by_user_id, s.revoke_reason, s.row_version, COALESCE(array_agg(a.action ORDER BY a.action), ARRAY[]::varchar[])::text[] AS actions
FROM shares s
LEFT JOIN share_actions a ON a.share_id = s.share_id
WHERE s.share_id = $1
GROUP BY s.share_id
`

type GetShareWithActionsRow struct {
	ShareID              pgtype.UUID
	SourceDocumentID     pgtype.UUID
	SourceFolderID       pgtype.UUID
	CreatorUserID        pgtype.UUID
	TargetKind           string
	TargetUserID         pgtype.UUID
	TargetOrganizationID pgtype.UUID
	TargetSpaceID        pgtype.UUID
	TokenHash            []byte
	PasswordHash         pgtype.Text
	AllowReshare         bool
	ValidFrom            pgtype.Timestamptz
	ValidUntil           pgtype.Timestamptz
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedByUserID      pgtype.UUID
	RevokeReason         pgtype.Text
	RowVersion           int64
	Actions              []string
}

func (q *Queries) GetShareWithActions(ctx context.Context, shareID pgtype.UUID) (*GetShareWithActionsRow, error) {
	row := q.db.QueryRow(ctx, getShareWithActions, shareID)
	var i GetShareWithActionsRow
	err := row.Scan(
		&i.ShareID,
		&i.SourceDocumentID,
		&i.SourceFolderID,
		&i.CreatorUserID,
		&i.TargetKind,
		&i.TargetUserID,
		&i.TargetOrganizationID,
		&i.TargetSpaceID,
		&i.TokenHash,
		&i.PasswordHash,
		&i.AllowReshare,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.RowVersion,
		&i.Actions,
	)
	return &i, err
}

const getShareWithActionsForUpdate = `-- name: GetShareWithActionsForUpdate :one
SELECT s.share_id, s.source_document_id, s.source_folder_id, s.creator_user_id, s.target_kind, s.target_user_id, s.target_organization_id, s.target_space_id, s.token_hash, s.password_hash, s.allow_reshare, s.valid_from, s.valid_until, s.status, s.created_at, s.updated_at, s.revoked_at, s.revoked_by_user_id, s.revoke_reason, s.row_version, ARRAY(SELECT a.action FROM share_actions a WHERE a.share_id = s.share_id ORDER BY a.action)::text[] AS actions
FROM shares s
WHERE s.share_id = $1
FOR UPDATE
`

type GetShareWithActionsForUpdateRow struct {
	ShareID              pgtype.UUID
	SourceDocumentID     pgtype.UUID
	SourceFolderID       pgtype.UUID
	CreatorUserID        pgtype.UUID
	TargetKind           string
	TargetUserID         pgtype.UUID
	TargetOrganizationID pgtype.UUID
	TargetSpaceID        pgtype.UUID
	TokenHash            []byte
	PasswordHash         pgtype.Text
	AllowReshare         bool
	ValidFrom            pgtype.Timestamptz
	ValidUntil           pgtype.Timestamptz
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedByUserID      pgtype.UUID
	RevokeReason         pgtype.Text
	RowVersion           int64
	Actions              []string
}

func (q *Queries) GetShareWithActionsForUpdate(ctx context.Context, shareID pgtype.UUID) (*GetShareWithActionsForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getShareWithActionsForUpdate, shareID)
	var i GetShareWithActionsForUpdateRow
	err := row.Scan(
		&i.ShareID,
		&i.SourceDocumentID,
		&i.SourceFolderID,
		&i.CreatorUserID,
		&i.TargetKind,
		&i.TargetUserID,
		&i.TargetOrganizationID,
		&i.TargetSpaceID,
		&i.TokenHash,
		&i.PasswordHash,
		&i.AllowReshare,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.RowVersion,
		&i.Actions,
	)
	return &i, err
}

const incrementShareOrganizationVersion = `-- name: IncrementShareOrganizationVersion :exec
UPDATE organization_security_versions
SET share_version = share_version + 1,
    subtree_security_epoch = subtree_security_epoch + 1,
    updated_at = $2
WHERE organization_id IN (
  SELECT ancestor_organization_id FROM organization_closure WHERE descendant_organization_id = $1
)
`

type IncrementShareOrganizationVersionParams struct {
	DescendantOrganizationID pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
}

func (q *Queries) IncrementShareOrganizationVersion(ctx context.Context, arg *IncrementShareOrganizationVersionParams) error {
	_, err := q.db.Exec(ctx, incrementShareOrganizationVersion, arg.DescendantOrganizationID, arg.UpdatedAt)
	return err
}

const incrementSharePrincipalVersion = `-- name: IncrementSharePrincipalVersion :exec
UPDATE principal_security_versions
SET share_version = share_version + 1,
    global_authorization_version = global_authorization_version + 1,
    updated_at = $2
WHERE user_id = $1
`

type IncrementSharePrincipalVersionParams struct {
	UserID    pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) IncrementSharePrincipalVersion(ctx context.Context, arg *IncrementSharePrincipalVersionParams) error {
	_, err := q.db.Exec(ctx, incrementSharePrincipalVersion, arg.UserID, arg.UpdatedAt)
	return err
}

const insertShare = `-- name: InsertShare :one
INSERT INTO shares (
  share_id, source_document_id, source_folder_id, creator_user_id,
  target_kind, target_user_id, target_organization_id, target_space_id,
  token_hash, allow_reshare, valid_from, valid_until, created_at, updated_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $13
)
RETURNING share_id, source_document_id, source_folder_id, creator_user_id, target_kind, target_user_id, target_organization_id, target_space_id, token_hash, password_hash, allow_reshare, valid_from, valid_until, status, created_at, updated_at, revoked_at, revoked_by_user_id, revoke_reason, row_version
`

type InsertShareParams struct {
	ShareID              pgtype.UUID
	SourceDocumentID     pgtype.UUID
	SourceFolderID       pgtype.UUID
	CreatorUserID        pgtype.UUID
	TargetKind           string
	TargetUserID         pgtype.UUID
	TargetOrganizationID pgtype.UUID
	TargetSpaceID        pgtype.UUID
	TokenHash            []byte
	AllowReshare         bool
	ValidFrom            pgtype.Timestamptz
	ValidUntil           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertShare(ctx context.Context, arg *InsertShareParams) (*Share, error) {
	row := q.db.QueryRow(ctx, insertShare,
		arg.ShareID,
		arg.SourceDocumentID,
		arg.SourceFolderID,
		arg.CreatorUserID,
		arg.TargetKind,
		arg.TargetUserID,
		arg.TargetOrganizationID,
		arg.TargetSpaceID,
		arg.TokenHash,
		arg.AllowReshare,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.CreatedAt,
	)
	var i Share
	err := row.Scan(
		&i.ShareID,
		&i.SourceDocumentID,
		&i.SourceFolderID,
		&i.CreatorUserID,
		&i.TargetKind,
		&i.TargetUserID,
		&i.TargetOrganizationID,
		&i.TargetSpaceID,
		&i.TokenHash,
		&i.PasswordHash,
		&i.AllowReshare,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.RowVersion,
	)
	return &i, err
}

const insertShareAction = `-- name: InsertShareAction :exec
INSERT INTO share_actions (share_id, action, created_at)
VALUES ($1, $2, $3)
`

type InsertShareActionParams struct {
	ShareID   pgtype.UUID
	Action    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertShareAction(ctx context.Context, arg *InsertShareActionParams) error {
	_, err := q.db.Exec(ctx, insertShareAction, arg.ShareID, arg.Action, arg.CreatedAt)
	return err
}

const insertShareOutboxEvent = `-- name: InsertShareOutboxEvent :exec
INSERT INTO outbox_events (
  outbox_event_id, aggregate_type, aggregate_id, aggregate_version,
  event_type, payload_json, deduplication_key, correlation_id, available_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertShareOutboxEventParams struct {
	OutboxEventID    pgtype.UUID
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
	PayloadJson      []byte
	DeduplicationKey string
	CorrelationID    pgtype.UUID
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertShareOutboxEvent(ctx context.Context, arg *InsertShareOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertShareOutboxEvent,
		arg.OutboxEventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.PayloadJson,
		arg.DeduplicationKey,
		arg.CorrelationID,
		arg.AvailableAt,
	)
	return err
}

const listCreatedShares = `-- name: ListCreatedShares :many
SELECT s.share_id, s.source_document_id, s.source_folder_id, s.creator_user_id, s.target_kind, s.target_user_id, s.target_organization_id, s.target_space_id, s.token_hash, s.password_hash, s.allow_reshare, s.valid_from, s.valid_until, s.status, s.created_at, s.updated_at, s.revoked_at, s.revoked_by_user_id, s.revoke_reason, s.row_version, COALESCE(array_agg(a.action ORDER BY a.action), ARRAY[]::varchar[])::text[] AS actions
FROM shares s
LEFT JOIN share_actions a ON a.share_id = s.share_id
WHERE s.creator_user_id = $1
GROUP BY s.share_id
ORDER BY s.created_at DESC, s.share_id DESC
LIMIT $3::integer OFFSET $2::bigint
`

type ListCreatedSharesParams struct {
	CreatorUserID pgtype.UUID
	PageOffset    int64
	PageSize      int32
}

type ListCreatedSharesRow struct {
	ShareID              pgtype.UUID
	SourceDocumentID     pgtype.UUID
	SourceFolderID       pgtype.UUID
	CreatorUserID        pgtype.UUID
	TargetKind           string
	TargetUserID         pgtype.UUID
	TargetOrganizationID pgtype.UUID
	TargetSpaceID        pgtype.UUID
	TokenHash            []byte
	PasswordHash         pgtype.Text
	AllowReshare         bool
	ValidFrom            pgtype.Timestamptz
	ValidUntil           pgtype.Timestamptz
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedByUserID      pgtype.UUID
	RevokeReason         pgtype.Text
	RowVersion           int64
	Actions              []string
}

func (q *Queries) ListCreatedShares(ctx context.Context, arg *ListCreatedSharesParams) ([]*ListCreatedSharesRow, error) {
	rows, err := q.db.Query(ctx, listCreatedShares, arg.CreatorUserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListCreatedSharesRow{}
	for rows.Next() {
		var i ListCreatedSharesRow
		if err := rows.Scan(
			&i.ShareID,
			&i.SourceDocumentID,
			&i.SourceFolderID,
			&i.CreatorUserID,
			&i.TargetKind,
			&i.TargetUserID,
			&i.TargetOrganizationID,
			&i.TargetSpaceID,
			&i.TokenHash,
			&i.PasswordHash,
			&i.AllowReshare,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.RowVersion,
			&i.Actions,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedShares = `-- name: ListReceivedShares :many
SELECT s.share_id, s.source_document_id, s.source_folder_id, s.creator_user_id, s.target_kind, s.target_user_id, s.target_organization_id, s.target_space_id, s.token_hash, s.password_hash, s.allow_reshare, s.valid_from, s.valid_until, s.status, s.created_at, s.updated_at, s.revoked_at, s.revoked_by_user_id, s.revoke_reason, s.row_version, COALESCE(array_agg(a.action ORDER BY a.action), ARRAY[]::varchar[])::text[] AS actions
FROM shares s
LEFT JOIN share_actions a ON a.share_id = s.share_id
WHERE s.status = 'ACTIVE'
  AND s.valid_from <= $1::timestamptz
  AND (s.valid_until IS NULL OR s.valid_until > $1)
  AND (
    s.target_user_id = $2::uuid
    OR s.target_organization_id = ANY($3::uuid[])
  )
GROUP BY s.share_id
ORDER BY s.created_at DESC, s.share_id DESC
LIMIT $5::integer OFFSET $4::bigint
`

type ListReceivedSharesParams struct {
	EffectiveAt     pgtype.Timestamptz
	UserID          pgtype.UUID
	OrganizationIds []pgtype.UUID
	PageOffset      int64
	PageSize        int32
}

type ListReceivedSharesRow struct {
	ShareID              pgtype.UUID
	SourceDocumentID     pgtype.UUID
	SourceFolderID       pgtype.UUID
	CreatorUserID        pgtype.UUID
	TargetKind           string
	TargetUserID         pgtype.UUID
	TargetOrganizationID pgtype.UUID
	TargetSpaceID        pgtype.UUID
	TokenHash            []byte
	PasswordHash         pgtype.Text
	AllowReshare         bool
	ValidFrom            pgtype.Timestamptz
	ValidUntil           pgtype.Timestamptz
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedByUserID      pgtype.UUID
	RevokeReason         pgtype.Text
	RowVersion           int64
	Actions              []string
}

func (q *Queries) ListReceivedShares(ctx context.Context, arg *ListReceivedSharesParams) ([]*ListReceivedSharesRow, error) {
	rows, err := q.db.Query(ctx, listReceivedShares,
		arg.EffectiveAt,
		arg.UserID,
		arg.OrganizationIds,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListReceivedSharesRow{}
	for rows.Next() {
		var i ListReceivedSharesRow
		if err := rows.Scan(
			&i.ShareID,
			&i.SourceDocumentID,
			&i.SourceFolderID,
			&i.CreatorUserID,
			&i.TargetKind,
			&i.TargetUserID,
			&i.TargetOrganizationID,
			&i.TargetSpaceID,
			&i.TokenHash,
			&i.PasswordHash,
			&i.AllowReshare,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.RowVersion,
			&i.Actions,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShare = `-- name: RevokeShare :one
UPDATE shares
SET status = 'REVOKED',
    revoked_at = $4,
    revoked_by_user_id = $2,
    revoke_reason = $3,
    updated_at = $4,
    row_version = row_version + 1
WHERE share_id = $1 AND row_version = $5 AND status = 'ACTIVE'
RETURNING share_id, source_document_id, source_folder_id, creator_user_id, target_kind, target_user_id, target_organization_id, target_space_id, token_hash, password_hash, allow_reshare, valid_from, valid_until, status, created_at, updated_at, revoked_at, revoked_by_user_id, revoke_reason, row_version
`

type RevokeShareParams struct {
	ShareID         pgtype.UUID
	RevokedByUserID pgtype.UUID
	RevokeReason    pgtype.Text
	RevokedAt       pgtype.Timestamptz
	RowVersion      int64
}

func (q *Queries) RevokeShare(ctx context.Context, arg *RevokeShareParams) (*Share, error) {
	row := q.db.QueryRow(ctx, revokeShare,
		arg.ShareID,
		arg.RevokedByUserID,
		arg.RevokeReason,
		arg.RevokedAt,
		arg.RowVersion,
	)
	var i Share
	err := row.Scan(
		&i.ShareID,
		&i.SourceDocumentID,
		&i.SourceFolderID,
		&i.CreatorUserID,
		&i.TargetKind,
		&i.TargetUserID,
		&i.TargetOrganizationID,
		&i.TargetSpaceID,
		&i.TokenHash,
		&i.PasswordHash,
		&i.AllowReshare,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.RowVersion,
	)
	return &i, err
}

const tryCreateShareIdempotency = `-- name: TryCreateShareIdempotency :execrows
INSERT INTO idempotency_records (
  idempotency_record_id, principal_kind, user_id, operation, idempotency_key, request_hash,
  status, expires_at, created_at, updated_at
) VALUES ($1,'USER',$2,$3,$4,$5,'IN_PROGRESS',$6,$7,$7)
ON CONFLICT DO NOTHING
`

type TryCreateShareIdempotencyParams struct {
	IdempotencyRecordID pgtype.UUID
	UserID              pgtype.UUID
	Operation           string
	IdempotencyKey      string
	RequestHash         []byte
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) TryCreateShareIdempotency(ctx context.Context, arg *TryCreateShareIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryCreateShareIdempotency,
		arg.IdempotencyRecordID,
		arg.UserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateShare = `-- name: UpdateShare :one
UPDATE shares
SET allow_reshare = $2,
    valid_until = $3,
    updated_at = $4,
    row_version = row_version + 1
WHERE share_id = $1 AND row_version = $5 AND status = 'ACTIVE'
RETURNING share_id, source_document_id, source_folder_id, creator_user_id, target_kind, target_user_id, target_organization_id, target_space_id, token_hash, password_hash, allow_reshare, valid_from, valid_until, status, created_at, updated_at, revoked_at, revoked_by_user_id, revoke_reason, row_version
`

type UpdateShareParams struct {
	ShareID      pgtype.UUID
	AllowReshare bool
	ValidUntil   pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	RowVersion   int64
}

func (q *Queries) UpdateShare(ctx context.Context, arg *UpdateShareParams) (*Share, error) {
	row := q.db.QueryRow(ctx, updateShare,
		arg.ShareID,
		arg.AllowReshare,
		arg.ValidUntil,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i Share
	err := row.Scan(
		&i.ShareID,
		&i.SourceDocumentID,
		&i.SourceFolderID,
		&i.CreatorUserID,
		&i.TargetKind,
		&i.TargetUserID,
		&i.TargetOrganizationID,
		&i.TargetSpaceID,
		&i.TokenHash,
		&i.PasswordHash,
		&i.AllowReshare,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.RowVersion,
	)
	return &i, err
}
