// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortUploadSession = `-- name: AbortUploadSession :one
UPDATE upload_sessions
SET status = 'ABORTED',
    failure_code = $3,
    updated_at = $4,
    row_version = row_version + 1
WHERE upload_session_id = $1
  AND row_version = $2
  AND status IN ('INITIATED', 'UPLOADING', 'FAILED')
RETURNING upload_session_id, user_id, space_id, folder_id, quota_reservation_id, target_document_id, upload_intent, file_name, normalized_name, declared_size_bytes, declared_sha256, declared_mime_type, provider_upload_id, temporary_object_key, part_size_bytes, expected_part_count, expected_current_version_id, expected_lock_fencing_token, lock_token_hash, status, expires_at, created_at, updated_at, completed_at, failure_code, result_document_id, result_version_id, row_version
`

type AbortUploadSessionParams struct {
	UploadSessionID pgtype.UUID
	RowVersion      int64
	FailureCode     pgtype.Text
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) AbortUploadSession(ctx context.Context, arg *AbortUploadSessionParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, abortUploadSession,
		arg.UploadSessionID,
		arg.RowVersion,
		arg.FailureCode,
		arg.UpdatedAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.UploadSessionID,
		&i.UserID,
		&i.SpaceID,
		&i.FolderID,
		&i.QuotaReservationID,
		&i.TargetDocumentID,
		&i.UploadIntent,
		&i.FileName,
		&i.NormalizedName,
		&i.DeclaredSizeBytes,
		&i.DeclaredSha256,
		&i.DeclaredMimeType,
		&i.ProviderUploadID,
		&i.TemporaryObjectKey,
		&i.PartSizeBytes,
		&i.ExpectedPartCount,
		&i.ExpectedCurrentVersionID,
		&i.ExpectedLockFencingToken,
		&i.LockTokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultDocumentID,
		&i.ResultVersionID,
		&i.RowVersion,
	)
	return &i, err
}

const getUploadDocumentContext = `-- name: GetUploadDocumentContext :one
SELECT
  e.namespace_entry_id AS document_id,
  e.space_id,
  e.lifecycle_status,
  d.current_version_id,
  d.availability_status,
  d.row_version,
  s.status AS space_status
FROM namespace_entries e
JOIN documents d ON d.document_id = e.namespace_entry_id
JOIN spaces s ON s.space_id = e.space_id
WHERE e.namespace_entry_id = $1::uuid
  AND e.space_id = $2::uuid
  AND e.entry_type = 'DOCUMENT'
  AND e.lifecycle_status = 'ACTIVE'
  AND s.status = 'ACTIVE'
`

type GetUploadDocumentContextParams struct {
	DocumentID pgtype.UUID
	SpaceID    pgtype.UUID
}

type GetUploadDocumentContextRow struct {
	DocumentID         pgtype.UUID
	SpaceID            pgtype.UUID
	LifecycleStatus    string
	CurrentVersionID   pgtype.UUID
	AvailabilityStatus string
	RowVersion         int64
	SpaceStatus        string
}

func (q *Queries) GetUploadDocumentContext(ctx context.Context, arg *GetUploadDocumentContextParams) (*GetUploadDocumentContextRow, error) {
	row := q.db.QueryRow(ctx, getUploadDocumentContext, arg.DocumentID, arg.SpaceID)
	var i GetUploadDocumentContextRow
	err := row.Scan(
		&i.DocumentID,
		&i.SpaceID,
		&i.LifecycleStatus,
		&i.CurrentVersionID,
		&i.AvailabilityStatus,
		&i.RowVersion,
		&i.SpaceStatus,
	)
	return &i, err
}

const getUploadFolderContext = `-- name: GetUploadFolderContext :one
SELECT
  e.namespace_entry_id AS folder_id,
  e.space_id,
  e.lifecycle_status,
  s.status AS space_status
FROM namespace_entries e
JOIN folders f ON f.folder_id = e.namespace_entry_id
JOIN spaces s ON s.space_id = e.space_id
WHERE e.namespace_entry_id = $1::uuid
  AND e.space_id = $2::uuid
  AND e.entry_type = 'FOLDER'
  AND e.lifecycle_status = 'ACTIVE'
  AND s.status = 'ACTIVE'
`

type GetUploadFolderContextParams struct {
	FolderID pgtype.UUID
	SpaceID  pgtype.UUID
}

type GetUploadFolderContextRow struct {
	FolderID        pgtype.UUID
	SpaceID         pgtype.UUID
	LifecycleStatus string
	SpaceStatus     string
}

func (q *Queries) GetUploadFolderContext(ctx context.Context, arg *GetUploadFolderContextParams) (*GetUploadFolderContextRow, error) {
	row := q.db.QueryRow(ctx, getUploadFolderContext, arg.FolderID, arg.SpaceID)
	var i GetUploadFolderContextRow
	err := row.Scan(
		&i.FolderID,
		&i.SpaceID,
		&i.LifecycleStatus,
		&i.SpaceStatus,
	)
	return &i, err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT upload_session_id, user_id, space_id, folder_id, quota_reservation_id, target_document_id, upload_intent, file_name, normalized_name, declared_size_bytes, declared_sha256, declared_mime_type, provider_upload_id, temporary_object_key, part_size_bytes, expected_part_count, expected_current_version_id, expected_lock_fencing_token, lock_token_hash, status, expires_at, created_at, updated_at, completed_at, failure_code, result_document_id, result_version_id, row_version
FROM upload_sessions
WHERE upload_session_id = $1
`

func (q *Queries) GetUploadSession(ctx context.Context, uploadSessionID pgtype.UUID) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSession, uploadSessionID)
	var i UploadSession
	err := row.Scan(
		&i.UploadSessionID,
		&i.UserID,
		&i.SpaceID,
		&i.FolderID,
		&i.QuotaReservationID,
		&i.TargetDocumentID,
		&i.UploadIntent,
		&i.FileName,
		&i.NormalizedName,
		&i.DeclaredSizeBytes,
		&i.DeclaredSha256,
		&i.DeclaredMimeType,
		&i.ProviderUploadID,
		&i.TemporaryObjectKey,
		&i.PartSizeBytes,
		&i.ExpectedPartCount,
		&i.ExpectedCurrentVersionID,
		&i.ExpectedLockFencingToken,
		&i.LockTokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultDocumentID,
		&i.ResultVersionID,
		&i.RowVersion,
	)
	return &i, err
}

const getUploadSessionForUpdate = `-- name: GetUploadSessionForUpdate :one
SELECT upload_session_id, user_id, space_id, folder_id, quota_reservation_id, target_document_id, upload_intent, file_name, normalized_name, declared_size_bytes, declared_sha256, declared_mime_type, provider_upload_id, temporary_object_key, part_size_bytes, expected_part_count, expected_current_version_id, expected_lock_fencing_token, lock_token_hash, status, expires_at, created_at, updated_at, completed_at, failure_code, result_document_id, result_version_id, row_version
FROM upload_sessions
WHERE upload_session_id = $1
FOR UPDATE
`

func (q *Queries) GetUploadSessionForUpdate(ctx context.Context, uploadSessionID pgtype.UUID) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUpdate, uploadSessionID)
	var i UploadSession
	err := row.Scan(
		&i.UploadSessionID,
		&i.UserID,
		&i.SpaceID,
		&i.FolderID,
		&i.QuotaReservationID,
		&i.TargetDocumentID,
		&i.UploadIntent,
		&i.FileName,
		&i.NormalizedName,
		&i.DeclaredSizeBytes,
		&i.DeclaredSha256,
		&i.DeclaredMimeType,
		&i.ProviderUploadID,
		&i.TemporaryObjectKey,
		&i.PartSizeBytes,
		&i.ExpectedPartCount,
		&i.ExpectedCurrentVersionID,
		&i.ExpectedLockFencingToken,
		&i.LockTokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultDocumentID,
		&i.ResultVersionID,
		&i.RowVersion,
	)
	return &i, err
}

const insertUploadSession = `-- name: InsertUploadSession :one
INSERT INTO upload_sessions (
  upload_session_id, user_id, space_id, folder_id, quota_reservation_id,
  target_document_id, upload_intent, file_name, normalized_name,
  declared_size_bytes, declared_sha256, declared_mime_type,
  provider_upload_id, temporary_object_key,
  part_size_bytes, expected_part_count,
  expected_current_version_id, expected_lock_fencing_token, lock_token_hash,
  status, expires_at, created_at, updated_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::varchar,
  $8::varchar,
  $9::varchar,
  $10::bigint,
  $11::bytea,
  $12::varchar,
  $13::varchar,
  $14::varchar,
  $15::bigint,
  $16::integer,
  $17::uuid,
  $18::bigint,
  $19::bytea,
  'INITIATED',
  $20::timestamptz,
  $21::timestamptz,
  $21::timestamptz
)
RETURNING upload_session_id, user_id, space_id, folder_id, quota_reservation_id, target_document_id, upload_intent, file_name, normalized_name, declared_size_bytes, declared_sha256, declared_mime_type, provider_upload_id, temporary_object_key, part_size_bytes, expected_part_count, expected_current_version_id, expected_lock_fencing_token, lock_token_hash, status, expires_at, created_at, updated_at, completed_at, failure_code, result_document_id, result_version_id, row_version
`

type InsertUploadSessionParams struct {
	UploadSessionID          pgtype.UUID
	UserID                   pgtype.UUID
	SpaceID                  pgtype.UUID
	FolderID                 pgtype.UUID
	QuotaReservationID       pgtype.UUID
	TargetDocumentID         pgtype.UUID
	UploadIntent             string
	FileName                 string
	NormalizedName           string
	DeclaredSizeBytes        int64
	DeclaredSha256           []byte
	DeclaredMimeType         pgtype.Text
	ProviderUploadID         pgtype.Text
	TemporaryObjectKey       string
	PartSizeBytes            int64
	ExpectedPartCount        int32
	ExpectedCurrentVersionID pgtype.UUID
	ExpectedLockFencingToken pgtype.Int8
	LockTokenHash            []byte
	ExpiresAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) InsertUploadSession(ctx context.Context, arg *InsertUploadSessionParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, insertUploadSession,
		arg.UploadSessionID,
		arg.UserID,
		arg.SpaceID,
		arg.FolderID,
		arg.QuotaReservationID,
		arg.TargetDocumentID,
		arg.UploadIntent,
		arg.FileName,
		arg.NormalizedName,
		arg.DeclaredSizeBytes,
		arg.DeclaredSha256,
		arg.DeclaredMimeType,
		arg.ProviderUploadID,
		arg.TemporaryObjectKey,
		arg.PartSizeBytes,
		arg.ExpectedPartCount,
		arg.ExpectedCurrentVersionID,
		arg.ExpectedLockFencingToken,
		arg.LockTokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.UploadSessionID,
		&i.UserID,
		&i.SpaceID,
		&i.FolderID,
		&i.QuotaReservationID,
		&i.TargetDocumentID,
		&i.UploadIntent,
		&i.FileName,
		&i.NormalizedName,
		&i.DeclaredSizeBytes,
		&i.DeclaredSha256,
		&i.DeclaredMimeType,
		&i.ProviderUploadID,
		&i.TemporaryObjectKey,
		&i.PartSizeBytes,
		&i.ExpectedPartCount,
		&i.ExpectedCurrentVersionID,
		&i.ExpectedLockFencingToken,
		&i.LockTokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultDocumentID,
		&i.ResultVersionID,
		&i.RowVersion,
	)
	return &i, err
}

const markUploadSessionUploading = `-- name: MarkUploadSessionUploading :one
UPDATE upload_sessions
SET status = 'UPLOADING',
    updated_at = $2,
    row_version = row_version + 1
WHERE upload_session_id = $1
  AND status = 'INITIATED'
RETURNING upload_session_id, user_id, space_id, folder_id, quota_reservation_id, target_document_id, upload_intent, file_name, normalized_name, declared_size_bytes, declared_sha256, declared_mime_type, provider_upload_id, temporary_object_key, part_size_bytes, expected_part_count, expected_current_version_id, expected_lock_fencing_token, lock_token_hash, status, expires_at, created_at, updated_at, completed_at, failure_code, result_document_id, result_version_id, row_version
`

type MarkUploadSessionUploadingParams struct {
	UploadSessionID pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) MarkUploadSessionUploading(ctx context.Context, arg *MarkUploadSessionUploadingParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, markUploadSessionUploading, arg.UploadSessionID, arg.UpdatedAt)
	var i UploadSession
	err := row.Scan(
		&i.UploadSessionID,
		&i.UserID,
		&i.SpaceID,
		&i.FolderID,
		&i.QuotaReservationID,
		&i.TargetDocumentID,
		&i.UploadIntent,
		&i.FileName,
		&i.NormalizedName,
		&i.DeclaredSizeBytes,
		&i.DeclaredSha256,
		&i.DeclaredMimeType,
		&i.ProviderUploadID,
		&i.TemporaryObjectKey,
		&i.PartSizeBytes,
		&i.ExpectedPartCount,
		&i.ExpectedCurrentVersionID,
		&i.ExpectedLockFencingToken,
		&i.LockTokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultDocumentID,
		&i.ResultVersionID,
		&i.RowVersion,
	)
	return &i, err
}
