// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeUserIdempotencyRecord = `-- name: CompleteUserIdempotencyRecord :exec
UPDATE idempotency_records
SET status = 'COMPLETED',
    response_status_code = 201,
    response_schema_version = 1,
    response_json = jsonb_build_object('userId', $3::uuid),
    result_resource_type = 'USER',
    result_resource_id = $3,
    completed_at = $4,
    updated_at = $4,
    row_version = row_version + 1
WHERE user_id = $1
  AND operation = 'CREATE_USER'
  AND idempotency_key = $2
  AND status = 'IN_PROGRESS'
`

type CompleteUserIdempotencyRecordParams struct {
	UserID           pgtype.UUID
	IdempotencyKey   string
	ResultResourceID pgtype.UUID
	CompletedAt      pgtype.Timestamptz
}

func (q *Queries) CompleteUserIdempotencyRecord(ctx context.Context, arg *CompleteUserIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, completeUserIdempotencyRecord,
		arg.UserID,
		arg.IdempotencyKey,
		arg.ResultResourceID,
		arg.CompletedAt,
	)
	return err
}

const countManagedUserSessions = `-- name: CountManagedUserSessions :one
SELECT count(*)::bigint
FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) CountManagedUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedUserSessions, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countManagedUsers = `-- name: CountManagedUsers :one
SELECT count(*)::bigint
FROM users
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR system_role = $2::text)
`

type CountManagedUsersParams struct {
	Status     pgtype.Text
	SystemRole pgtype.Text
}

func (q *Queries) CountManagedUsers(ctx context.Context, arg *CountManagedUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedUsers, arg.Status, arg.SystemRole)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getManagedUserByID = `-- name: GetManagedUserByID :one
SELECT user_id, username, username_normalized, employee_no, employee_no_normalized,
       display_name, email, email_normalized, phone, system_role, status, locale,
       timezone, last_login_at, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM users
WHERE user_id = $1
`

type GetManagedUserByIDRow struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Status               string
	Locale               string
	Timezone             string
	LastLoginAt          pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

func (q *Queries) GetManagedUserByID(ctx context.Context, userID pgtype.UUID) (*GetManagedUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getManagedUserByID, userID)
	var i GetManagedUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmployeeNo,
		&i.EmployeeNoNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.Phone,
		&i.SystemRole,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getManagedUserForUpdate = `-- name: GetManagedUserForUpdate :one
SELECT user_id, username, username_normalized, employee_no, employee_no_normalized,
       display_name, email, email_normalized, phone, system_role, status, locale,
       timezone, last_login_at, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM users
WHERE user_id = $1
FOR UPDATE
`

type GetManagedUserForUpdateRow struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Status               string
	Locale               string
	Timezone             string
	LastLoginAt          pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

func (q *Queries) GetManagedUserForUpdate(ctx context.Context, userID pgtype.UUID) (*GetManagedUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getManagedUserForUpdate, userID)
	var i GetManagedUserForUpdateRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmployeeNo,
		&i.EmployeeNoNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.Phone,
		&i.SystemRole,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getOwnedUserSession = `-- name: GetOwnedUserSession :one
SELECT user_session_id
FROM user_sessions
WHERE user_session_id = $1
  AND user_id = $2
`

type GetOwnedUserSessionParams struct {
	UserSessionID pgtype.UUID
	UserID        pgtype.UUID
}

func (q *Queries) GetOwnedUserSession(ctx context.Context, arg *GetOwnedUserSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOwnedUserSession, arg.UserSessionID, arg.UserID)
	var user_session_id pgtype.UUID
	err := row.Scan(&user_session_id)
	return user_session_id, err
}

const getUserIdempotencyRecordForUpdate = `-- name: GetUserIdempotencyRecordForUpdate :one
SELECT request_hash, status, result_resource_id
FROM idempotency_records
WHERE principal_kind = 'USER'
  AND user_id = $1
  AND operation = 'CREATE_USER'
  AND idempotency_key = $2
FOR UPDATE
`

type GetUserIdempotencyRecordForUpdateParams struct {
	UserID         pgtype.UUID
	IdempotencyKey string
}

type GetUserIdempotencyRecordForUpdateRow struct {
	RequestHash      []byte
	Status           string
	ResultResourceID pgtype.UUID
}

func (q *Queries) GetUserIdempotencyRecordForUpdate(ctx context.Context, arg *GetUserIdempotencyRecordForUpdateParams) (*GetUserIdempotencyRecordForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserIdempotencyRecordForUpdate, arg.UserID, arg.IdempotencyKey)
	var i GetUserIdempotencyRecordForUpdateRow
	err := row.Scan(&i.RequestHash, &i.Status, &i.ResultResourceID)
	return &i, err
}

const incrementGlobalAuthorizationVersion = `-- name: IncrementGlobalAuthorizationVersion :exec
UPDATE principal_security_versions
SET global_authorization_version = global_authorization_version + 1,
    updated_at = $2
WHERE user_id = $1
`

type IncrementGlobalAuthorizationVersionParams struct {
	UserID    pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) IncrementGlobalAuthorizationVersion(ctx context.Context, arg *IncrementGlobalAuthorizationVersionParams) error {
	_, err := q.db.Exec(ctx, incrementGlobalAuthorizationVersion, arg.UserID, arg.UpdatedAt)
	return err
}

const insertManagedPasswordCredential = `-- name: InsertManagedPasswordCredential :exec
INSERT INTO user_credentials (
    user_credential_id, user_id, credential_type, identifier, identifier_normalized,
    secret_hash, status, created_at, updated_at
) VALUES ($1, $2, 'PASSWORD', $3, $4, $5, 'ACTIVE', $6, $6)
`

type InsertManagedPasswordCredentialParams struct {
	UserCredentialID     pgtype.UUID
	UserID               pgtype.UUID
	Identifier           string
	IdentifierNormalized string
	SecretHash           pgtype.Text
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertManagedPasswordCredential(ctx context.Context, arg *InsertManagedPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, insertManagedPasswordCredential,
		arg.UserCredentialID,
		arg.UserID,
		arg.Identifier,
		arg.IdentifierNormalized,
		arg.SecretHash,
		arg.CreatedAt,
	)
	return err
}

const insertManagedUser = `-- name: InsertManagedUser :one
INSERT INTO users (
    user_id, username, username_normalized, employee_no, employee_no_normalized,
    display_name, email, email_normalized, phone, system_role, status, locale,
    timezone, created_by_user_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'ACTIVE', $11, $12, $13, $14, $14
)
RETURNING user_id, username, username_normalized, employee_no, employee_no_normalized,
          display_name, email, email_normalized, phone, system_role, status, locale,
          timezone, last_login_at, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type InsertManagedUserParams struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Locale               string
	Timezone             string
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

type InsertManagedUserRow struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Status               string
	Locale               string
	Timezone             string
	LastLoginAt          pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

func (q *Queries) InsertManagedUser(ctx context.Context, arg *InsertManagedUserParams) (*InsertManagedUserRow, error) {
	row := q.db.QueryRow(ctx, insertManagedUser,
		arg.UserID,
		arg.Username,
		arg.UsernameNormalized,
		arg.EmployeeNo,
		arg.EmployeeNoNormalized,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.Phone,
		arg.SystemRole,
		arg.Locale,
		arg.Timezone,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i InsertManagedUserRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmployeeNo,
		&i.EmployeeNoNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.Phone,
		&i.SystemRole,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertPrincipalSecurityVersions = `-- name: InsertPrincipalSecurityVersions :exec
INSERT INTO principal_security_versions (user_id, updated_at)
VALUES ($1, $2)
`

type InsertPrincipalSecurityVersionsParams struct {
	UserID    pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPrincipalSecurityVersions(ctx context.Context, arg *InsertPrincipalSecurityVersionsParams) error {
	_, err := q.db.Exec(ctx, insertPrincipalSecurityVersions, arg.UserID, arg.UpdatedAt)
	return err
}

const insertUserOutboxEvent = `-- name: InsertUserOutboxEvent :exec
INSERT INTO outbox_events (
    outbox_event_id, aggregate_type, aggregate_id, aggregate_version, event_type,
    event_schema_version, payload_json, deduplication_key, correlation_id,
    max_attempts, available_at, created_at, updated_at
) VALUES ($1, 'USER', $2, $3, $4, 1, $5, $6, $7, 10, $8, $8, $8)
`

type InsertUserOutboxEventParams struct {
	OutboxEventID    pgtype.UUID
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
	PayloadJson      []byte
	DeduplicationKey string
	CorrelationID    pgtype.UUID
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertUserOutboxEvent(ctx context.Context, arg *InsertUserOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertUserOutboxEvent,
		arg.OutboxEventID,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.PayloadJson,
		arg.DeduplicationKey,
		arg.CorrelationID,
		arg.AvailableAt,
	)
	return err
}

const listManagedUserSessions = `-- name: ListManagedUserSessions :many
SELECT user_session_id, user_id, device_id, ip_address, user_agent, status, expires_at,
       last_seen_at, created_at, updated_at, revoked_at, revoke_reason, row_version
FROM user_sessions
WHERE user_id = $1
ORDER BY created_at DESC, user_session_id DESC
LIMIT $3::integer OFFSET $2::bigint
`

type ListManagedUserSessionsParams struct {
	UserID     pgtype.UUID
	PageOffset int64
	PageSize   int32
}

func (q *Queries) ListManagedUserSessions(ctx context.Context, arg *ListManagedUserSessionsParams) ([]*UserSession, error) {
	rows, err := q.db.Query(ctx, listManagedUserSessions, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.UserSessionID,
			&i.UserID,
			&i.DeviceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Status,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT user_id, username, username_normalized, employee_no, employee_no_normalized,
       display_name, email, email_normalized, phone, system_role, status, locale,
       timezone, last_login_at, created_by_user_id, created_at, updated_at, deleted_at, row_version
FROM users
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR system_role = $2::text)
ORDER BY created_at DESC, user_id DESC
LIMIT $4::integer OFFSET $3::bigint
`

type ListManagedUsersParams struct {
	Status     pgtype.Text
	SystemRole pgtype.Text
	PageOffset int64
	PageSize   int32
}

type ListManagedUsersRow struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Status               string
	Locale               string
	Timezone             string
	LastLoginAt          pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

func (q *Queries) ListManagedUsers(ctx context.Context, arg *ListManagedUsersParams) ([]*ListManagedUsersRow, error) {
	rows, err := q.db.Query(ctx, listManagedUsers,
		arg.Status,
		arg.SystemRole,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListManagedUsersRow{}
	for rows.Next() {
		var i ListManagedUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.UsernameNormalized,
			&i.EmployeeNo,
			&i.EmployeeNoNormalized,
			&i.DisplayName,
			&i.Email,
			&i.EmailNormalized,
			&i.Phone,
			&i.SystemRole,
			&i.Status,
			&i.Locale,
			&i.Timezone,
			&i.LastLoginAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveSystemAdministrators = `-- name: LockActiveSystemAdministrators :many
SELECT user_id
FROM users
WHERE system_role = 'SYSTEM_ADMIN'
  AND status = 'ACTIVE'
ORDER BY user_id
FOR UPDATE
`

func (q *Queries) LockActiveSystemAdministrators(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockActiveSystemAdministrators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSystemAdminMutation = `-- name: LockSystemAdminMutation :exec
SELECT pg_advisory_xact_lock(hashtext('file_workshop.system_admin_mutation'))
`

func (q *Queries) LockSystemAdminMutation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSystemAdminMutation)
	return err
}

const revokeManagedUserCredentials = `-- name: RevokeManagedUserCredentials :exec
UPDATE user_credentials
SET status = 'REVOKED',
    revoked_at = $2,
    revoke_reason = $3,
    updated_at = $2,
    row_version = row_version + 1
WHERE user_id = $1
  AND status = 'ACTIVE'
`

type RevokeManagedUserCredentialsParams struct {
	UserID       pgtype.UUID
	RevokedAt    pgtype.Timestamptz
	RevokeReason pgtype.Text
}

func (q *Queries) RevokeManagedUserCredentials(ctx context.Context, arg *RevokeManagedUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, revokeManagedUserCredentials, arg.UserID, arg.RevokedAt, arg.RevokeReason)
	return err
}

const revokeManagedUserRefreshTokens = `-- name: RevokeManagedUserRefreshTokens :exec
UPDATE session_refresh_tokens AS token
SET status = 'REVOKED',
    revoked_at = $2,
    updated_at = $2,
    row_version = token.row_version + 1
WHERE token.status = 'ACTIVE'
  AND EXISTS (
      SELECT 1 FROM user_sessions AS session
      WHERE session.user_session_id = token.user_session_id
        AND session.user_id = $1
  )
`

type RevokeManagedUserRefreshTokensParams struct {
	UserID    pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeManagedUserRefreshTokens(ctx context.Context, arg *RevokeManagedUserRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeManagedUserRefreshTokens, arg.UserID, arg.RevokedAt)
	return err
}

const revokeManagedUserSessions = `-- name: RevokeManagedUserSessions :exec
UPDATE user_sessions
SET status = 'REVOKED',
    revoked_at = $2,
    revoke_reason = $3,
    updated_at = $2,
    row_version = row_version + 1
WHERE user_id = $1
  AND status = 'ACTIVE'
`

type RevokeManagedUserSessionsParams struct {
	UserID       pgtype.UUID
	RevokedAt    pgtype.Timestamptz
	RevokeReason pgtype.Text
}

func (q *Queries) RevokeManagedUserSessions(ctx context.Context, arg *RevokeManagedUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeManagedUserSessions, arg.UserID, arg.RevokedAt, arg.RevokeReason)
	return err
}

const revokeOwnedUserSession = `-- name: RevokeOwnedUserSession :execrows
UPDATE user_sessions
SET status = 'REVOKED',
    revoked_at = $3,
    revoke_reason = 'USER_SESSION_REVOKED',
    updated_at = $3,
    row_version = row_version + 1
WHERE user_session_id = $1
  AND user_id = $2
  AND status = 'ACTIVE'
`

type RevokeOwnedUserSessionParams struct {
	UserSessionID pgtype.UUID
	UserID        pgtype.UUID
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) RevokeOwnedUserSession(ctx context.Context, arg *RevokeOwnedUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOwnedUserSession, arg.UserSessionID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOwnedUserSessionTokens = `-- name: RevokeOwnedUserSessionTokens :exec
UPDATE session_refresh_tokens AS token
SET status = 'REVOKED',
    revoked_at = $3,
    updated_at = $3,
    row_version = row_version + 1
WHERE token.user_session_id = $1
  AND token.status = 'ACTIVE'
  AND EXISTS (
      SELECT 1 FROM user_sessions AS session
      WHERE session.user_session_id = $1
        AND session.user_id = $2
  )
`

type RevokeOwnedUserSessionTokensParams struct {
	UserSessionID pgtype.UUID
	UserID        pgtype.UUID
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) RevokeOwnedUserSessionTokens(ctx context.Context, arg *RevokeOwnedUserSessionTokensParams) error {
	_, err := q.db.Exec(ctx, revokeOwnedUserSessionTokens, arg.UserSessionID, arg.UserID, arg.RevokedAt)
	return err
}

const setManagedUserStatus = `-- name: SetManagedUserStatus :one
UPDATE users
SET status = $2,
    deleted_at = $3,
    updated_at = $4,
    row_version = row_version + 1
WHERE user_id = $1
  AND row_version = $5
RETURNING user_id, username, username_normalized, employee_no, employee_no_normalized,
          display_name, email, email_normalized, phone, system_role, status, locale,
          timezone, last_login_at, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type SetManagedUserStatusParams struct {
	UserID     pgtype.UUID
	Status     string
	DeletedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	RowVersion int64
}

type SetManagedUserStatusRow struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Status               string
	Locale               string
	Timezone             string
	LastLoginAt          pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

func (q *Queries) SetManagedUserStatus(ctx context.Context, arg *SetManagedUserStatusParams) (*SetManagedUserStatusRow, error) {
	row := q.db.QueryRow(ctx, setManagedUserStatus,
		arg.UserID,
		arg.Status,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i SetManagedUserStatusRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmployeeNo,
		&i.EmployeeNoNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.Phone,
		&i.SystemRole,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}

const touchManagedUserForPasswordReset = `-- name: TouchManagedUserForPasswordReset :one
UPDATE users
SET updated_at = $2,
    row_version = row_version + 1
WHERE user_id = $1
  AND row_version = $3
RETURNING row_version
`

type TouchManagedUserForPasswordResetParams struct {
	UserID     pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	RowVersion int64
}

func (q *Queries) TouchManagedUserForPasswordReset(ctx context.Context, arg *TouchManagedUserForPasswordResetParams) (int64, error) {
	row := q.db.QueryRow(ctx, touchManagedUserForPasswordReset, arg.UserID, arg.UpdatedAt, arg.RowVersion)
	var row_version int64
	err := row.Scan(&row_version)
	return row_version, err
}

const tryCreateUserIdempotencyRecord = `-- name: TryCreateUserIdempotencyRecord :execrows
INSERT INTO idempotency_records (
    idempotency_record_id, principal_kind, user_id, operation, idempotency_key,
    request_hash, status, expires_at, created_at, updated_at
) VALUES ($1, 'USER', $2, 'CREATE_USER', $3, $4, 'IN_PROGRESS', $5, $6, $6)
ON CONFLICT DO NOTHING
`

type TryCreateUserIdempotencyRecordParams struct {
	IdempotencyRecordID pgtype.UUID
	UserID              pgtype.UUID
	IdempotencyKey      string
	RequestHash         []byte
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) TryCreateUserIdempotencyRecord(ctx context.Context, arg *TryCreateUserIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryCreateUserIdempotencyRecord,
		arg.IdempotencyRecordID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateManagedPasswordCredential = `-- name: UpdateManagedPasswordCredential :execrows
UPDATE user_credentials
SET secret_hash = $2,
    updated_at = $3,
    row_version = row_version + 1
WHERE user_id = $1
  AND credential_type = 'PASSWORD'
  AND status = 'ACTIVE'
`

type UpdateManagedPasswordCredentialParams struct {
	UserID     pgtype.UUID
	SecretHash pgtype.Text
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateManagedPasswordCredential(ctx context.Context, arg *UpdateManagedPasswordCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateManagedPasswordCredential, arg.UserID, arg.SecretHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateManagedUser = `-- name: UpdateManagedUser :one
UPDATE users
SET employee_no = $2,
    employee_no_normalized = $3,
    display_name = $4,
    email = $5,
    email_normalized = $6,
    phone = $7,
    system_role = $8,
    locale = $9,
    timezone = $10,
    updated_at = $11,
    row_version = row_version + 1
WHERE user_id = $1
  AND row_version = $12
RETURNING user_id, username, username_normalized, employee_no, employee_no_normalized,
          display_name, email, email_normalized, phone, system_role, status, locale,
          timezone, last_login_at, created_by_user_id, created_at, updated_at, deleted_at, row_version
`

type UpdateManagedUserParams struct {
	UserID               pgtype.UUID
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Locale               string
	Timezone             string
	UpdatedAt            pgtype.Timestamptz
	RowVersion           int64
}

type UpdateManagedUserRow struct {
	UserID               pgtype.UUID
	Username             string
	UsernameNormalized   string
	EmployeeNo           pgtype.Text
	EmployeeNoNormalized pgtype.Text
	DisplayName          string
	Email                pgtype.Text
	EmailNormalized      pgtype.Text
	Phone                pgtype.Text
	SystemRole           string
	Status               string
	Locale               string
	Timezone             string
	LastLoginAt          pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	RowVersion           int64
}

func (q *Queries) UpdateManagedUser(ctx context.Context, arg *UpdateManagedUserParams) (*UpdateManagedUserRow, error) {
	row := q.db.QueryRow(ctx, updateManagedUser,
		arg.UserID,
		arg.EmployeeNo,
		arg.EmployeeNoNormalized,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.Phone,
		arg.SystemRole,
		arg.Locale,
		arg.Timezone,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	var i UpdateManagedUserRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmployeeNo,
		&i.EmployeeNoNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.Phone,
		&i.SystemRole,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return &i, err
}
