// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentVersions = `-- name: CountDocumentVersions :one
SELECT count(*)::bigint
FROM document_versions
WHERE document_id = $1
`

func (q *Queries) CountDocumentVersions(ctx context.Context, documentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentVersions, documentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureDocumentLockCounter = `-- name: EnsureDocumentLockCounter :exec
INSERT INTO document_lock_counters (document_id, last_fencing_token, updated_at)
VALUES ($1, 0, $2)
ON CONFLICT (document_id) DO NOTHING
`

type EnsureDocumentLockCounterParams struct {
	DocumentID pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) EnsureDocumentLockCounter(ctx context.Context, arg *EnsureDocumentLockCounterParams) error {
	_, err := q.db.Exec(ctx, ensureDocumentLockCounter, arg.DocumentID, arg.UpdatedAt)
	return err
}

const expireDocumentLocks = `-- name: ExpireDocumentLocks :exec
UPDATE document_locks
SET status = 'EXPIRED',
    released_at = $1::timestamptz,
    release_reason = 'LOCK_EXPIRED',
    updated_at = $1::timestamptz,
    row_version = row_version + 1
WHERE document_id = $2::uuid
  AND status = 'ACTIVE'
  AND expires_at <= $1::timestamptz
`

type ExpireDocumentLocksParams struct {
	Now        pgtype.Timestamptz
	DocumentID pgtype.UUID
}

func (q *Queries) ExpireDocumentLocks(ctx context.Context, arg *ExpireDocumentLocksParams) error {
	_, err := q.db.Exec(ctx, expireDocumentLocks, arg.Now, arg.DocumentID)
	return err
}

const forceReleaseDocumentLock = `-- name: ForceReleaseDocumentLock :one
UPDATE document_locks
SET status = 'FORCED',
    released_at = $3,
    released_by_user_id = $4,
    release_reason = $5,
    updated_at = $3,
    row_version = row_version + 1
WHERE document_id = $1
  AND row_version = $2
  AND status = 'ACTIVE'
RETURNING document_lock_id, document_id, user_id, token_hash, fencing_token, source, status, acquired_at, heartbeat_at, expires_at, released_at, released_by_user_id, release_reason, created_at, updated_at, row_version
`

type ForceReleaseDocumentLockParams struct {
	DocumentID       pgtype.UUID
	RowVersion       int64
	ReleasedAt       pgtype.Timestamptz
	ReleasedByUserID pgtype.UUID
	ReleaseReason    pgtype.Text
}

func (q *Queries) ForceReleaseDocumentLock(ctx context.Context, arg *ForceReleaseDocumentLockParams) (*DocumentLock, error) {
	row := q.db.QueryRow(ctx, forceReleaseDocumentLock,
		arg.DocumentID,
		arg.RowVersion,
		arg.ReleasedAt,
		arg.ReleasedByUserID,
		arg.ReleaseReason,
	)
	var i DocumentLock
	err := row.Scan(
		&i.DocumentLockID,
		&i.DocumentID,
		&i.UserID,
		&i.TokenHash,
		&i.FencingToken,
		&i.Source,
		&i.Status,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getActiveDocumentLock = `-- name: GetActiveDocumentLock :one
SELECT document_lock_id, document_id, user_id, token_hash, fencing_token, source, status, acquired_at, heartbeat_at, expires_at, released_at, released_by_user_id, release_reason, created_at, updated_at, row_version
FROM document_locks
WHERE document_id = $1
  AND status = 'ACTIVE'
`

func (q *Queries) GetActiveDocumentLock(ctx context.Context, documentID pgtype.UUID) (*DocumentLock, error) {
	row := q.db.QueryRow(ctx, getActiveDocumentLock, documentID)
	var i DocumentLock
	err := row.Scan(
		&i.DocumentLockID,
		&i.DocumentID,
		&i.UserID,
		&i.TokenHash,
		&i.FencingToken,
		&i.Source,
		&i.Status,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getActiveDocumentLockForUpdate = `-- name: GetActiveDocumentLockForUpdate :one
SELECT document_lock_id, document_id, user_id, token_hash, fencing_token, source, status, acquired_at, heartbeat_at, expires_at, released_at, released_by_user_id, release_reason, created_at, updated_at, row_version
FROM document_locks
WHERE document_id = $1
  AND status = 'ACTIVE'
FOR UPDATE
`

func (q *Queries) GetActiveDocumentLockForUpdate(ctx context.Context, documentID pgtype.UUID) (*DocumentLock, error) {
	row := q.db.QueryRow(ctx, getActiveDocumentLockForUpdate, documentID)
	var i DocumentLock
	err := row.Scan(
		&i.DocumentLockID,
		&i.DocumentID,
		&i.UserID,
		&i.TokenHash,
		&i.FencingToken,
		&i.Source,
		&i.Status,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT document_version_id, document_id, version_number, storage_object_id, size_bytes, sha256, mime_type, change_note, source_type, restored_from_version_id, created_by_user_id, created_at
FROM document_versions
WHERE document_id = $1
  AND document_version_id = $2
`

type GetDocumentVersionParams struct {
	DocumentID        pgtype.UUID
	DocumentVersionID pgtype.UUID
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg *GetDocumentVersionParams) (*DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.DocumentVersionID)
	var i DocumentVersion
	err := row.Scan(
		&i.DocumentVersionID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.StorageObjectID,
		&i.SizeBytes,
		&i.Sha256,
		&i.MimeType,
		&i.ChangeNote,
		&i.SourceType,
		&i.RestoredFromVersionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return &i, err
}

const getVersionDocumentContext = `-- name: GetVersionDocumentContext :one
SELECT
  d.document_id,
  e.space_id,
  d.owner_user_id,
  d.current_version_id,
  d.availability_status,
  d.row_version,
  e.lifecycle_status
FROM documents d
JOIN namespace_entries e ON e.namespace_entry_id = d.document_id
JOIN spaces s ON s.space_id = e.space_id
WHERE d.document_id = $1
  AND e.entry_type = 'DOCUMENT'
  AND e.lifecycle_status = 'ACTIVE'
  AND s.status = 'ACTIVE'
`

type GetVersionDocumentContextRow struct {
	DocumentID         pgtype.UUID
	SpaceID            pgtype.UUID
	OwnerUserID        pgtype.UUID
	CurrentVersionID   pgtype.UUID
	AvailabilityStatus string
	RowVersion         int64
	LifecycleStatus    string
}

func (q *Queries) GetVersionDocumentContext(ctx context.Context, documentID pgtype.UUID) (*GetVersionDocumentContextRow, error) {
	row := q.db.QueryRow(ctx, getVersionDocumentContext, documentID)
	var i GetVersionDocumentContextRow
	err := row.Scan(
		&i.DocumentID,
		&i.SpaceID,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.AvailabilityStatus,
		&i.RowVersion,
		&i.LifecycleStatus,
	)
	return &i, err
}

const getVersionDocumentForUpdate = `-- name: GetVersionDocumentForUpdate :one
SELECT document_id, owner_user_id, current_version_id, availability_status, extension_normalized, inheritance_mode, acl_version, classification, metadata_schema_version, metadata_json, created_at, updated_at, row_version
FROM documents
WHERE document_id = $1
FOR UPDATE
`

func (q *Queries) GetVersionDocumentForUpdate(ctx context.Context, documentID pgtype.UUID) (*Document, error) {
	row := q.db.QueryRow(ctx, getVersionDocumentForUpdate, documentID)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.OwnerUserID,
		&i.CurrentVersionID,
		&i.AvailabilityStatus,
		&i.ExtensionNormalized,
		&i.InheritanceMode,
		&i.AclVersion,
		&i.Classification,
		&i.MetadataSchemaVersion,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const heartbeatDocumentLock = `-- name: HeartbeatDocumentLock :one
UPDATE document_locks
SET heartbeat_at = $4,
    expires_at = $5,
    updated_at = $4,
    row_version = row_version + 1
WHERE document_id = $1
  AND token_hash = $2
  AND row_version = $3
  AND user_id = $6
  AND status = 'ACTIVE'
  AND expires_at > $4
RETURNING document_lock_id, document_id, user_id, token_hash, fencing_token, source, status, acquired_at, heartbeat_at, expires_at, released_at, released_by_user_id, release_reason, created_at, updated_at, row_version
`

type HeartbeatDocumentLockParams struct {
	DocumentID  pgtype.UUID
	TokenHash   []byte
	RowVersion  int64
	HeartbeatAt pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	UserID      pgtype.UUID
}

func (q *Queries) HeartbeatDocumentLock(ctx context.Context, arg *HeartbeatDocumentLockParams) (*DocumentLock, error) {
	row := q.db.QueryRow(ctx, heartbeatDocumentLock,
		arg.DocumentID,
		arg.TokenHash,
		arg.RowVersion,
		arg.HeartbeatAt,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i DocumentLock
	err := row.Scan(
		&i.DocumentLockID,
		&i.DocumentID,
		&i.UserID,
		&i.TokenHash,
		&i.FencingToken,
		&i.Source,
		&i.Status,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const incrementDocumentLockCounter = `-- name: IncrementDocumentLockCounter :one
UPDATE document_lock_counters
SET last_fencing_token = last_fencing_token + 1,
    updated_at = $2
WHERE document_id = $1
RETURNING last_fencing_token
`

type IncrementDocumentLockCounterParams struct {
	DocumentID pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) IncrementDocumentLockCounter(ctx context.Context, arg *IncrementDocumentLockCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementDocumentLockCounter, arg.DocumentID, arg.UpdatedAt)
	var last_fencing_token int64
	err := row.Scan(&last_fencing_token)
	return last_fencing_token, err
}

const insertDocumentLock = `-- name: InsertDocumentLock :one
INSERT INTO document_locks (
  document_lock_id, document_id, user_id, token_hash, fencing_token,
  source, status, acquired_at, heartbeat_at, expires_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, 'ACTIVE', $7, $7, $8, $7, $7
)
RETURNING document_lock_id, document_id, user_id, token_hash, fencing_token, source, status, acquired_at, heartbeat_at, expires_at, released_at, released_by_user_id, release_reason, created_at, updated_at, row_version
`

type InsertDocumentLockParams struct {
	DocumentLockID pgtype.UUID
	DocumentID     pgtype.UUID
	UserID         pgtype.UUID
	TokenHash      []byte
	FencingToken   int64
	Source         string
	AcquiredAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) InsertDocumentLock(ctx context.Context, arg *InsertDocumentLockParams) (*DocumentLock, error) {
	row := q.db.QueryRow(ctx, insertDocumentLock,
		arg.DocumentLockID,
		arg.DocumentID,
		arg.UserID,
		arg.TokenHash,
		arg.FencingToken,
		arg.Source,
		arg.AcquiredAt,
		arg.ExpiresAt,
	)
	var i DocumentLock
	err := row.Scan(
		&i.DocumentLockID,
		&i.DocumentID,
		&i.UserID,
		&i.TokenHash,
		&i.FencingToken,
		&i.Source,
		&i.Status,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const insertRestoredDocumentVersion = `-- name: InsertRestoredDocumentVersion :one
WITH source_version AS (
  SELECT document_version_id, document_id, version_number, storage_object_id, size_bytes, sha256, mime_type, change_note, source_type, restored_from_version_id, created_by_user_id, created_at
  FROM document_versions
  WHERE document_id = $2::uuid
    AND document_version_id = $6::uuid
),
next_number AS (
  SELECT COALESCE(MAX(version_number), 0) + 1 AS version_number
  FROM document_versions
  WHERE document_id = $2::uuid
)
INSERT INTO document_versions (
  document_version_id, document_id, version_number, storage_object_id,
  size_bytes, sha256, mime_type, change_note, source_type,
  restored_from_version_id, created_by_user_id, created_at
)
SELECT
  $1::uuid,
  $2::uuid,
  next_number.version_number,
  source_version.storage_object_id,
  source_version.size_bytes,
  source_version.sha256,
  source_version.mime_type,
  $3::text,
  'RESTORE',
  source_version.document_version_id,
  $4::uuid,
  $5::timestamptz
FROM source_version, next_number
RETURNING document_version_id, document_id, version_number, storage_object_id, size_bytes, sha256, mime_type, change_note, source_type, restored_from_version_id, created_by_user_id, created_at
`

type InsertRestoredDocumentVersionParams struct {
	DocumentVersionID     pgtype.UUID
	DocumentID            pgtype.UUID
	ChangeNote            pgtype.Text
	CreatedByUserID       pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	RestoredFromVersionID pgtype.UUID
}

func (q *Queries) InsertRestoredDocumentVersion(ctx context.Context, arg *InsertRestoredDocumentVersionParams) (*DocumentVersion, error) {
	row := q.db.QueryRow(ctx, insertRestoredDocumentVersion,
		arg.DocumentVersionID,
		arg.DocumentID,
		arg.ChangeNote,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.RestoredFromVersionID,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.DocumentVersionID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.StorageObjectID,
		&i.SizeBytes,
		&i.Sha256,
		&i.MimeType,
		&i.ChangeNote,
		&i.SourceType,
		&i.RestoredFromVersionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return &i, err
}

const insertVersionOutboxEvent = `-- name: InsertVersionOutboxEvent :exec
INSERT INTO outbox_events (
  outbox_event_id, aggregate_type, aggregate_id, aggregate_version,
  event_type, event_schema_version, payload_json, deduplication_key, correlation_id,
  max_attempts, available_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4,
  $5, 1, $6, $7, $8,
  10, $9, $9, $9
)
`

type InsertVersionOutboxEventParams struct {
	OutboxEventID    pgtype.UUID
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
	PayloadJson      []byte
	DeduplicationKey string
	CorrelationID    pgtype.UUID
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertVersionOutboxEvent(ctx context.Context, arg *InsertVersionOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertVersionOutboxEvent,
		arg.OutboxEventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.PayloadJson,
		arg.DeduplicationKey,
		arg.CorrelationID,
		arg.AvailableAt,
	)
	return err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT document_version_id, document_id, version_number, storage_object_id, size_bytes, sha256, mime_type, change_note, source_type, restored_from_version_id, created_by_user_id, created_at
FROM document_versions
WHERE document_id = $1::uuid
ORDER BY version_number DESC, document_version_id DESC
LIMIT $3::integer OFFSET $2::bigint
`

type ListDocumentVersionsParams struct {
	DocumentID pgtype.UUID
	PageOffset int64
	PageSize   int32
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg *ListDocumentVersionsParams) ([]*DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DocumentID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.DocumentVersionID,
			&i.DocumentID,
			&i.VersionNumber,
			&i.StorageObjectID,
			&i.SizeBytes,
			&i.Sha256,
			&i.MimeType,
			&i.ChangeNote,
			&i.SourceType,
			&i.RestoredFromVersionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDocumentLock = `-- name: ReleaseDocumentLock :one
UPDATE document_locks
SET status = 'RELEASED',
    released_at = $5,
    released_by_user_id = $6,
    release_reason = $7,
    updated_at = $5,
    row_version = row_version + 1
WHERE document_id = $1
  AND token_hash = $2
  AND row_version = $3
  AND user_id = $4
  AND status = 'ACTIVE'
RETURNING document_lock_id, document_id, user_id, token_hash, fencing_token, source, status, acquired_at, heartbeat_at, expires_at, released_at, released_by_user_id, release_reason, created_at, updated_at, row_version
`

type ReleaseDocumentLockParams struct {
	DocumentID       pgtype.UUID
	TokenHash        []byte
	RowVersion       int64
	UserID           pgtype.UUID
	ReleasedAt       pgtype.Timestamptz
	ReleasedByUserID pgtype.UUID
	ReleaseReason    pgtype.Text
}

func (q *Queries) ReleaseDocumentLock(ctx context.Context, arg *ReleaseDocumentLockParams) (*DocumentLock, error) {
	row := q.db.QueryRow(ctx, releaseDocumentLock,
		arg.DocumentID,
		arg.TokenHash,
		arg.RowVersion,
		arg.UserID,
		arg.ReleasedAt,
		arg.ReleasedByUserID,
		arg.ReleaseReason,
	)
	var i DocumentLock
	err := row.Scan(
		&i.DocumentLockID,
		&i.DocumentID,
		&i.UserID,
		&i.TokenHash,
		&i.FencingToken,
		&i.Source,
		&i.Status,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.ReleasedByUserID,
		&i.ReleaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return &i, err
}

const setDocumentCurrentVersion = `-- name: SetDocumentCurrentVersion :execrows
UPDATE documents
SET current_version_id = $2,
    availability_status = 'PENDING_SCAN',
    updated_at = $3,
    row_version = row_version + 1
WHERE document_id = $1
  AND row_version = $4
`

type SetDocumentCurrentVersionParams struct {
	DocumentID       pgtype.UUID
	CurrentVersionID pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
	RowVersion       int64
}

func (q *Queries) SetDocumentCurrentVersion(ctx context.Context, arg *SetDocumentCurrentVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDocumentCurrentVersion,
		arg.DocumentID,
		arg.CurrentVersionID,
		arg.UpdatedAt,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
